#  record.org --- file used to record reading, running, etc
#+PROPERTY: READING_ALL 0 1
#+PROPERTY: READING
#+PROPERTY: MOVIE_ALL 0 1
#+PROPERTY: MOVIE
#+PROPERTY: SOULSOUP
#+PROPERTY: SOULSOUP_ALL 1 0

* Reading

** 我的读书

*** 读什么书？

读小说、读历史、读经管、读科普、读诗歌、读经典

*** 我喜欢读什么样的书

我喜欢阅读怎样的书呢？现在我对这个问题有了进一步的了解。

一是小说。小说是我的最爱，包括西方古典小说，以及王小波和村上春树。

二是历史。历史可以很有趣的。

三是哲学。我总是有太多的问题在思考，那么我为何不把这样过剩的精力花费在
值得的地方呢？我一直在追求自己的信仰，哲学是对此最好的解答。

*** 什么时候读书？

尽量睡前读半个小时到一个小时，白天主要精力还是要放在学习上，读书反倒会
成为一件虚荣心作祟和分心的事情。不过呢，随身携带一杯书装在包里的习惯不
须改，万事没有绝对。

*** 可以同时读多本书么？

最好不要。专一，求质，亦求量，求思考，不同类型的书最好交叉开来读。

*** 读书是一生的事

毋庸置疑，我喜欢阅读。我知道自己在读书上很迟钝，每每总是理解地过于片面
和肤浅，但我在坚持，会有改善的。

*** 纸质阅读 VS 电子阅读

纸质阅读自然最是享受，但是有所不便。Kindle带来了改变，提供了接近纸质阅
读的感受，成为了我的一种生活方式。

*** 学习德语与读书

德语文学和哲学是世界史上的极为重要的一部分，所以好好学习德语，以求能够
阅读英文原著。像歌德、康德、尼采、黑塞等等。

*** 关于外文书籍

- 外文 VS 译本

  - +能够阅读原著和便不读翻译+  （两者不矛盾，不偏废， 英文书籍最好也读原文）
  - 能够阅读原著自然是最好的了。

- 英文阅读的能力，我已经培养了不少，这样阅读英美文学便成了可能。

- 中文翻译的书籍要选取优质的译本

*** 电子书管理规范

+ 主要方式按作者分类

  - 因为我喜欢阅读经典，所以多数书的作者值得阅读的作品往往不止一部
  - 和音乐、电影的组织模式类似

+ 次要方式按体裁分类，可以将主要分类方式的作品使用软链链接到对应题材下

+ 渐近式地整理

  - 不要一次性整理，费时费精力
  - 而且，组织方式总是在进化，不是一尘不变的
  - 读一本，整理一本，可以整理同一作者类似的，已读的

+ 尽量避免合集

+ 单本存放更容易管理

  - 每本书单独建立一个文件夹
  - 存放 EPUB 和 MOBI 两种格式的电子书
  - 存放 PDF 文件
  - 存放外文原版
  - 还可以存放其他相关信息
+ 择优
  - 别字少
  - 排版优
  - 大纲齐全

*** Kindle 使用准则

+ 极简

+ 充分利用：阅读的内核并不在介质

+ 不折腾

  - 不越狱不刷机：想要折腾的话，玩ARM去

+ 简洁

  - +同一时间只放两本书，一本中文，一本英文+
  - 开始界面只放当前阅读的书
  - 仅建立两个文件夹 READ 和 TOREAD

+ 不虚荣

  - +不使用类似“已读”、“最爱“之类的收藏夹，也不使用收藏夹+

+ +使用 Evernote 保存 Kindle 摘录+ 使用 Org-mode 保存 Kindle 摘录

*** 关于 Evernote: 可以收藏，但编辑不行

使用印象笔记收藏笔记还可以，简单的编辑也可以，但要作复杂的编辑简直折腾
死人

使用 Orgmode 收藏 kindle 读书笔记。

使用 Evernote 收录豆瓣的书评。

*** TODO 关于速读
*** 如何使用 ORG-MODE + Kindle 系统地建立读书笔记

1. org-mode 和 evernote 各有千秋，就做读书笔记而言

   1) Org-mode 更为系统完备
   2) Emacs 赋予 Org-mode 无以伦比的编辑能力
   3) 做笔记的方式必然会在不断更新， Org-mode 更为灵活

2. 纸质版 VS 电子版（这个已经考虑过许多次）

   1) 如果我的字迹耐看，那么手写必然是首先，但是事实并非如此
   2) 为了备份纸质版的笔记，也会将其扫描成电子版
   3) 不论两者怎么交替，电子版笔记都不可或缺

*** org-mode properties

** 书单
*** 无出其右者

- [X] 《红楼梦》

- [X] 《小王子》

*** 西方文学

- [ ] 《红与黑》作者：[法]司汤达

- [ ] 《玩偶之家》 [挪威]易卜生

**** 雨果

- [ ] 《悲惨世界》

**** 列夫托尔斯泰

- [X] 《安娜卡列妮娜》
- [ ] 《复活》
- [ ] 《战争与和平》

*** 古典国学

- [ ] 《金瓶梅》

- [X] 《肉蒲团》。

- [ ] 《孙子兵法》

- [ ] 《山海经》

- [ ] 《冰室合集》

- [ ] 《明夷待访录》

*** 历史

- [ ] 《史记》

- [ ] 《资治通鉴》

- [ ] 《全球通史》

- [ ] 《历史研究》

- [ ] 《西方的没落》

- [ ] 《西行漫记》

- [ ] 《高卢战记》

*** 哲学

- [ ] 《伦理学》

- [ ] 《理想国》

- [ ] 《爱因斯坦文集》

**** 罗素

- [ ] 《西方哲学史》

**** 康德

- [ ] 《纯粹理性批判》

*** 现代小说

- [ ] 《芙蓉镇》 古华

- [X] 《平凡的世界》 路遥

  这一本呕心沥血写成的百万字的长篇巨著全景式地表现中国当代城乡社会生活。
  路遥在中国70年代中期到80年代中期近十年间的广阔背景上，通过复杂的矛盾
  纠葛，以孙少安和孙少平两兄弟为代表展开了劳动与爱情、挫折与追求、痛苦
  与欢乐、日常生活与巨大社会冲突纷繁地交织在一起，深刻地展示了普通人在
  大时代历史进程中所走过的艰难曲折的道路，故事的广阔和深刻可谓是改革开
  放以来最可读的书之一。

- [X] 《百年孤独》 [哥伦比亚]加西亚·马尔克斯

  这是一本艰涩难懂的书，通篇充满了怪异的人和离奇的故事，马尔克斯用马尔
  克斯在书中溶汇了南美洲特有的五彩缤纷的文化。他通过描写小镇马孔多的产
  生、兴盛到衰落、消亡，表现了拉丁美洲令人惊异的疯狂历史。在这本书中隐
  藏着许多关于拉美世界和现代文明的思考，其不可思议的奇迹和最纯粹的现实
  生活的结合，以及深入独到的笔力文风，使其成为文学史上巨著。

- [ ] 《小团圆》 张爱玲。

  学者读者皆认为《小团圆》带有强烈的自传性质。小说中男女主角的恋情基本
  就是张爱玲与胡兰成的恋情记录。

  ‘他的头发拂在她大腿上，毛参参的不知道什么野兽的头。兽在幽暗的岩洞里
  的一线黄泉就饮，泊泊的用舌头卷起来。她是洞口倒挂着的蝙蝠，深山中藏匿
  的遗民，被侵犯了，被发现了，无助的，无告的，有只动物在小口小口地啜着
  她的核心。’

  女性写性，柔软细腻，动情至深。而张爱玲的文字，又如此独特，见之使人痴
  迷。

- [ ] 《废都》  贾平凹。

  季羡林说：三十年后这本书会大放异彩。93年出版至今已经二十二年了，虽说
  解禁，但这本书却没有了出版当时知识分子人手一册的轰动。这本书不止性爱，
  但性爱有很大篇幅，四十万字的长篇，大致有两万字纯写性爱。其中庄之蝶、
  唐宛儿等人物，食色性也。

  初看此书，惊呼：只怕贾平凹老师要来个《红楼梦》和《金瓶梅》的大杂烩了
  吧。李敬泽说此书：走向极致的实，又走向极致的虚。这是本书不止于情色的
  思想深度。有关中国的风俗人情、吃喝玩乐，利害关系，写得趣味而耐看，也
  是一种写作本领。能在闲淡琐碎之中让人轻轻一叹，也是一种写作境界。

  百年之后，贾平凹的文字还会有人读的。

**** 王小波

***** 小说
- [ ] 《唐人秘传故事》1990年8月 山东文艺出版社

- [ ] 《王二风流史》1992年3月 香港繁荣出版社

- [X] 《黄金时代》1992年8月 台湾联经出版社 / 1997年7月 花城出版社

- [ ] 《白银时代》1997年7月 花城出版社

- [ ] 《青铜时代》 1997年7月 花城出版社

- [ ] 《黑铁时代》王小波早期作品及未竟稿集， 1998年2月 时代文艺出版社

- [ ] 英译本《王二的爱欲枷锁》("Wang in Love and Bondage") 2007年3月
  纽约州立大学出版社

***** 杂文集

- [ ] 《思维的乐趣》1996年11月

- [ ] 《我的精神家园》1997年5月

- [ ] 《沉默的大多数》1997年10月

- [ ] 《理想国与哲人王》

***** 书信集

- [ ] 《爱你就像爱生命》（与李银河合著）2004年5月

***** 电影文学剧本

- [ ] 《东宫西宫》

***** 其它

- [ ] 《未来世界》1995年7月

- [ ] 《地久天长》1998年2月

- [ ] 《他们的世界——中国男同性恋群落透视》与李银河合著 1992年1月

**** 海明威

***** 小说

- [ ]《老人与海》

  《老人与海》是海明威最著名的作品之一，它围绕一位老年古巴渔夫，与一条
  巨大的马林鱼在离岸很远的湾流中搏斗的故事。海明威电报式的简洁有力的写
  作风格，“冰山”原则指导下的荡人心魄描写，都在这片文章中得到了淋漓尽
  致的展现。海上捕鱼老人的拼搏、勇毅、不屈服，让每个人心中都波涛汹涌。

- [ ] 1925年：《春潮》（The Torrents of Spring）

- [ ] 1926年：《太阳依旧升起》（The Sun Also Rises）

- [ ] 1929年：《永别了，武器》（A Farewell to Arms）

- [ ] 1937年：《有钱人与没钱人》（To Have and Have Not）

- [ ] 1940年：《丧钟为谁而鸣》，或译《丧钟为谁而鸣》（For Whom the
  Bell Tolls）

- [ ] 1950年：《渡河入林》（Across the River and Into the Trees）

- [ ] 1952年：《老人与海》（The Old Man and the Sea）

- [ ] 1970年：《岛之恋》（Islands in the Stream）

- [ ] 1985年：《伊甸园》（The Garden of Eden）

- [ ] 1999年：《曙光示真》（True At First Light）

- [ ] 2005年：《乞力马扎罗下》（Under Kilimanjaro）

***** 非小说

- [ ] 1932年：《午后之死》，或译《死在午后》（Death in the Afternoon）

- [ ] 1935年：《非洲的青山》（Green Hills of Africa）

- [ ] 1962年：《Hemingway, The Wild Years》

- [ ] 1964年：《流动的飨宴》（A Moveable Feast）

- [ ] 1967年：《By-Line: Ernest Hemingway》

- [ ] 1970年：《Ernest Hemingway: Cub Reporter》

- [ ] 1981年：《Ernest Hemingway Selected Letters 1917-1961》

- [ ] 1985年：《危险夏日》（The Dangerous Summer）

- [ ] 1985年：《Dateline: Toronto》

***** 短篇小说

- [ ] 1923年：《三个故事和十首诗》（Three Stories and Ten Poems）

- [ ] 1925年：《雨中的猫》（Cat in the Rain）

- [ ] 1925年：《在我们的时代里》（In Our Time）

- [ ] 1927年：《没有女人的男人》（Men Without Women）

- [ ] 1932年：《乞力马扎罗的雪》（The Snows of Kilimanjaro）1933年：
  《胜者一无所获》（Winner Take Nothing）

- [ ] 1938年：《第五纵队与49个故事》（The Fifth Column and the First
  Forty-Nine Stories）

- [ ] 1972年：《尼克·亚当斯故事集》（The Nick Adams Stories）

- [ ] 1987年：《海明威短篇故事全集》（The Complete Short Stories of
  Ernest Hemingway）

- [ ] 1995年：《海明威故事选集》（Everyman's Library: The Collected
  Stories）

**** 村上春树

- [ ] 1979年 且听风吟 風の歌を聴け

- [ ] 1980年 1973年的弹子球 1973年のピンボール

- [ ] 1982年 寻羊冒险记 羊をめぐる冒険

- [ ] 1985年 世界尽头与冷酷仙境 世界の終りと

- [ ] ハードボイルド・ワンダーランド

- [ ] 1987年 挪威的森林 ノルウェイの森

- [ ] 1988年 舞！舞！舞！ ダンス・ダンス・ダンス

- [ ] 1992年 国境以南 太阳以西 国境の南、太陽の西

- [ ] 1994年－1995年 奇鸟行状录 ねじまき鳥クロニクル

- [ ] 1999年 斯普特尼克恋人 スプートニクの恋人

- [ ] 2002年 海边的卡夫卡 海辺のカフカ

- [ ] 2004年 天黑以后 アフターダーク

- [ ] 2009年－2010年 1Q84 1Q84

- [ ] 2013年 没有色彩的多崎作和他的巡礼之年 色彩を持たない多崎つくると、
  彼の巡礼の年

**** 金庸
- [ ] 飞狐外传

- [ ] 雪山飞狐

- [ ] 连城诀

- [ ] 天龙八部

- [ ] 射雕英雄传

- [ ] 白马啸西风

- [ ] 鹿鼎记

- [ ] 笑傲江湖

- [ ] 书剑恩仇录

- [ ] 神雕侠侣

- [ ] 侠客行

- [ ] 倚天屠龙记

- [ ] 碧血剑

- [ ] 鸳鸯刀

*** 社科

**** 心理

- [X] 《爱的艺术》  弗洛姆

  爱情是大学期间一门重要的必修课，心理学家弗洛姆这本著名的《爱的艺术》
  一定能够对你有所帮助。弗洛姆认为，不成熟的、幼稚的爱是“我爱你，因为
  我需要你。”，而成熟的爱是“我需要你，因为我爱你。”。希望从这本书中
  得到追求攻略的同学往往会失望，但是如果你静下心，就可以从本书中读出爱
  的艺术的真谛。

- [ ] 《追寻生命的意义》  弗兰克尔

  弗兰克尔是20世纪著名的心理学家，纳粹时期，作为犹太人，他的全家都被关
  进了奥斯威辛集中营，他的父母、妻子、哥哥，全都死于毒气室中，只有他和
  妹妹幸存。弗兰克尔不但超越了这炼狱般的痛苦，更将自己的经验与学术结合，
  开创了意义疗法，替人们找到绝处再生的意义。本书第一部分叙述了弗兰克尔
  的集中营经历，第二部分阐述了他的“意义疗法”。本书不仅适合于心理学爱
  好者，也适合面临挑战希望寻找生活意义的人们。

- [ ] 《拖延心理学》  简·博克, 莱诺拉·袁

  你想要向拖延的恶习开刀吗？这两位加利福尼亚心理学家在她们治疗拖延者的
  实践中精准地捕捉到了拖延的根本原因。这本书可以帮助读者减轻拖延，更好
  地享受生活。

- [ ] 《梦的解析》  [奥地利]弗洛伊德

  弗洛伊德的《梦的解析》被誉为精神分析的第一名著。它通过对梦境的科学探
  索和解释，找破了几千年来人类对梦的无知、迷信和秘感，同时揭示了左右人
  们思想和行为的潜意识的奥秘。不管你是否对心理学感兴趣，这本书都会带给
  你看待人的精神世界的一个新的视角。

- [ ] 《麦肯锡方法》  [美]埃森・M・拉塞尔

  《麦肯锡方法》披露了麦肯锡小心守护的一系列管理技巧——那些可以帮助任何
  水平的任何人像麦肯锡顾问一样思考的工具。这是一套你可以应用在任何社工、
  实习、团队管理中的方法，像你的咨询顾问一样，为你指出通向成功的解决方
  案。这是从事咨询行业的必读书，也是希望丰富管理素养、提升自身领导力的
  同学的良好参考。

- [ ] 《人的潜能和价值》  [美]马斯洛等

  一个广为人知的理论认为，人脑有上千亿个细胞，其中98.5％－99％的细胞处
  于休眠状态，大约有1％－1.5％的细胞参加脑的神经功能活动，这说明人的潜
  能有极大的发挥空间。《人的潜能和价值》是人本主义心理学有关“人的潜能
  和价值”讨论的论文集。主要选录了马斯洛等有关人心理学价值观点的文章。
  这本书中收录了著名的马斯洛需求层次理论，该理论在心理学、管理学等众多
  领域影响很大。本书是希望开发自身潜能和价值的同学所必读的一本好书。

- [ ] 《心理学与生活》  [美]理查德·格里格

  本书是心理学的入门经典，是美国斯坦福大学多年来使用的教材，也是在美国
  许多大学里推广使用的经典教材，被ETS推荐为GRE心理学专项考试的主要参考
  用书。这本书写作流畅，通俗易懂，深入生活，把心理学理论与知识联系人们
  的日常生活与工作，使它同样也成为一般人了解心理学与自己的极好的读物。

- [ ] 《设计心理学》  [美]唐纳德·A·诺曼

  本书是对产品设计感兴趣同学的必读书。诺曼博士本书中强调以使用者为中心
  的设计哲学，提醒消费者在挑选的物品，必须要方便好用，易于理解，希望设
  计师在注重设计美感的同时，不要忽略设计的一些必要因素，因为对于产品设
  计来说，安全好用永远是竞争的关键。虽然本书讨论的是日常用品的设计，但
  是其思想同样适合于互联网产品的设计，建议计算机相关专业的同学阅读。

- [ ] 《乌合之众：大众心理研究》  [法]古斯塔夫·勒庞

  这本书是社会心理学领域的经典著作，至今已被翻译成近20种语言出版。在书
  中，作者以十分简约的方式，考察了群体的特殊心理与思维方式，尤其对个人
  与群体的迥异心理进行了精辟分析。二战中日本普通民众如何变成丧尽天良的
  战争机器，“文革”中的单纯学生又为何会作出那许多丧心病狂的举动？个人
  到群体的变化总是叫人难以理解、难以置信，此书的解释，或能稍解你的困惑。

- [ ] 《自私的基因》  [英]里查德·道金斯

  这是一本关于进化论的书，但是从这本书中读者可以获得关于人类行为的许多
  启发。道金斯使用“自私的基因”来表达基因中心的进化论观点。这种观点和
  基于物种或生物体的进化论观点不同，能够解释生物体之间的各种利他行为。

**** 社会

- [ ] 《一九八四》  [英]乔治·奥威尔

  这一部奥威尔的传世之作，堪称世界文坛上最著名的政治讽喻小说。他在小说
  中他创造的“老大哥”、“双重思想”、“新话”等词汇都已收入权威的英语
  词典，甚至由他的姓衍生了一个形容词“奥威尔式”不断出现在报道国际新闻
  的记者笔下，足见其在英语国家影响之深远。

- [ ] 《政府论》  [英]洛克

  《政府论》英国约翰·洛克的政治著作，出版于1690年。本书可视为政治学的
  研究范畴，但对法学研究而言，此书亦属必读之列。《政府论》汇集了洛克的
  主要政治哲学思想，不仅使洛克成为古典自由主义思想的集大成者，而且对于
  后世的现实政治产生了深远的影响.

- [ ] 《社会契约论》  [法]卢梭

  《社会契约论》是法国思想家让•雅克•卢梭于1762年写成的一本书。《社会契
  约论》中主权在民的思想，是现代民主制度的基石，深刻地影响了逐步废除欧
  洲君主绝对权力的运动，和18世纪末北美殖民地摆脱英帝国统治、建立民主制
  度的斗争。美国的《独立宣言》和法国的《人权宣言》及两国的宪法均体现了
  《社会契约论》的民主思想。

- [ ] 《资本论》  [德]马克思

  《资本论》是马克思用毕生的心血写成的一部光辉灿烂的科学巨著，这部巨著
  第一次深刻地分析了资本主义的全部发展过程，以数学般的准确性证明这一发
  展的方向必然引导到社会主义革命和无产阶级专政的确立。研究各种学科的知
  识分子都应读读这部巨著。

- [ ] 《论法的精神》  [法]孟德斯鸠

  公认的十八世纪最伟大的、最深远地影响了历史的作品是哪几部？人们可以很
  轻易地说出亚当施密的《国富论》、卢梭的《社会契约论》和孟德斯鸠的《论
  法的精神》。《论法的精神》以法律为中心，又遍涉经济、政治、宗教、历史、
  地理等领域，内容极为丰富。《论法的精神》中提出的“追求自由”、“主张
  法制”、“三权分立”等理论，极大地影响了人类社会的发展进程，成为了美、
  英、法等国的立国之本。

- [ ] 《共产党宣言》  [德]马克思

  《共产党宣言》又译《共产主义宣言》，是卡尔•马克思和弗里德里希•恩格斯
  为共产主义者同盟起草的纲领，国际共产主义运动第一个纲领性文献，马克思
  主义诞生的重要标志。由马克思执笔写成 。1848年2月在伦敦第一次以单行本
  问世。宣言第一次全面系统地阐述了科学社会主义理论，指出共产主义运动已
  成为不可抗拒的历史潮流。

- [ ] 《论美国的民主》  [法]托克维尔

  《论美国的民主》这本书是世界学术界第一部对美国社会、政治制度和民情进
  行社会学研究的著作，也是第一部论述民主制度的专著，19世纪最著名的社会
  学著作之一，同时，它也是当代青年不可不读的经典名著之一。

- [ ] 《菊花与刀》  [美]鲁斯·本尼迪克特

  《菊花与刀》的前身是一份研究报告——作者受美国战时情报局委托写的有关日
  本的研究报告。后来在原报告基础上加上前后两章，即成此书。此书于1946年
  发表后反响巨大，亦成为日本最畅销的图书之一，因其学术价值和借鉴意义，
  60多年后依然长销不衰，成为文化人类学的典范之作，是了解我们一衣带水的
  近邻——日本民族的绕不过的经典读本。

- [ ] 《战争论》  [德]克劳塞维茨

  本书作者亲身参加过普法战争和法俄战争，积累了丰富的作战经验。他的思想
  还受到德国古典哲学的很大影响，这为他研究战争理论和写作此书提供了有利
  的主客观条件。作为西方军事史上的理论名著，它甚至受到过恩格斯和列宁的
  好评。正是这部著作最早提出了“战争是政治通过另一种手段（即暴力）的继
  续”这一著名的公理。

- [ ] 《正义论》  [美]约翰·罗尔斯

  罗尔斯在《正义论》当中提出了关于正义的两条原则：第一条是所谓平等的自
  由原则，即每个人应该在社会中享有平等的自由权利；第二条原则包括差别原
  则与机会平等原则。前者要求在进行分配的时候，如果不得不产生某种不平等
  的话，这种不平等应该有利于境遇最差的人们的最大利益，就是说，利益分配
  应该像处于不利地位的人们倾斜；后者要求将机会平等的原则应用于社会经济
  的不平等，使具有同等能力、技术与动机的人们享有平等的获得职位的机会。

- [ ] 《宽容》  [美]房龙

  在宽容与不宽容之间，宗教以血腥和仁慈维护着它几千年的统治，更迭变幻、
  不滞不流。从众神的黄昏到好奇的人，从宗教裁判所到新天堂，从耶稣基督到
  布鲁诺……历史席卷一切，也记忆一切。而在这一切之后，始终不离其左右，
  是利益抑或是人性？这是一部宗教的历史，一部宽容与不宽容的历史，也是一
  郜人性血腥与进步的历史。文图之间，《宽容》生动地再现了这一历史。

- [ ] 《浅薄》  [美]尼古拉斯·卡尔

  “谷歌在把我们变傻吗？”当尼古拉斯•卡尔在发表于《大西洋月刊》上赫赫
  有名的那篇封面文章中提出这个问题的时候，他就开启了人们热切渴望的期盼
  源泉，让人急于弄清楚互联网是在如何改变我们的。卡尔在本书中阐述了他对
  互联网时代的看法：互联网会在现代人的心智中打下深深的烙印。这本书会让
  你看到互联网对我们的影响的另一面。

- [ ] 《批评官员的尺度》  [美]安东尼·刘易斯

  这本书可以带给你一场理性精神的洗礼，是一次寻访理性的旅程。也许法律制
  度是不同的，文化源头是不同的，但是对理性的追求是人类共有的美德。不仅
  是新闻还是法律工作者还是普通读者，只要你想做一个现代社会的公民，你都
  可以而且应当把这本书当作一本政治启蒙书。

- [ ] 《失控》  [美]凯文·凯利

  这《失控》，全名为《失控：机器、社会与经济的新生物学》，是一部思考人
  类社会（或更一般意义上的复杂系统）进化的“大部头”著作，书中提到并且
  今天正在兴起或大热的概念包括：大众智慧、云计算、物联网、虚拟现实、敏
  捷开发、协作、双赢、共生、共同进化、网络社区、网络经济，等等。对于那
  些喜欢思考的的同学来说，阅读此书必然会开卷有益。

- [ ] 《浪潮之巅》  吴军

  近一百多年来，总有一些公司很幸运地、有意识或无意识地站在技术革命的浪
  尖之上。在这十几年间，它们代表着科技的浪潮，直到下一波浪潮的来临。在
  这些公司兴衰的背后，有着它必然的规律。本书不仅讲述科技工业的历史，更
  重在揭示它的规律性。 这是一本讲述IT行业历史的经典著作，作者吴军博
  士曾是Google公司的搜索专家，本书值得所有理工科学生和商科学生好好阅
  读。

- [ ] 《新教伦理与资本主义精神》  [德]马克斯·韦伯

  资本主义的兴起不仅仅是一个经济和政治制度的综合体，它还有着特殊的精神
  风格和文化意义，其所呈显的特征处处和某种宗教上的伦理态度相互呼应，共
  同构成了现代人普遍的生活方式。本书从文化的角度考察近代资本主义的兴起，
  探讨近代资本主义在欧洲而不是其他大陆发轫和发展的根源，让读者看到隐藏
  在制度背后的精神力量，从另一个视角来重新认识这套西方花了数百年时间才
  酝酿出来的资本主义生活秩序。

**** 社交

- [ ] 《人性的弱点》  [美]戴尔·卡内基

  “世界成功学第一书”，戴尔·卡耐基被称为美国“成人教育之父”，他运用
  社会学和心理学知识，对人性进行了深刻的探讨和分析。他讲述的许多普通人
  通过奋斗获得成功的真实故事，激励了无数陷入迷茫和困境的人，帮助他们重
  新找到了自己的人生。不管成功学有怎样的缺陷，这些故事对于处于迷茫中的
  同学无疑是一种指引和帮助。

- [ ] 《影响力》  罗伯特·B·西奥迪尼

  影响力是改变他人思想和行动的能力。政治家运用影响力来赢得选举，商人运
  用影响力来兜售商品，推销员运用影响力诱惑你乖乖地把金钱捧上…人们对影
  响力的运用存在于社会的每个角落，当一个要求用不同的方式提出来时，你的
  反应就会不知不觉地从负面抵抗变成积极合作，你为什么会说“是”，这一转
  变中究竟蕴涵着怎样的心理策略？ 《影响力》这本妙趣横生的书可以告诉你。

- [ ] 《非暴力沟通》  [美]马歇尔·卢森堡

  良言一句三冬暖，恶语伤人二月寒。不正确的沟通方式不仅会导致对他人的伤
  害，也会导致无法进行有效的沟通。卢森堡博士在本书中揭示了那些长久被人
  忽视的沟通障碍，并总结了和谐有效的沟通方式。无论是同学之间、恋人之间、
  师生之间、同事之间，非暴力沟通方式都能帮助你进行有效的沟通。本书的内
  容非常易懂和实用，穿插出现的沟通练习帮助你随时演练书中的沟通原则，对
  于困扰于沟通的同学们，本书是不可不读的好书。

- [ ] 经济

  作者：[美] N.格里高利·曼昆
  曼昆的《经济学原理》是世界上最流行的经济学教材。现代社会中经济与每个人的生活都密切相关，所有的大学生都该懂点经济学，而这本书无疑是最受欢迎的经济学入门经典。

- [ ] 《国富论》  [英]亚当·斯密

  《国富论》被誉为西方经济学的"圣经"，经济学的百科全书，影响世界历史的
  十大著作本书之一，影响人类文化的100本书之一。这部著作是现代经济学的
  开山之作，后来的经济学家基本是沿着他的方法分析经济发展规律的，这部著
  作也奠定了资本主义自由经济的理论基础，第一次提出了市场经济会由“看不
  见的手”自行调节的理论。

- [ ] 《怪诞行为学》  [美]丹·艾瑞里

  这是一本有趣的书，本书告诉你，你的非理性冲动都是有经济学支撑的！ 丹·
  艾瑞里用轻松幽默的语言揭示了我们不可思议的行为背后的原因。如果你是一
  个冲动消费的同学，希望了解为什么自己会那么做，你该看看这本书，它会解
  开你的谜团。本书没有任何门槛，没有经济学专业知识的同学也可以从中收获
  甚多。

- [ ] 《牛奶可乐经济学》  [美]罗伯特·弗兰克

  为什么牛奶装在方盒子里卖，可乐却装在圆瓶子里卖？为什么很多酒吧喝水要
  钱，却又提供免费花生米？这不是一部让人读得头疼的教科书，而是一部点滴
  生活小智慧合集。作者擅长用经济学方法将生活中的故事娓娓道来，这是一部
  没有阅读门槛、却能从中获得生活智慧的另类经济学书籍。

- [ ] 《Facebook效应》  [美]大卫·柯克帕特里克

  本书叙述了Facebook如何从哈佛的宿舍里萌发，创始人的内讧，权力之争，如
  何放弃华盛顿邮报的投资，怎样争取到第一个广告客户，而第一轮融资又如何
  获得一亿美元的估值……作者近距离地采访了与Facebook相关的人士，其中包
  括Facebook的创始人、员工、投资人、意向投资人以及合作伙伴，加起来超过
  了130人。这是真切详实的访谈，更是超级精彩的故事。Facebook作为一个传
  奇企业，值得所有希望了解互联网和新媒体的同学深入了解。

- [ ] 《大败局》  吴晓波

  这本书展示了国内著名企业的失败之路。这是一个令人激动的年代，无数的机
  会令人心动，一个伟大品派往往在一瞬间便打造而成；这也是一个冒险的年代，
  未知的风险又令每一个人不寒而畏，成功者往往在一瞬间灰飞烟灭。这本书与
  《激荡三十年》一样，是了解中国市场所不可不读的书。

- [ ] 《激荡三十年》  吴晓波

  本书记载了1978-2008年间中国的企业变革，作者没有用传统的教科书或历史
  书的方式来写作这部作品，而是站在民间的角度，以真切而激扬的写作手法描
  绘了中国企业在改革开放年代走向市场、走向世界的成长、发展之路。

- [ ] 《策略思维》  迪克西特 /奈尔伯夫

  耶鲁大学教授奈尔伯夫和普林斯顿大学教授迪克西特的这本著作，用许多活生
  生的例子，向没有经济学基础的读者展示了博弈论策略思维的道理。人生是一
  个永不停息的决策过程。从事什么样的工作，怎样打理一宗生意，该和谁结婚，
  怎样将孩子抚养成人，要不要竞争总裁的位置，都是这类决策的例子。这本书
  不仅适合对博弈论感兴趣的同学，也同样适合所有希望让生活决策更有条理的
  同学。

- [ ] 《无价》  [美]威廉·庞德斯通

  为什么免费的巧克力让我们疯狂？为什么百老汇剧场里价格越高的位置卖得越
  火？为什么100万美元带来的愉悦感，400万美元才能让它翻倍？为什么议价时，
  一定要抢先报价，而且一定要狮子大开口？威廉·庞德斯通告诉我们答案：价
  格只是一场集体幻觉。如果你想了解价格的奥秘，就来读这本书吧！

- [ ] 《欢乐的经济学》  戴维·亨德森

  这是一本通过对作者亲身经历进行生动有趣的分析，向读者普及经济学思维、
  传达自由至上理念的书。本书的作者是一名专业经济学家，致力于传播自由经
  济与市场经济的理念。

- [ ] 《长尾理论》  [美]克里斯·安德森

  本书讲述了互联网时代如何改变了长尾的经济价值。 本书中阐述，商业和文
  化的未来不在于传统需求曲线上那个代表“畅销商品”（hits）的头部； 而
  是那条代表“冷门商品”（misses）经常为人遗忘的长尾。 比如，亚马逊网
  络书店的销售额有四分之一来自于排名10万之后的书籍。本书适合所有希望了
  解产品与市场的同学阅读。

- [ ] 《惠普之道》  [美]戴维·帕卡德

  《惠普之道》是惠普公司创始人戴维·帕卡德所写的创立惠普公司的故事，本
  书文笔通俗简练，前半部分叙述惠普公司的创业经历，后半部分阐释惠普公司
  的价值观、宗旨与做法。惠普公司是硅谷的纪念碑和常春藤，惠普公司以其健
  康的绩效、良好的企业环境得到了长足的发展。本书阐释的“惠普之道”被许
  多卓越的企业所效仿，本书是所有对创业和企业管理感兴趣的同学的必读书。

- [ ] 《定位》  [美]艾·里斯/杰克·特劳特

  20多年前，美国《广告时代》杂志约请年轻的营销专家里斯和特劳特撰写一系
  列有关营销和广告新思维的文章，总标题就是“定位的时代”。系列文章刊载
  之后，引起全行业的轰动，定位成了营销界人人谈论的热闹话题，经作者之手
  送出的文章就达12万份之多，由此开创了营销理论全面创新的时代。20年过去，
  定位思想已经深入人心，成为营销中必须考虑的要素。本书适合所有对商业感
  兴趣的同学阅读。

- [ ] 《通往奴役之路》  [英]弗里德利希・冯・哈耶克

  这是一本古典自由主义经济学的经典名著，在哈耶克的学术生涯中占有重要的
  地位。哈耶克在这本书中论证道，当时正在计划中的福利国家不是为个人自由
  的战斗在和平时期的继续，倒是朝着专制的方向迈出了一步。因此，他认为追
  求计划经济，其无意识后果必然是极权主义。本书适合对政治经济学感兴趣的
  同学阅读。

*** 诗歌
- [ ] 《雪国》  [日]川端康成

  年轻的少年在多雪的岛国与两个女子，发生了平淡的故事，然而川端康成笔下
  唯美的情景与诗意的语言，让这本书打动无数人心灵。空灵境界，遥远人物，
  哀伤故事，是川端康成的永恒主题。《雪国》中东方式的虚无充满了日本古典
  文学传统，而人物的描绘又带给人强烈的真实感。

- [ ] 《人间词话》  王国维

  清末文史学和考证学的大师王国维先生留给了我们的《人间词话》是晚清以来
  最有影响的著作之一。这是一部接受了西洋美学思想之洗礼后，以崭新的眼光
  对中国旧文学所作的文学批评著作，在旧日诗词论著中，称得上一部屈指可数
  的作品。在以往词论界里，许多人把它奉为圭臬，把它的论点作为词学、美学
  的根据，影响很是深远。

*** 其它

- [ ] 《生命是什么》  埃尔温·薛定谔

  理工科学生大概都对薛定谔耳熟能详，这位诺贝尔奖获得者撰写的《生命是什
  么》更是一本伟大的科学人文经典。这本书专为生命科学的门外汉书写，内容
  通俗易懂，历史证明这本书成为了推动分子生物学诞生的激励者和推动者。本
  书适合于任何希望增进科学素养的同学阅读。

- [ ] 《如何阅读一本书》  [美]莫提默·艾德勒/查尔斯·范多

  你会阅读吗？莫提默·艾德勒告诉你，阅读并非那么简单。不懂阅读的人，初
  探阅读的人，读这本书可以少走冤枉路。对阅读有所体会的人，读这本书可以
  有更深的印证和领悟。本书介绍了阅读的三个层次，对每个层次都进行了细致
  的指导，是一本非常实用的读书用手册。

- [ ] 《人月神话》  [美]弗雷德里克·布鲁克斯

  本书是软件工程领域的名著，为人们管理复杂项目提供了颇具洞察力的见解，
  既有很多发人深省的观点，也有大量的软件工程实践。如果你有志从事技术领
  域的管理工作，或者面临领导团队的工作，本书是你的必读之书。

- [ ] 《西方美学史》  朱光潜

  一部美学史并不单一的只是纯粹美学理论的历史，而且还是人类心灵自我展现
  的历史，或者说，在那些看似抽象的理论背后，我们所感受到的乃是各个时代
  人类精神脉博的跳动，这是一种精神的还乡历程——请跟随朱光潜先生来一次西
  方美学的精神漫游吧。

- [ ] 《目送》  龙应台

  《目送》共由七十四篇散文组成，是为一本极具亲情、感人至深的文集。由父
  亲的逝世、母亲的苍老、儿子的离开、朋友的牵挂、兄弟的携手共行，写出失
  败和脆弱、失落和放手，写出缠绵不舍和绝然的虚无。作者平淡朴实的文笔、
  真诚深挚的情感和传统现代的思考，都让人感觉身心放松、恍若相通，值得一
  读。

- [ ] 《黑客与画家》  [美] Paul Graham

  本书是硅谷创业之父Paul Graham的文集，主要介绍优秀程序员的爱好和动机，
  讨论他们的成长、对世界的贡献以及编程语言和工作方法等所有对计算机时代
  感兴趣的人的一些话题。书中的内容不但有助于了解计算机编程的本质、互联
  网行业的规则，还会帮助读者了解我们这个时代，迫使读者独立思考。本书适
  合所有互联网创业者和计算机相关专业的学生，也适合一切对计算机行业感兴
  趣的读者。

- [ ] 《性趣探秘》  戴蒙德

  这不是一本房中术秘籍，这是一本严肃书籍。《性趣探秘》力图解释人类的性
  行为是如何演变为现在的模式，包括女性的绝经期、人类社会中男性的角色、
  离群性交、为取乐的性交，以及女性乳房早于发挥喂乳功用时的隆起等。一些
  我们看来再自然不过、再平常不过的事情中，隐藏着生物进化的奥秘。本书语
  言平实，适合对生物进化论感兴趣的同学阅读。

- [ ] 《枪炮、病菌与钢铁》  [美]贾雷德・戴蒙德

  《枪炮、病菌与钢铁》是一本关于生物演化的书，它是理解人类社会的一个重
  大进展，它记录了现代世界及其诸多不平等所以形成的原因。这是关于如何理
  解人类繁衍、扩张、发现、侵略的历史的一本书，内容恢弘大气，历史感强烈。
  该书于1998年获得普利策奖以及英国科普书奖。适合任何希望增进科学素养的
  同学阅读。

** Kindle 剪切板

# Kindle剪切板保存有许多冗余的信息，我也不知道是不是会需要，也许吧，先保
# 留着。

*** 2015/10/11--2016/02/09

Of Human Bondage (W. Somerset Maugham; Maeve Binchy; Benjamin Demott)
- 您在位置 #142-143的标注 | 添加于 2015年10月11日星期日 上午7:31:59

In general—no rules without exceptions—autobiographical novels produced by authors at an early age have the strength of intensity and the weakness of self-absorption, while those produced in mid-life lose passion and gain objectivity.
==========
﻿Of Human Bondage (W. Somerset Maugham; Maeve Binchy; Benjamin Demott)
- 您在位置 #153 的笔记 | 添加于 2015年10月11日星期日 上午7:40:09

自我关注
==========
﻿Of Human Bondage (W. Somerset Maugham; Maeve Binchy; Benjamin Demott)
- 您在位置 #153-153的标注 | 添加于 2015年10月11日星期日 上午7:40:09

self-preoccupation
==========
﻿Of Human Bondage (W. Somerset Maugham; Maeve Binchy; Benjamin Demott)
- 您在位置 #169-169的标注 | 添加于 2015年10月11日星期日 上午7:46:24

feeling can be tinged with self-pity and still not deserve contempt.
==========
﻿1Q84 (村上春树)
- 您在位置 #213-215的标注 | 添加于 2015年10月13日星期二 上午8:56:32

我是谁，接下来要去什麼地方做什麼？你们一定想像不到。青豆嘴唇不动地这样说。你们被绑在那裡动弹不得，哪裡也去不了。既无法前进，也无法后退。但我不一样。我有不能不去做的工作。不能不完成的使命。所以我先走一步了。
==========
Of Human Bondage (W. Somerset Maugham; Maeve Binchy; Benjamin Demott)
- 您在位置 #787-789的标注 | 添加于 2015年11月4日星期三 上午8:06:25

Insensibly he formed the most delightful habit in the world, the habit of reading: he did not know that thus he was providing himself with a refuge from all the distress of life; he did not know either that he was creating for himself an unreal world which would make the real world of every day a source of bitter disappointment.
==========
目录 (Unknown)
- 您在位置 #318-319的标注 | 添加于 2015年12月1日星期二 下午3:17:28

此处所讲的“无为”不是无所作为，随心所欲，而是要以辩证法的原则指导人们的社会生活，帮助人们寻找顺应自然、遵循事物客观发展的规律
==========
目录 (Unknown)
- 您在位置 #325-325的标注 | 添加于 2015年12月1日星期二 下午3:18:23

“相反相成
==========
目录 (Unknown)
- 您在位置 #331-332的标注 | 添加于 2015年12月1日星期二 下午3:19:10

朴素的辩证法，是老子哲学中最有价值的部
==========
目录 (Unknown)
- 您在位置 #384-385的标注 | 添加于 2015年12月1日星期二 下午3:25:06

他既不讲人性善，也不讲人性恶，而是说人性本来是纯洁素朴的，犹如一张白纸。如
==========
目录 (Unknown)
- 您在位置 #742-743的标注 | 添加于 2015年12月1日星期二 下午5:59:02

为腹不为目：只求温饱安宁，而不为纵情声色之娱。"腹"在这里代表一种简朴宁静的生活方式；"目"代表一种巧伪多欲的生活方式。
==========
目录 (Unknown)
- 您在位置 #906-907的标注 | 添加于 2015年12月7日星期一 上午12:44:55

日出而作，日入而息。凿井而饮，耕田而食。帝力于我何有哉？
==========
目录 (Unknown)
- 您在位置 #1544-1545的标注 | 添加于 2015年12月15日星期二 下午9:24:28

上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。不笑不足以为道。
==========
目录 (Unknown)
- 您在位置 #1571-1572的标注 | 添加于 2015年12月15日星期二 下午9:27:16

道生一①，一生二②，二生三③，三生万物。万物负阴而抱阳④，冲气以为和⑤。
==========
目录 (Unknown)
- 您在位置 #1661-1661的标注 | 添加于 2015年12月15日星期二 下午9:34:33

祸莫大于不知足；咎莫大于欲得。
==========
目录 (Unknown)
- 您在位置 #2009-2009的标注 | 添加于 2015年12月15日星期二 下午9:55:30

祸兮，福之所倚；福兮，祸之所伏。
==========
目录 (Unknown)
- 您在位置 #2147-2147的标注 | 添加于 2015年12月15日星期二 下午10:05:33

图难于其易，为大于其细；天下难事，必作于易；天下大事，必作于细
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #25-29的标注 | 添加于 2015年12月22日星期二 下午7:32:19

《诗经》共三百零五首，简称“诗三百”。按其内容，可分为“风”、“雅”、“颂”三类。“风”乃风土之曲，即民间歌谣，共一百六十篇，总称为十五国风。“雅”乃朝廷之乐，多为京都一带朝廷官吏的作品，共一百零五篇，分为《大雅》和《小雅》。“颂”乃庙堂之音，是王侯举行祭祀或其他重大典礼专用的乐歌，共四十篇，分为《周颂》、《鲁颂》、《商颂》，合称三颂。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #33-34的标注 | 添加于 2015年12月22日星期二 下午7:33:03

。读《诗经》，重在读、贵在读、趣在读。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #50-53的标注 | 添加于 2015年12月22日星期二 下午7:35:35

关关雎鸠，在河之洲。窈窕淑女，君子好逑。 参差荇菜，左右流之。窈窕淑女，寤寐求之。 求之不得，寤寐思服。悠哉悠哉，辗转反侧。 参差荇菜，左右采之。窈窕淑女，琴瑟友之。 参差荇菜，左右芼之。窈窕淑女，钟鼓乐之。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #150-151的标注 | 添加于 2015年12月22日星期二 下午7:53:04

桃之夭夭，灼灼其华。之子于归，宜其室家。 桃之夭夭，有蕡有实。之子于归，宜其家室。 桃之夭夭，其叶蓁蓁。之子于归，宜其家人。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #395-396的标注 | 添加于 2015年12月22日星期二 下午8:31:54

我心匪石，不可转也。我心匪席，不可卷也。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #501-502的标注 | 添加于 2015年12月22日星期二 下午8:44:32

“死生契阔”，与子成说。执子之手，与子偕老。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #513-514的标注 | 添加于 2015年12月22日星期二 下午8:44:51

契：合。阔：疏。“契阔”在这里是偏义复词，偏用“契”义。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #1147-1149的标注 | 添加于 2015年12月23日星期三 上午11:15:15

投我以木瓜，报之以琼琚。匪报也，永以为好也。 投我以木桃，报之以琼瑶。匪报也，永以为好也。 投我以木李，报之以琼玖。匪报也，永以为好也。
==========
《诗经》全文鉴赏大辞典 (多人)
- 您在位置 #1162-1165的标注 | 添加于 2015年12月23日星期三 上午11:18:50

彼黍离离，彼稷之苗。行迈靡靡，中心摇摇。知我者谓我心忧，不知我者谓我何求。悠悠苍天！此何人哉？ 彼黍离离，彼稷之穗。行迈靡靡，中心如醉。知我者谓我心忧，不知我者谓我何求。悠悠苍天！此何人哉？ 彼黍离离，彼稷之实。行迈靡靡，中心如噎。知我者谓我心忧，不知我者谓我何求。悠悠苍天！此何人哉？
==========
爱的饥渴 (COAY.com)
- 您在位置 #17-18的标注 | 添加于 2015年12月23日星期三 下午8:40:39

其实，悦子害怕的，也许不是城市，而仅仅是生活本身？
==========
爱的饥渴 (COAY.com)
- 您在位置 #18-19的标注 | 添加于 2015年12月23日星期三 下午8:40:46

生活—是无边无际的、浮满各种漂流物的、变化无常的、暴力的，但总是一片澄澈而湛蓝的海。
==========
英儿 (顾城; 雷米)
- 您在位置 #63-65的标注 | 添加于 2015年12月25日星期五 上午1:10:52

我是理性主义者，但我也相信生活是由某种我们所无法把握的阴差阳错构成的。所以，一件事情如果没有理所当然以外的诧异，那就会失去真实的感觉。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #4-4的标注 | 添加于 2015年12月26日星期六 上午2:21:26

幸福的家庭都是相似的，不幸的家庭各有各的不幸。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #45-46的标注 | 添加于 2015年12月26日星期六 上午2:25:21

斯捷潘·阿尔卡季奇是一个忠实于自己的人。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #526-528的标注 | 添加于 2016年1月2日星期六 上午1:49:33

她的衣服和姿态看上去都没有什么特别引人注目的地方，但是列文在人群中找出她来，就好像在荨麻里找到蔷薇一样地容易。由于她，万物生辉。她是照耀周遭一切的微笑。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #561-562的标注 | 添加于 2016年1月2日星期六 上午1:52:57

因为现在我是幸福的，至少在希望上是幸福的……而以后呢？……但是我一定要，我一定要，懦弱滚开吧！”
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #716-718的标注 | 添加于 2016年1月3日星期日 上午12:38:06

。他深知列文的那种感情，在他看来，世界上的少女应当分成两类：有一类——她以外的全世界的少女，那些有着所有人类缺点的少女，最普遍的少女；另外一类——她一个人，丝毫弱点都没有，而且超出全人类。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #810-813的标注 | 添加于 2016年1月3日星期日 上午12:45:30

你是始终如一的。这是你的优点，也是你的缺陷。你有始终如一的性格，你要整个生活也是始终如一的——但事实决不是这样。你轻视公务，因为你希望工作永远和目的完全相符——而事实决不是这样。你还要每个人的活动都有明确的目的，恋爱和家庭生活始终是统一的——而事实决不是这样。人生的一切变化，一切魅力，一切美都是由光和影构成的
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #957-959的标注 | 添加于 2016年1月4日星期一 上午12:20:37

有些人，无论在什么事情上面，遇到成功的敌手的时候，马上就不睬他的一切优点，只看到缺点。反之，也有些人，他们顶希望在幸运的敌手身上找出胜过自己的特点，带着剧烈的创痛专门寻找长处。列文属于第二种人。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #1080-1082的标注 | 添加于 2016年1月4日星期一 上午12:30:39

他不晓得他对基蒂的这种行为有一个特定的名称，那就是向少女调情而又无意和她结婚，这种调情是像他那样风度翩翩的公子所共有的恶行之一。他以为他是第一个发现这种快乐的，他正在尽情享受着他的发现。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #1607-1609的标注 | 添加于 2016年1月12日星期二 下午10:44:55

，我不能埋怨谁，也没有什么好埋怨的。都是我自己不好。我有什么权利以为她愿意和我结成终身伴侣呢？就是什么人，我算个什么？是一个谁都不需要、对于谁都没有用处的一无可取的人呀。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #1773-1775的标注 | 添加于 2016年1月14日星期四 上午12:45:37

他感到自在起来，不再作分外之想了。他现在唯一希望的就是要变得比从前更好一些。第一，他下决心从此不再希望结婚能给予他罕有的幸福，因此也不再那么轻视他现有的东西。第二，他再也不让自己沉溺于卑劣的情欲中，在他决心求婚的时候，回想起过去的情欲曾经使他那么苦恼
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #1790-1792的标注 | 添加于 2016年1月14日星期四 上午12:47:41

不，你不会离开我们，你不会变成另外的样子，你还会和从前一样的：老是怀疑，永远不满意自己，徒劳无益地妄想改革，结果总是失败，永远憧憬着你不会得到、而且不可能得到的幸福。”
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #2428-2431的标注 | 添加于 2016年2月2日星期二 上午10:00:19

他十分明白他在贝特西或任何其他社交界人们的眼里并没有成为笑柄的危险。他十分明白在他们心目中做一个少女或任何未婚女性的单恋者的角色也许是可笑的；但是一个男子追求一个已婚的妇人，而且，不顾一切，冒着生命危险要把她勾引到手，这个男子的角色就颇有几分优美和伟大的气概，而决不会是可笑的；
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #2704-2704的标注 | 添加于 2016年2月2日星期二 上午10:33:10

这在他看来是非常荒谬和不可思议的，因为这就是生活本身
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #2705-2707的标注 | 添加于 2016年2月2日星期二 上午10:34:11

而每一次他与现实发生冲突的时候，他就逃避现实。现在他体验到这样一种心情，仿佛一个人泰然自若地走过深渊上的桥梁的时候，突然发觉桥断了，下面是无底深渊
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #5054-5055的标注 | 添加于 2016年2月2日星期二 下午9:29:52

。伪善不论在什么事情上也许可以欺骗最聪明最机灵的大人，但是最不灵敏的小孩也能识破伪善，对它抱着恶感，不管它掩饰得多么巧妙。列
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #5221-5226的标注 | 添加于 2016年2月2日星期二 下午9:46:40

他自言自语，极力想替自己把他在这短短的一夜里体会到的一切思想感情表达出来。他所体会到的一切思想感情分成了三个不同的思路。一个是抛弃自己过去的生活，抛弃自己的完全无用的学识和教育。这种抛弃会给与他快乐，而且对他说来是简单容易的。另一类的思想和想像是有关他现在所渴望过的生活的。他明晰地感觉到这种生活的单纯、纯洁和正当，而且深信他会在这种生活中寻找到他所痛感缺乏的满足、平静和高尚品德。但是第三类的思想却围绕着怎样使旧生活转变成新生活的问题。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #5234-5234的标注 | 添加于 2016年2月2日星期二 下午9:49:03

在光明完全战胜黑暗的黎明将要来临之前，通常总有一个幽暗的顷刻。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #5243-5245的标注 | 添加于 2016年2月2日星期二 下午9:50:33

。这就是基蒂。他明白了她正从火车站坐车到叶尔古绍沃去。在那不眠的一夜里使列文激动不安的一切事情，他所下的一切决心，全都一下子烟消云散
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #5883-5883的标注 | 添加于 2016年2月3日星期三 下午12:40:49

，只要了解了你所爱的妻子，你就会比认识一千个女人的人更了解所有的女人。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #7462-7462的标注 | 添加于 2016年2月3日星期三 下午8:44:21

人们争论得那么热烈，往往只是因为不能领会对方所要证明的事情。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #7461-7461的标注 | 添加于 2016年2月3日星期三 下午8:44:27

他们为什么要辩论呢？您知道从来没有人能够说服谁。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #7564-7564的标注 | 添加于 2016年2月3日星期三 下午8:54:08

结婚中的重要因素就是爱情，有了爱情，人总是幸福的，因为幸福全在自己身上。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #7657-7658的标注 | 添加于 2016年2月3日星期三 下午9:00:52

我多么清楚会这样啊！我从来不敢这样希望；可是在我心里我却总是深信不疑的，
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #7714-7714的标注 | 添加于 2016年2月3日星期三 下午9:34:03

凡上帝要毁灭者，先使其疯狂
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #8139-8140的标注 | 添加于 2016年2月3日星期三 下午10:25:44

有人打你的右脸，连左脸也由他打；有人夺你的上衣，连衬衣也给他
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #8996-9000的标注 | 添加于 2016年2月4日星期四 下午4:59:55

他是幸福的，但是进入家庭生活以后，他处处看到这和他所想像的完全不同。他处处感到这样一种心情，如同一个人叹赏湖上一叶小舟平稳而幸福地漂浮，等到自己坐上小舟的时候心情就有些两样。他发现：这并不只是平稳地坐着，毫不摇晃，人还得要思想，片刻不能忘记他要到什么地方去；而且下面还有水，人还得划桨；他的不习惯划桨的手还会疼痛；只是看着容易，可是做起来的时候，虽说是非常愉快，却也是很不容易啊。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #9000-9005的标注 | 添加于 2016年2月4日星期四 下午5:00:49

独身的时候，他看见别人的婚后生活，看到他们的琐屑的忧虑、争吵、嫉妒的时候，他往往只是在心里轻蔑地讥笑。在他未来的夫妻生活中，他相信决不会有这种事情；就连他的结婚生活的外表形式，在他想来，也准会和别人的生活完全不同。可是出乎意外，他和他妻子的生活不但没有独树一格，而且，恰好相反，完全是由他以前那么轻视的极其琐碎的小事构成的，而现在，那些小事，违反他的意愿，却具有了异乎寻常的、无可争辩的重要性。列文看到要把所有这些琐事安顿好，完全不像他以前想像的那么容易。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #9163-9165的标注 | 添加于 2016年2月4日星期四 下午5:15:12

他开始说话，竭力找话来与其说是说服她，不如说是安慰她。但是她不听他，随便他说什么也不理睬。他弯下腰，拉住她那只在抗拒他的手。他吻她的手，吻她的头发，又吻她的手——她却始终沉默着。但是当他用两手捧着她的脸，叫了声“基蒂！”的时候，她突然恢复了镇静，哭了一会，于是他们就和好了
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #9332-9332的标注 | 添加于 2016年2月4日星期四 下午5:34:27

一切事情都难料呢，
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #13874-13876的标注 | 添加于 2016年2月5日星期五 下午5:04:50

一个家庭要采取任何行动之前，夫妻之间要么是完全破裂，要么是情投意合才行。当夫妇之间的关系不确定，既不这样，又不那样的时候，他们就不可能采取任何行动了。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #14768-14769的标注 | 添加于 2016年2月5日星期五 下午6:44:17

他还模糊地意识到他所谓的那种信念不但是无知，而且还是那么一种思想方法，靠这种思想方法要取得他所需要的知识是不可能的。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #14827-14829的标注 | 添加于 2016年2月5日星期五 下午6:49:35

当列文想到他是什么和为什么活着的时候，他找不到答案，于是陷入悲观失望；但是当他不再问自己这些问题的时候，他反倒好像知道他是什么和为什么活着了，因为他坚决而明确地生活着和行动着；最近他甚至比以前更坚定明确得多了。
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #14863-14866的标注 | 添加于 2016年2月5日星期五 下午6:53:22

推究把他引入了疑惑之中，妨碍他看清他该做什么，不该做什么。但是当他不动脑筋，只是这么活着的时候，他就不住地感觉到他的心灵里有一个绝对正确的审判官，在评判那可能发生的两种行动，哪样好，哪样歹；而他刚一做了不该做的事，他立刻就感觉到了
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #15340-15343的标注 | 添加于 2016年2月5日星期五 下午7:30:46

这种新的情感并没有使我有所改变，没有使我感到幸福，也没有像我梦想的那样突然间使我大彻大悟，只是像我对我儿子的感情一样。这也没有什么出人意外的地方。但就是信仰也罢，不是信仰也罢——我不知道这到底是什么呢，——这种情感不知不觉地历尽痛苦产生了，在我心中牢固地扎下根来
==========
安娜·卡列尼娜 (列夫·托尔斯泰)
- 您在位置 #15343-15347的标注 | 添加于 2016年2月5日星期五 下午7:31:18

我照样还会跟车夫伊万发脾气，照样还会和人争论，照样还会不合时宜地发表自己的意见；在我心灵最神圣的地方和其他的人们，甚至和我的妻子之间仍然会有隔阂；为了我自己的恐惧我还会责备她，并且还会因此感到后悔；我的理智仍然不可能理解我为什么祈祷，但是我照样还会祈祷；但是现在我的生活，我的整个生活，不管什么事情临到我的身上，随时随刻，不但再也不会像从前那样没有意义，而且具有一种不可争辩的善的意义，而我是有权力把这种意义贯注到我的生活中去的！”
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #26-27的标注 | 添加于 2016年2月6日星期六 下午1:34:13

爱情不是一种与人的成熟程度无关，只需要投入身心的感情
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #75-76的标注 | 添加于 2016年2月6日星期六 下午1:35:49

如果爱是一门艺术，那就要求人们有这方面的知识并付出努力。或
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #103-105的标注 | 添加于 2016年2月6日星期六 下午1:38:58

在一个商业化占统治地位以及把物质成功看得高于一切的文化中，事实上是没有理由对下列事实抱有吃惊的态度：人与人之间的爱情关系也遵循同控制商品和劳动力市场一样的基本原则。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #87-88的标注 | 添加于 2016年2月6日星期六 下午1:39:30

产生在爱这件事上一无可学这一看法的第二个原因是人们认为爱的问题是一个对象问题，而不是能力问题。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #79-81的标注 | 添加于 2016年2月6日星期六 下午1:40:11

但他们之中没有人认为，人们本可以学会去爱。 　　他们之所以持有这种特殊态度是有其各种原因的，这些原因反过来又分别地或总和地加强了他们的这一态度。大多数人认为爱情首先是自己能否被人爱，而不是自己有没有能力爱的问题
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #105-107的标注 | 添加于 2016年2月6日星期六 下午1:40:37

产生在爱情这件事上一无可学这一看法的第三个错误是人们不了解“堕入情网”同“持久的爱”这两者的区别。如果我们用falling in love和being in love这两个英文搭配也许就能更清楚地区分这两个概念。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #118-120的标注 | 添加于 2016年2月6日星期六 下午1:42:03

要认识爱情是一门艺术。人们要学会爱情，就得像学其他的艺术——如音乐，绘画，木工或者医疗艺术和技术一样的行动。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #123-124的标注 | 添加于 2016年2月6日星期六 下午1:43:00

，除了学习理论和实践外还有第三个必不可少的因素，即要把成为大师看得高于一切，这一目标必须占据他整个身心。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #135-136的标注 | 添加于 2016年2月6日星期六 下午1:44:23

人的存在的根本要点是人超越了动物界，超越了本能的适应性，脱离了自然——尽管人永远不可能完全脱离自然。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #158-159的标注 | 添加于 2016年2月6日星期六 下午1:48:32

人——所有时代和生活在不同文化之中的人——永远面临同一个问题，即：如何克服这种孤独感，如何超越个人的天地，实现人类的大同。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #183-186的标注 | 添加于 2016年2月6日星期六 下午1:51:09

在某种程度上性纵欲是克服孤独感的一种自然和正常的方式，并有部分效果。许多不能用其他的方式减轻孤独感的人很重视性纵欲的要求，实际上这和酗酒和吸毒并无多大区别。有些人拼命地想借性纵欲使自己克服由于孤独而产生的恐惧感，但其结果只能是越来越孤独，因为没有爱情的性交只能在一刹那间填补两个人之间的沟壑。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #275-277的标注 | 添加于 2016年2月6日星期六 下午2:02:07

同共生有机体结合相对立的是成熟的爱情，那就是在保留自己完整性和独立性的条件下，也就是保持自己个性的条件下与他人合二为一。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #277-278的标注 | 添加于 2016年2月6日星期六 下午2:02:22

爱情可以使人克服孤寂和与世隔绝感，但同时又使人保持对自己的忠诚，保持自己的完整性和本来的面貌。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #290-291的标注 | 添加于 2016年2月6日星期六 下午2:04:24

。如果一个人是在积极的情绪支配下行动，他就是自由的，是情绪的主人。如果他是被一种消极的情绪所支配，那他就是受外力驱使者，是他自己都不了解的动机的对象
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #294-295的标注 | 添加于 2016年2月6日星期六 下午2:04:57

爱情是一种积极的，而不是消极的情绪。一般来说可以用另一个说法来表达，即爱情首先是给而不是得。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #332-334的标注 | 添加于 2016年2月6日星期六 下午2:11:10

有没有能力把爱情作为一种给的行为取决于人的性格发展，这一事实似乎没有必要加以强调了。取得这一能力的先决条件是人要有一种占主导地位的生产性倾向
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #338-339的标注 | 添加于 2016年2月6日星期六 下午2:11:51

爱情的积极性除了有给的要素外，还有一些其他的基本要素。这些要素是所有爱的形式共有的，那就是：关心、责任心、尊重和了解。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #342-343的标注 | 添加于 2016年2月6日星期六 下午2:12:35

爱情是对生命以及我们所爱之物生长的积极的关心。如果缺乏这种积极的关心，那么这只是一种情绪，而不是爱情。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #352-352的标注 | 添加于 2016年2月6日星期六 下午2:14:38

，爱的本质是创造和培养，爱情和劳动是不可分割的。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #353-355的标注 | 添加于 2016年2月6日星期六 下午2:15:39

关心和关怀还包括爱情的另一方面，即责任心。今天人们常常把责任心理解为是义务，是外部强加的东西。但是责任心这个词的本来意义是一件完全自觉的行动，是我对另一个生命表达出来或尚未表达出来的愿望的答复。“有责任”意味着有能力并准备对这些愿望给予回答
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #359-360的标注 | 添加于 2016年2月6日星期六 下午2:16:05

如果爱情没有第三个要素：尊重，那责任心就很容易变成控制别人和奴役别人
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #360-361的标注 | 添加于 2016年2月6日星期六 下午2:16:55

。尊重这个词的出处就是有能力实事求是地正视对方和认识他独有的个性。尊重就是要努力地使对方能成长和发展自己，因此尊重决无剥削之意。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #363-365的标注 | 添加于 2016年2月6日星期六 下午2:17:43

只有当我自己达到独立，在没有外援的情况下独立地走自己的路，即不想去控制和利用别人，只有在这种情况下，尊重对方才成为可能。只有在自由的基础上才会有 　　爱情，
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #366-368的标注 | 添加于 2016年2月6日星期六 下午2:17:57

人们只有认识对方，了解对方才能尊重对方。如果不以了解为基础，关心和责任心都会是盲目的，而如果不是从关怀的角度出发去了解对方，这种了解也是无益的。了解的方式多种多样。成为爱情一要素的了解是要深入事物
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #368-369的标注 | 添加于 2016年2月6日星期六 下午2:18:19

我只有用他人的眼光看待他人，而把对自己的兴趣退居二位。我才能了解对方
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #407-408的标注 | 添加于 2016年2月6日星期六 下午2:23:29

我们永远不可能靠智力来了解人和宇宙的秘密，但可以通过爱情去把握它。心
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #410-412的标注 | 添加于 2016年2月6日星期六 下午2:23:59

成熟的人只想拥有他自己的劳动果实，放弃了获取全力和全知的自恋幻想，并有一种谦恭的态度。这一态度的基础是他内心的力量，单单这股力量就能使他进行真正的、创造性的劳动。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #495-497的标注 | 添加于 2016年2月6日星期六 下午2:34:48

天真的、孩童式的爱情遵循下列原则：“我爱，因为我被人爱。”成熟的爱的原则是：“我被人爱，因为我爱人。”不成熟的、幼稚的爱是：“我爱你，因为我需要你”，而成熟的爱是：“我需要你，因为我爱你。”
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #548-550的标注 | 添加于 2016年2月6日星期六 下午2:41:06

爱首先不是同一个特殊的人的关系，而更多的是一种态度，性格上的一种倾向。这种态度决定一个人同整个世界，而不是同爱的唯一“对象”的关系。如果一个人只爱他的对象，而对其他的人无动于衷，他的爱就不是爱，而是一种共生有机体的联系或者是一种更高级意义上的自私
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #558-559的标注 | 添加于 2016年2月6日星期六 下午2:46:46

一切爱的形式都以博爱为基矗我指的博爱就是对所有的人都有一种责任感，关心、尊重和了解他人，也就是愿意提高其他人的生活情趣。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #701-702的标注 | 添加于 2016年2月7日星期日 下午3:28:36

利己者眼里只有自己，总是按照对自己是否有利的标准来判断一切人和一切事物，他们原则上没有爱的能力
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #868-868的标注 | 添加于 2016年2月8日星期一 下午4:21:37

悖论逻辑的导师认为人只有在现实的矛盾中才能感觉现实，人永远无法在思想上把握最终实体，把握宇宙。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #983-984的标注 | 添加于 2016年2月8日星期一 下午4:44:10

爱情不是性满足的结果，而是性的幸福，甚至掌握所谓的性技巧也是爱情的结果。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1115-1117的标注 | 添加于 2016年2月8日星期一 下午4:57:14

。这要爱情是一个白日梦，他们就能加入进来，但如果爱情成为两个真实的人之间的一种现实关系——他们就僵化了。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1120-1120的标注 | 添加于 2016年2月8日星期一 下午4:57:53

。现在人不是生活在过去就是生活在未来，但不是现时。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1120-1123的标注 | 添加于 2016年2月8日星期一 下午4:58:24

。现在人不是生活在过去就是生活在未来，但不是现时。他们满怀感伤地回忆童年和母亲——或者为未来制定伟大的计划。不管是通过参与别人的非真正的爱情经历来体验爱情，还是通过吧现时推移到过去和未来的方法来躲避爱情的现实，这些抽象的和异化的爱情形式其作用就和鸦片一样，都是为了减轻现实、人的孤独和与世隔绝所带来的痛苦。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1125-1126的标注 | 添加于 2016年2月8日星期一 下午4:58:55

。有些人对他人的每一个细微错误的反应都十分灵敏，而对自己的问题和弱点却不闻不问，他们永远是在考虑如何指责对方或者教育对方。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1138-1143的标注 | 添加于 2016年2月8日星期一 下午5:00:25

。按“在任何情况下都应避免痛苦和悲伤”的世俗之见，所以现代人也认为，爱情就是意味着没有冲突。他们还以他们所见之争吵都是毁灭性的争论，对双方都没有好处的事实作为理论依据。但是真正的原因在于大多数人的“冲突”实际上都是为了避免真正的冲突。这些冲突只是对一些鸡毛蒜皮的小事产生分歧而已，而这些小事按其本质来看是无法澄清或者无法解决的。但人与人之间的真正冲突——那些不应该被遮掩，也不应该投射到别处的冲突，那些属于人的内在现实并能在人的心灵深处体验到的冲突——绝不是毁灭性的。这些冲突会得到澄清，会带来一种净化，从而是双方能变得更有知识，更坚强。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1144-1147的标注 | 添加于 2016年2月8日星期一 下午5:01:15

爱情只能产生于这样两个人中间，这两个人都从他们生存的圈子里跳出来并互相结合，同时他们每个人都又能脱离自我中心去体验自己。只有这种“中心体验”才是人的现实，才是生活，才是爱情的基础。这样体验到的爱情是不断地挑战，这种爱情不是避风港，而是一种共同的努力、成长和劳动
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1148-1150的标注 | 添加于 2016年2月8日星期一 下午5:02:06

爱情的存在只有一个证明：那就是双方联系的深度和每个所爱之人的活力和生命力。这也是我们所能看到的爱情的唯一成果。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1182-1182的标注 | 添加于 2016年2月8日星期一 下午5:07:03

除了进行实践外，难道可以从纸上了解一些有关实践爱的艺术的问题吗？
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1190-1191的标注 | 添加于 2016年2月8日星期一 下午5:08:45

首先要求有纪律。如果没有纪律，我将会一事无成。如果我是凭一时的“兴致”去行事，这也许会成为使我感到愉快的一种嗜好，但我永远成不了大师
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1198-1199的标注 | 添加于 2016年2月8日星期一 下午5:09:52

集中是掌握艺术的一个必要条件，这一点是无需证明的了。每一个试图学会一门艺术的人都了解这一点
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1204-1205的标注 | 添加于 2016年2月8日星期一 下午5:11:01

第三个因素是耐心。学过艺术的人都值得要达到目的就必须要有耐心。想尽可能快的取得结果的人永远也学不会一门艺术。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1211-1211的标注 | 添加于 2016年2月8日星期一 下午5:11:58

学会一门艺术还有另一个条件那就是对掌握这门艺术要有极大的兴趣
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1214-1215的标注 | 添加于 2016年2月8日星期一 下午5:12:33

在谈及学会一门艺术的一般条件时还必须提及一点，那就是人们从来不是一开始就直接地学会一门艺术，而总是间接地学会这门艺术。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1216-1219的标注 | 添加于 2016年2月8日星期一 下午5:13:07

为了使自己成为一门艺术的大师，必须把一生献给这门艺术。在实践这门艺术时，自己要成为工具并保持一定的状态，以适应需要完成的任务。这一点在实践爱的艺术上就意味着所有想成为大师的人应该把生活的每一个阶段训练纪律、集中和耐心作为实践爱的艺术的开端。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1219-1220的标注 | 添加于 2016年2月8日星期一 下午5:13:59

那么如何训练纪律呢？我们的爷爷辈能更好地回答这一问题。他们会建议我们早起，不要过奢华的生活，要努力工作。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1222-1224的标注 | 添加于 2016年2月8日星期一 下午5:14:08

每天早晨按时起床，按时进行一定的活动，如禅坐、看书、听音乐和散步，不做或者有限度地做一些分散注意力的是如看侦探小说和电影，不暴饮暴食——这些都是明显的基本要求。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1222-1226的标注 | 添加于 2016年2月8日星期一 下午5:14:29

每天早晨按时起床，按时进行一定的活动，如禅坐、看书、听音乐和散步，不做或者有限度地做一些分散注意力的是如看侦探小说和电影，不暴饮暴食——这些都是明显的基本要求。但是最重要的是不要把纪律看作是外部强加的东西，而应该成为自我意志的体现，应该感到这是一种愉快，并且逐渐习惯于一种生活态度，一旦放弃它，便会若有所思
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1227-1228的标注 | 添加于 2016年2月8日星期一 下午5:14:50

，与身心有益的东西必定使人舒适，即使开始的时候需要克服一定的阻力。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1229-1230的标注 | 添加于 2016年2月8日星期一 下午5:15:22

。最重要的步骤是要学会一个人单独呆着，而且不看书，不听广播，不抽烟和不喝酒。有没有集中的能力表现在能不能单独地呆着——而这种能力
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1229-1231的标注 | 添加于 2016年2月8日星期一 下午5:15:47

最重要的步骤是要学会一个人单独呆着，而且不看书，不听广播，不抽烟和不喝酒。有没有集中的能力表现在能不能单独地呆着——而这种能力优势学会爱的一个条件
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1236-1238的标注 | 添加于 2016年2月8日星期一 下午5:16:29

，他在思考工作中遇到的困难或者是考虑今天晚上上哪里去。但是做一些简单的练习就能帮助他集中，譬如：轻松地坐着（即不要懒散，也不要紧张），把眼睛闭上，努力使自己的眼前出现一片白色，并排除一切干扰自己的画面和念头。然后可试着观察自己的呼吸——不要去想它，也不要去影响它，而只是要意思到自己在呼吸
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1240-1242的标注 | 添加于 2016年2月8日星期一 下午5:16:55

。除这些练习外还有学会专心做一切事：专心听音乐、看书、谈话或欣赏图画。如果专心地干，那么干什么就无关紧要了，无论干什么，重要的或者不重要的都会增加一层现实意义，因为干事的人是完全开放的。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1251-1252的标注 | 添加于 2016年2月8日星期一 下午5:18:22

在同别人的关系中要记住首先就意味着要有听别人讲话的能力。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1254-1255的标注 | 添加于 2016年2月8日星期一 下午5:18:47

每一件聚精会神完成的事会使人清醒（尽管干完时候出现能恢复的自然疲劳状态）。而懒懒散散的干事只能使人产生倦意——
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1256-1256的标注 | 添加于 2016年2月8日星期一 下午5:19:00

集中意味着要完全地在现时地生活，而不是赶着这事想那事
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1258-1259的标注 | 添加于 2016年2月8日星期一 下午5:19:34

如果人们不知道学会每一种事都要有一个过程，都应自己给自己施加压力，那就永远不会学会集中
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1260-1261的标注 | 添加于 2016年2月8日星期一 下午5:20:05

有孩子学走路的耐心和集中他会作出多么大的成绩啊！
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1261-1262的标注 | 添加于 2016年2月8日星期一 下午5:20:33

集中还要求另一样东西，那就是对自己要保持清醒
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1270-1275的标注 | 添加于 2016年2月8日星期一 下午5:22:19

我们也可以以同样的方式清醒地面对自己。譬如在感觉到累或者消沉的时候，不应该听之任之和用随时可以捡来的消沉的想法去加剧这种感受，而应该问问自己：到底发生了什么？为什么我那么一蹶不振？同样在我们生气或者迷惑不解的时候，在我们开始想入非非的时候，都应该这样问自己。在所有这种情况下，终于的是要觉察内心的活动，而不是用各种各样的方法去找到为自己辩护的借口。这样我们就此次会听到内心的一种声音，在向我们讲述，为什么会害怕、消沉或者迷惑不解。一般人对自己体内的活动都有一定的警觉性；能感觉到每种变化和甚至能发现几乎感觉不到的疼痛。注意身体的变化是比较容易做到的，因为大多数人都了解自己的健康状态。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1293-1298的标注 | 添加于 2016年2月8日星期一 下午5:36:05

根据我对爱情本质的论述，获得爱的能力的主要条件是克服自恋。自恋倾向是人的一种态度，具有这种态度的人体验到底现实只是内心活动，主要是他们自己的贪婪和恐惧，对他们来说，外部世界的现象本身是不现实的，只有对他们有利或者威胁他们的食物才有意义。同自恋相反的是客观性，客观性就是对人和事物吧友开放的态度，能实事求是地看待事物。这个意义上的客观性就是能从表面深入现象核心的实现主义。同自恋相反，客观性的基础不是与外部世界毫无关系，而是由强烈的联系
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1317-1318的标注 | 添加于 2016年2月8日星期一 下午5:38:17

能进行客观思考的能力就是理智，以理智为基础的感情是谦恭。我们只有摆脱了童年时代妄图得到全知、全能的幻想，才能有客观性和运用自己的理智。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1326-1328的标注 | 添加于 2016年2月9日星期二 上午1:58:08

爱的能力取决于我们本人成熟的程度，以及在我们同世界和同自己的关系中能不能发展一直创造性的倾向。这种脱离自己的过程、诞生和成熟的过程需要另一种品质作为必不可少的条件：那就是信仰。爱情是以信仰为基础的。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1329-1329的标注 | 添加于 2016年2月9日星期二 上午1:59:35

信仰是否同理智和理性的思考对立？
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1330-1334的标注 | 添加于 2016年2月9日星期二 上午2:00:26

我理解的非合理的信仰是指服从一种非理性权威的信仰（信仰一个人或者一种思想）。与此相反，合理的信仰是扎根于自己思想或感情体验的一种坚定的信念。合理的信仰首先不是信仰什么东西，而是一种确认，这种确认是符合建筑在自己真实经历上的坚定的信念。信仰是全部人格的一个性格特点，而不是同某些被看作为对的思想内容有关的东西。合理的信仰牢牢扎根于创造性的智力和情感的积极活动
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1343-1344的标注 | 添加于 2016年2月9日星期二 上午2:02:32

不合理的信仰意味着只相信权威或大多数人的意见，而合理的信仰是产生一种独立的信念，相信自己创造性的观察和思考——尽管大多数人的看法与之不同。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1354-1355的标注 | 添加于 2016年2月9日星期二 上午2:04:29

在爱情方面，就是要把相信自己的爱情并相信这种爱情能唤起别人的爱以及相信这种爱的可靠性看作是爱情的基本条件
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1366-1369的标注 | 添加于 2016年2月9日星期二 上午2:06:16

在一定的条件下，人类有能力建立一个以平等、正义和爱为原则的社会制度。迄今为止人类没有做到这一点，所以就需要有深信人类能做到这一点的信仰。但是同每一种理性的信念一样，这一信仰绝不是相信会出现奇迹；它更多的是以迄今为止的人类历史为基础，以及每个人的内心经历、对理智和爱的体验为基础。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1390-1393的标注 | 添加于 2016年2月9日星期二 上午8:35:44

培养自己的信仰和勇气可以从日常生活的点滴小事做起。第一个步骤就是要认识到在什么时候和什么地方失去信仰，要看穿用来辩护失去信仰的各种借口和要认识到什么地方胆怯了并找了哪些辩解的借口；另外还要认识到每一次的自我欺骗指挥消弱自己，而越来越软弱又会导致新的自我欺骗，如此恶性循环，一直到人没有信仰为止
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1397-1398的标注 | 添加于 2016年2月9日星期二 上午8:36:18

另外一种与实践爱的艺术不可分割的态度是积极的活动。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1399-1400的标注 | 添加于 2016年2月9日星期二 上午8:36:43

爱情是一项积极的活动，如果我爱，我对所爱之人就抱有积极的态度，而且还不限于对他（她）。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1404-1405的标注 | 添加于 2016年2月9日星期二 上午8:38:40

有些人认为可以把自己的生活分为两个部分，这样在爱情的范畴可以有创造性，而在其他的范畴就不需要有创造性，这种想法只是一种幻想。生产力的本质决定了不会有这样的分工
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1409-1411的标注 | 添加于 2016年2月9日星期二 上午8:40:12

如果爱上一种性格特点，那么爱必须不仅仅出现在我们对自己家庭和朋友的关系中，也必然能在同与我们的工作、职业有关的人的关系中找到。在我们对我们家人的爱和对陌生人的爱之间是没有“分工”的。相反，对陌生人的爱是对家人爱的前提。
==========
爱的艺术 (〔美〕弗洛姆)
- 您在位置 #1419-1420的标注 | 添加于 2016年2月9日星期二 上午8:41:12

“己所不欲，勿施于人”的准则被解释为是“要公正地同别人做生意”。
==========

** 最爱
*** 《小王子》

**** 时间

- 1st :: 2013/08/24--2013/08/25

**** 摘录

To forget a friend is sad. Not every one has had a friend. And if I
forget him, I may become like the grown-ups who are no longer
interested in anything but figures...

one loves the sunset, when one is so sad..."

"I know a planet where there is a certain red-faced gentleman. He has
never smelled a flower. He has never looked at a star. He has never
loved any one. He has never done anything in his life but add up
figures. And all day he says over and over, just like you: 'I am busy
with matters of consequence!' And that makes him swell up with
pride. But he is not a man-- he is a mushroom!"

And if I know-- I, myself-- one flower which is unique in

the world, which grows nowhere but on my planet, but which one little
sheep can destroy in a single bite some morning, without even noticing
what he is doing-- Oh! You think that is not important!"

"If some one loves a flower, of which just one single blossom grows in
all the millions and millions of stars, it is enough to make him happy
just to look at the stars. He can say to himself, 'Somewhere, my
flower is there...' But if the sheep eats the flower, in one moment
all his stars will be darkened... And you think that is not
important!"

It is such a secret place, the land of tears.

He had taken seriously words which were without importance, and it
made him very unhappy.

"One never ought to listen to the flowers. One should simply look at
them and breathe their fragrance. Mine perfumed all my planet. But I
did not know how to take pleasure in all her grace. This tale of
claws, which disturbed me so much, should only have filled my heart
with tenderness and pity."

I ought to have judged by deeds and not by words. She cast her
fragrance and her radiance over me. I ought never to have run away
from her... I ought to have guessed all the affection that lay behind
her poor little strategems. Flowers are so inconsistent! But I was too
young to know how to love her..."

But on this last morning all these familiar tasks seemed very precious
to him.

And when he watered the flower for the last time, and prepared to
place her under the shelter of her glass globe, he realised that he
was very close to tears.

"Of course I love you," the flower said to him. "It is my fault that
you have not known it all the while. That is of no importance. But
you-- you have been just as foolish as I. Try to be happy...

"Forget that I am ashamed," the tippler confessed, hanging his
head. "Ashamed of what?" insisted the little prince, who wanted to
help him. "Ashamed of drinking!" The tippler brought his speech to an
end, and shut himself up in an impregnable silence.

When one wishes to play the wit, he sometimes wanders a little from
the truth.

What does that mean-- 'tame'?" "It is an act too often neglected,"
said the fox. It means to establish ties."

To me, you will be unique in all the world. To you, I shall be unique
in all the world..."

"One only understands the things that one tames,"

"It has done me good," said the fox, "because of the color of the
wheat fields."

But in herself alone she is more important than all the hundreds of
you other roses: because it is she that I have watered; because it is
she that I have put under the glass globe; because it is she that I
have sheltered behind the screen; because it is for her that I have
killed the caterpillars (except the two or three that we saved to
become butterflies); because it is she that I have listened to, when
she grumbled, or boasted, or even sometimes when she said
nothing. Because she is my rose.

It is only with the heart that one can see rightly; what is essential
is invisible to the eye."

"It is the time you have wasted for your rose that makes your rose so
important."

You become responsible, forever, for what you have tamed. You are
responsible for your rose..."

"What makes the desert beautiful," said the little prince, "is that
somewhere it hides a well..."

"The house, the stars, the desert-- what gives them their beauty is
something that is invisible!"

"What moves me so deeply, about this little prince who is sleeping
here, is his loyalty to a flower-- the image of a rose that shines
through his whole being like the flame of a lamp, even when he is
asleep..."

"It is just as it is with the flower. If you love a

flower that lives on a star, it is sweet to look at the sky at
night. All the stars are a-bloom with flowers..."

"In one of the stars I shall be living. In one of them I shall be
laughing. And so it will be as if all the stars were laughing, when
you look at the sky at night... you-- only you-- will have stars that
can laugh!"

**** 观感

** 村上春树

*** 《当我跑步时，我谈些什么》

**** 时间

- 1st :: 2013/08/16--2013/08/19

**** 摘录

**** 观感

*** 《挪威的森林》

**** 时间

- 1st :: 2013/08/27--2013/08/28

**** 摘录

**** 观感

*** 《1973年的弹子球》

**** 时间

- 1st :: 2014/11/01

**** 摘录

**** 观感

*** 《寻羊冒险记》

**** 时间

- 1st :: 2014/11/15

**** 摘录

**** 观感

*** 《舞舞舞》

**** 时间

- 1st :: 2014/12/01

**** 摘录

**** 观感

** 海明威

*** 《老人与海》
:PROPERTIES:
:READING:  1
:END:

**** 时间

- 1st :: 2013/08/20--2013/08/23

**** 摘录

**** 观感

*** 《太阳照常升起》
:PROPERTIES:
:READING:  1
:END:


**** 时间

- 1st :: 2014/12/15

**** 摘录

**** 观感

*** 《丧钟为谁而鸣》
:PROPERTIES:
:READING:  1
:END:

**** 时间

- 1st :: 2015/01/05--2015/02/10

**** 摘录

**** 观感

** 王小波

*** 《白银时代》

**** 时间

- 1st :: 2016/02/16--2016/02/16

**** 摘录

文字是用来读，用来听，不是用来看的——要看不如去看小人书

思想、语言、文字，是一体的，假如念起来乱糟糟，意思也不会好——这是最简单
的真理

没有人告诉他们这些，只按名声来理解文学，就会不知道什么是坏，什么是好。

未来的世界是银子的。这就是说，这世界早晚要沦为一片冷冰冰的、稀薄的银色
混沌，你把一片黄铜含在嘴里，或者把一片锡放在嘴里反复咀嚼，会尝到金属辛
辣的味道——这就是混沌的味道。

罗马诗人维吉尔有诗云：下雨天呆在家里，看别人在街上奔走，是很惬意的。

让我猜猜她为什么会这么怕死。如你所知，我最擅长猜谜，但这个谜我没猜出来。
这谜底是：我这么怕死，说明我是活着的。这真是所罗门式的答案！

未来的世界是银子的，在热寂之后，整个宇宙同此凉热，没有差别，沦为一片冷
冰冰的、稀薄的银色混沌，这就是白银时代。

希腊神话里说，白银时代的人蒙神的恩宠，终生不会衰老，也不会为生计所困。
他们没有痛苦，没有忧虑，相貌和心境都像儿童。死掉这后，他们的幽灵还会在
尘世上游荡。

**** 书评

- [[未来的世界是银子的，在热寂之后，整个宇宙同此凉热，没有差别，沦为一
  片冷冰冰的、稀薄的银色混沌，这就是白银时代。][未来的世界是银子的]]
- [[https://app.yinxiang.com/shard/s52/nl/11551545/414e4181-4b0e-4ee2-86c9-51501c0394b7?title=%E9%87%8D%E8%AF%BB%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3%20(%E8%AF%84%E8%AE%BA%3A%20%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3)][重读白银时代]]
- [[https://app.yinxiang.com/shard/s52/nl/11551545/3f2b7128-da79-478b-ae8c-a4e6542181b0?title=%E3%80%8A%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3%E3%80%8B%E8%AF%BB%E5%90%8E%E6%84%9F%20(%E8%AF%84%E8%AE%BA%3A%20%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3)][《白银时代》读后感]]
- [[https://app.yinxiang.com/shard/s52/nl/11551545/384879f5-0b51-4b07-a4a9-65841eb70776?title=%E7%8B%82%E6%AC%A2%E5%B9%B4%E4%BB%A3%EF%BC%8C%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3%20(%E8%AF%84%E8%AE%BA%3A%20%E7%99%BD%E9%93%B6%E6%97%B6%E4%BB%A3)][狂欢年代，白银时代]]

**** 观感

不到两个小时看完了《白银时代》，恕我愚蒙，真的没有看懂故事的内涵，故事
本身也并不十分有趣，刚拿起这本书时根本读不进去。看了书评，才似乎明白了
在讲什么。  2016/02/16

*** 《沉默的大多数》

**** 时间

- 1st :: 2015/08/31

**** 摘录

真正的君子知道，自己的见解受所处环境左右未必是公平的，所以他觉得明辨是
非是难的。

在这个世界上，大多数愚蠢里含有假装和弄假成真的成分。

参差多态乃是幸福的本源--

看过但丁《神曲》的人就会知道，对人来说，刀山、剑树、火海、油锅都不算严
酷，最严酷的是寒冰地狱，把人冻在那里一动都不动。假如一个社会的宗旨就是
反对有趣，那它比寒冰地狱又有不如。

一个人的生活不能单纯地依赖社会保障，还要靠自身的努力，而且一个人得到的
社会保障越多，自身的努力往往就越少

社会主义女权主义向社会寻求保障的同时，也就承认了自己是弱者，这是一个不
小的失策。

据说女人可以有比男人更强烈、持久的性高潮，也是一种优越的证明，我很怀疑
这种证明的严肃性。

作为一个男人，我同意自由女权主义，并且觉得这就够了。从这种认同里，我能
获得一点平常心，并向其他男人推荐这种想法。我承认男人和女人很不同，但这
种差异并不意味着别的：既不意味着某个性别的人比另一种性别的人优越，也不
意味着某种性别的人比另一种性别的人高明。一个女孩子来到人世间，应该像男
孩一样，有权利寻求她所要的一切。假如她所得到的正是她所要的，那就是最好
的

目之于色也有同美焉

假如修饰自己意味着尊重对方，还是打扮一下好。

梦想虽不见得都是伟大事业的起点，但每种伟大的事业必定源于一种梦想--我

至于小说越来越不好看，则有另外的原因。这是因为有人要求它带有正确性、合
理性、激励人们向上等等，这样的小说肯定无趣。换言之，那些人用现实所应有
的性质来要求小说、电影等等。我听人说，这样做的原因是小说和电影比现实世
界容易管理，如此说来，这是出于善良的动机，正如堂·吉诃德挑风车也是出于
善良的动机。但是这样做的结果却很不幸。

后一种想法是没有道理的。假定此说是有理的，想当作家的人就该时常把自己吊
起来，想当历史学家的人就该学太史公去掉自己的男根，想当音乐家的人就该买
个风镐来家把自己震聋--以便像贝多芬，想当画家的人就该割去自己的耳朵--混
充凡·高，什么都想当的人就得把什么都去掉，像个梆子，听起来就不是个道理。

真正有出息的人是对名人感兴趣的东西感兴趣，并且在那上面做出成就，而不是
仅仅对名人感兴趣。

人有多种兴趣，性只是其中的一种，色情品又只是其中一个小小的侧面。几乎没
有人会把性当作自己的主要生活兴趣，把色情品当作自己的主要生活兴趣的人就
更少见

我本人又是个读者，年登不惑，需要看专业书，并且喜欢看严肃的文学书，但是
市面上只有七十二个故事的《十日谈》、节本《金瓶梅》，和被宰得七零八落的
雷马克，还有一些性心理学、性社会学的书，不客气地说，出得完全是乌七八糟。
前些日子买了一本福柯的《性史》，根本看不懂，现在正想办法找英文本来看。
这种情形对我是一种极大的损害。在此我毫不谦虚地说，我是个高层次的读者，
可是书刊检查却拿我当十六岁的孩子看待。

Story of O

人对于人的认识，容易带有偏见。比如自我中心、文化中心主义等等。

不要以为有了实证方法，思辨就不重要了。实际上，要提出有意义的假设，必须
下一番思辨功夫。这

既然这不由他本人决定，同性恋就不是一种道德或者思想问题

同性恋者和异性恋者是不能仅仅从行为上区分的，真正的分界是看某人在同性恋
和异性恋这两种性生活方式中选择哪一种

我们说男同性恋者占男性人口的1%到10%，是指终身的绝对同性恋者。

人的存在是一种自然现象，而不是某种意志的产物。这种现象的内容就包括：人
和人是不一样的，有性别之分，贤愚之分，还有同性恋和异性恋之分，这都是自
然的现象。

有一个形容缺德行为的顺口溜：打聋子骂哑巴扒绝户坟--现在可以给它加上一句：
敲诈同性恋。打聋子缺德，是因为他不知你为何打他，也就不知该不该还手；骂
哑巴缺德，是因为他还不了口；扒绝户坟缺德，是因为没有他的后人来找你算账；
敲诈同性恋缺德，是因为他不敢报案。这四种行为全在同一水平线上。照我们的
看法，这才是"丑恶现象"，应当加以根除。一个现象是否丑恶，应当由它的性质
来决定，而不是由它是针对什么人来决定。

。国外有些同性恋者认为，从一而终，是异性恋社会里的陈腐观念，他们就喜欢
时常更换性伴。对此我倒无话可说。但一般来说，性乱是社会里的负面现象，是
一种既不安定又危险的生活方式。一个有理性的人总能相信，这种生活方式并不
可取。

医学没有办法把同性恋者改造成异性恋者--我猜这是因为性倾向和人的整个意识
混为一体--所谓矫治，无非是剥夺他的性能力。假如此说属实，矫治就没什么道
理。有的人渴慕异性，有些人渴慕同性，但大家对爱情的态度是一样的，歧视和
嘲笑是没有道理的。

在社会科学的出发点方面，有两种对立的立场：一种是说，科学在寻求真理，真
理是对事实的实事求是；另一种则说，真理是由一种教义说明的，科学寻求的是
此种真理正大光明的颂词。一种说，科学不应屈服于一种权威的教义；另一种说，
科学本身就是权威的教义。一种说，不应出卖科学；一种则说，不存在出卖的问
题，它自从出世，就在买方手中。一种说，在科学中要避免学院式的装腔作势；
另一种则说，科学本身不是别的，恰恰就是学院式的装腔作势。一种说，科学是
出于求知的努力，是永不休止的学习过程；另一种则认为，科学原质是天生所有
的，后天的求学乃是养浩然正气，凡有助于正气的，可以格致一番，而不利于正
气的，则应勿视勿听，以求达到思无邪的境界。

科学研究的实事求是原则、反意识形态中心主义原则和善良原则

我们也不知道，为什么大多数中国人宁愿在婚丧嫁娶方面花很多钱，却不肯用来
改善生活。

倘若生活中存在着完全不能解释的事，那很可能是因为有我们所不知道的事实，
而不知道的原因却是我们并不真正想知道。

人类的存在，文明的发展就是个减熵过程，

我总觉得读过了《情人》，就算知道了现代小说艺术；读过道乾先生的译笔，就
算知道什么是现代中国的文学语言了。

文字是用来读的，不是用来看的。看起来黑鸦鸦的一片，都是方块字，念起来就
大不相同。诗不光是押韵，还有韵律；散文也有节奏的快慢，或低沉压抑，沉痛
无比，或如黄钟大吕，回肠荡气--这才是文字的筋骨所在。

任何一门艺术只有从作品里才能看到--

众所周知，六七十年代，中国处于非性的年代。在非性的年代里，性才会成为生
活主题，正如饥饿的年代里吃会成为生活的主题。古人说：食色性也。想爱和想
吃都是人性的一部分，如果得不到，就成为人性的障碍。

有些话仿佛永远讲不出口，仅仅是因为别人已经把反对它的话讲了出来。因此这
些话就成了心底的暗流，形不成文字，也形不成话语，甚至不能形成有条理的思
路--它就变成了郁结的混沌。而已经讲出的话则被人们一再重复，结构分明地架
在混沌之上。我看到一个无智的世界，但是智慧在混沌中存在；我看到一个无性
的世界，但是性爱在混沌中存在；我看到一个无趣的世界，但是有趣在混沌中存
在。我要做的就是把这些讲出来。

战争即和平自由即奴役无知即力量。

有这样的孩子，那个可怜的女人的日子一定过得够呛。再过一、两年，他们就要
日日夜夜地监视着她，看她有没有思想不纯的迹象。如

千篇一律的时代，孤独的时代，老大哥的时代，双重思想的时代，向未来，向过
去，向一个思想自由、人们各不相同、但并不孤独生活的时代――向一个真理存
在、做过的事不能抹掉的时代致敬!

所谓自由就是可以说二加二等于四的自由。

如果你爱一个人，你就爱他，当你没有别的东西可以给他时，你仍把你的爱给他。
最后一块巧克力给抢走时，他母亲怀里抱着孩子。这没有用，改变不了任何东西，
并不能变出一块巧克力来，并不能使那孩子或她自已逃脱死亡;但是她仍抱着她，
似乎这是很自然的事。

。这真是神仙般的生活，但愿能永生永世地过下去。在你搞到一本你知道最后总
要一读再读的书的时候，你往往会无目的地翻开到一个地方，随便读一段

后来你也许可以伪装这不过是一种计策，这么说是为了使他们停下来，真的意思
并不是这样。但是这不对。当时你说的真是这个意思。你认为没有别的办法可以
救你，因此你很愿意用这个办法来救自已。你真的愿意这事发生在另外一个人身
上。他受得了受不了，你根本不在乎。你关心的只是你自己。” “你关心的只
是你自己，”他随声附和说。 “在这以后，你对另外那个人的感情就不一样
了。” “不一样了，”他说，“你就感到不一样了。”

假如一个社会长时间不进步，生活不发展，也没有什么新思想出现，对知识分子
来说，就是一种噩梦。这种噩梦会在文学上表现出来。这正是中国文学的一个传
统。这是因为，中国人相信天不变道亦不变，在生活中感到烦躁时，就带有最深
刻的虚无感

我原是学理科的，学理科的不承认有牢不可破的囚笼，更不信有摆不脱的噩梦。
人生唯一的不幸就是自己的无能

所谓幽闭类型的小说，有这么个特征：那就是把囚笼和噩梦当作一切来写。或者
当媳妇，被人烦；或者当婆婆，去烦人；或者自怨自艾；或者顾影自怜。总之，
是在不幸之中品来品去。

要努力去做事，拼命地想问题，这才是自己的救星。

任何一个文明都该容许反讽的存在，这是一种解毒剂，可以防止人把事情干到没
滋没味的程度。

，我以为人生在世应当努力，应该善良，而血统这种说法对于培养这些优良品质
毫无帮助。除此之外，血统这件事还特别的荒唐

媚俗"，是指艺术家为了取悦大众，放弃了艺术的格调。

媚雅"，简直不知是什么意思。这个词的意思我倒知道，是指大众受到某些人的
蛊惑或者误导，一味追求艺术的格调，也不问问自己是不是消受得了。

现在用的软件都是我自己写的。我用它写文章，做科学工作：算题，做统计--顺
便说

这样禁来禁去，总有一天禁到我身上。我的小说内容健康，但让我逐行说明每一
句都是良好的信息，我也做不到。再说，到那时我已经吓傻了，哪有精神给自己
辩护。电影电视都能禁，为什么不能禁小说？我们爱读书，还有不识字的人呢，
他们准赞成禁书。好吧，我不写作了，到车站上去扛大包。我的身体很好，能当
搬运工。别的作家未必扛得动大包??

我赞成对生活空间加以压缩，只要压不到我。但压来压去，结果却出乎我的想

海明威在《钟为谁鸣》里说过这个意思：所有的人是一个整体，别人的不幸就是
你的不幸。所以，不要以为丧钟是为谁而鸣--它就是为你而鸣

作者的感慨是："奸近杀"啊。由此可以重新解释这个故事：这两只蚂蚱在篱笆底
下偷情，是两个堕落分子。而那只黄里透绿、肥硕无比的癞蛤蟆，却是个道德上
的义士，看到这桩奸情，就跳过来给他们一点惩戒--把它们吃了。寓意是好的，
但有点太过离奇：癞蛤蟆吃蚂蚱，都扯到男女关系上去，未免有点牵强。我总怀
疑那只癞蛤蟆真有这么高尚

中国为什么没有这种幽默，道理是明摆着的：这里的权力不容许幽默，只容许假
正经。

假设我要搞的是《侏罗纪公园》那样的电影，我怎么跟上面说呢？我这部片子，
现实意义在哪里？积极意义又在哪里？为什么我要搞这么一部古怪的电影？最主
要的问题是：我这部电影是怎样配合当前形势的？这些问题我一个都答不上来，
可答不上来又不行。这样一想，结论就出来了：当初我就不该给自己找这份麻烦。

与其为数顷无源之塘水，不若为数尺有源之井水，生意不穷

同化，在生物学上指生物从外界取得养分，构造自己的机体

。根据我的人生经验，假如你遇到一种可疑的说法，这种说法对自己又过于有利，
这种说法准不对，因为它是编出来自己骗自己的

认自己傻过，这是一种美德，

明星崇拜是一种癫狂症，病根不在明星身上，而是在追星族的身上

我以为科学和艺术的正途不仅不是去关怀弱势群体，而且应当去冒犯强势群体。
使最强的人都感到受了冒犯，那才叫做成就。

电视观众来说，幸运的是：不是每天都是节日和大的纪念日，在这些日子里可以
指望看点好节目。对电视台的编导来说，不幸的也是：不是每天都是节日和纪念
日，那一天他们必须给观众找点节目。我现在站在编导一方来说

青年的动人之处，就在于勇气，和他们的远大前程。

真古迹使人留恋之处，在于它历经沧桑直至如今，在它身边生活，你才会觉得历
史至今还活着。要是可以随意翻盖，那就会把历史当作可以随意捏造的东西，一

真古迹使人留恋之处，在于它历经沧桑直至如今，在它身边生活，你才会觉得历
史至今还活着。要是可以随意翻盖，那就会把历史当作可以随意捏造的东西，一
个人尽可夫的娼妇；这两种感觉真是大不相同。

一座城市的历史不可能是别的，只能是它的建筑。

做成一件事，需要比呼吁更大的勇气和努力。要是你有这些勇气和精力，不妨动
手去做。要是没这份勇气和精力，不如闭上嘴，省点唾沫

工业不会造成环境问题，农业也不会造成环境问题，环境问题是人造成的。知识
分子悲天悯人的哀号解决不了环境问题，开大会、大游行、全民总动员也解决不
了这问题。只要知道一件事就可以解决环境问题：人不能只管糟蹋不管收拾。收
拾一下环境就好了，在其中生活也能像个体面人。

罗素说，中国文化里只重家族内的私德，不重社会的公德公益，这一点造成了很
要命的景象。费孝通说，中国社会里有所谓"差序格局"，与己关系近的就关心，
关系远的就不关心或少关心。结果有些事从来就没人关心。

一辈子都在弄他的那片土、那只猪，结果自己也变成了一片土、一只猪

贫穷是种生活方式

至于他们的生菜色拉，只不过是些胡乱扯碎的生菜叶子。文学界的老前辈梁实秋
有吃后感如下：这不是喂兔子吗

钱这种东西，我们将来会有的，我对此很有信心。

罗素先生曾说：真正的幸福来自于建设性的工作。

虽然人生在世会有种种不如意，但你仍可以在幸福与不幸中作选择

据我所见，诀窍和真正的知识是不同的。真正的知识不仅能说明一件事应该怎样
做，还能说明为什么要这样做。而那些诀窍呢，从来就说不出为什么，所以是靠
不住的。能使人变聪明的诀窍是没有的。倒是有种诀窍能使人觉得自己变聪明了，
实际上却变得更笨。人应该记住自己做过的聪明事，更该记得自己做的那些傻事

我对权力没有兴趣，对钱有一些兴趣，但也不愿为它去受罪--做我想做的事(这
件事对我来说，就是写小说)，并且把它做好，这就是我的目标。

总而言之，干什么都是好的，但要干出个样子来，这才是人的价值和尊严所在。
人在工作时，不单要用到手、腿和腰，还要用脑子和自己的心胸。

维特根斯坦一样说道：我度过了美好的一生；也不能像司汤达一样说：活过，爱
过，写过。

假如我今天死掉，恐怕就不能像维特根斯坦一样说道：我度过了美好的一生；也
不能像司汤达一样说：活过，爱过，写过。我很怕落到什么都说不出的结果，所
以正在努力工作。

**** 观感

*** 《黄金时代》
:PROPERTIES:
:Random:   reading
:END:

**** 时间

- 3rd :: 2016/02/10--2016/02/10

**** 摘录

大家都认为，结了婚的女人不偷汉，就该面色黝黑，乳房下垂。而你脸不黑而且
白，乳房不下垂而且高耸，所以你是破鞋。假如你不想当破鞋，就要把脸弄黑，
把乳房弄下垂，以后别人就不说你是破鞋。当然这样很吃亏，假如你不想吃亏，
就该去偷个汉来。这样你自己也认为自己是个破鞋。别人没有义务先弄明白你是
否偷汉再决定是否管你叫破鞋。你倒有义务叫别人无法叫你破鞋

那一天我二十一岁，在我一生的黄金时代。我有好多奢望。我想爱，想吃，还想
在一瞬间变成天上半明半暗的云。后来我才知道，生活就是个缓慢受锤的过程，
人一天天老下去，奢望也一天天消失，最后变得像挨了锤的牛一样

她说道：你请我来吃鱼，做倾心之谈，鱼在哪里？我只好说，鱼还在河里。她说
好吧，还剩下一个倾心之谈

伟大友谊

其实伟大友谊不真也不假，就如世上一切东西一样，你信它是真，它就真下去；
你疑它是假，它就是假的。我的话也半真不假

于是我就像作家一样写起交待材料来。首先交待的就是逃跑上山那天晚上的事。
写了好几遍，终于写出陈清扬像考拉熊。她承认她那天心情非常激动，确实像考
拉熊。因为她终于有了机会，来实践她的伟大友谊。于是她腿圈住我的腰，手抓
住我的肩膀，把我想像成一棵大树，几次想爬上去。

陈清扬说，那一刻她感到浑身无力，就瘫软下来，挂在我肩上。那一刻她觉得如
春藤绕树，小鸟依人，她再也不想理会别的事，而且在那一瞬间把一切部遗忘。
在那一瞬间她爱上了我，而且这件事永远不能改变。

陈清扬说她真实的罪孽，是指在清平山上。那时她被架在我的肩上，穿着紧裹住
双腿的筒裙，头发低垂下去，直到我的腰际。天上白云匆匆，深山里只有我们两
个人。我刚在她屁股上打了两下，打得非常之重，火烧火撩的感觉正在飘散。打
过之后我就不管别的事，继续往山上攀登。 陈清扬说，那一刻她感到浑身无力，
就瘫软下来，挂在我肩上。那一刻她觉得如春藤绕树，小鸟依人，她再也不想理
会别的事，而且在那一瞬间把一切部遗忘。在那一瞬间她爱上了我，而且这件事
永远不能改变。

陈清扬说，那一回她躺在冷雨里，忽然觉得每一个毛孔都进了冷雨。她感到悲从
中来，不可断绝。忽然间一股巨大的快感劈进来。冷雾，雨水，都沁进了她的身
体。那时节她很想死去。她不能忍耐，想叫出来，但是看见了我她又不想叫出来。
世界上还没有一个男人能叫她肯当着他的面叫出来。她和任何人都格格不入。

陈清杨说，在章风山她骑在我身上一上一下，极目四野，都是灰蒙蒙的水雾。忽
然间觉得非常寂寞，非常孤独。虽然我的一部分在她身体里磨擦，她还是非常寂
寞，非常孤独

敦敦伟大友谊

回来的路上扛着她爬披。那时旱季刚到，天上白云纵横，阳光灿烂。可是山里还
时有小雨。红土的大板块就分外的滑。我走上那块烂泥板，就像初次上冰场。那
时我右手扣住她的大腿，左手提着猎枪，背上还有一个背篓，走在那滑溜溜的斜
面上，十分吃力。忽然间我向左边滑动，马上要滑进山沟，幸亏手里有条枪，拿
枪拄在地上。那时我全身绷紧，拼了老命，总算支持住了。可这个笨蛋还来添乱，
在我背上扑腾起来，让我放她下去。那一回差一点死了。 等我刚能喘过气来，
就把枪带交到右手，抡起左手在她屁股上狠狠打了两巴掌，隔了薄薄一层布，倒
显得格外光滑。她的屁股很圆。鸡巴，感觉非常之好的啦！她挨了那两下登时老
实了。非常的乖，一声也不吭。

**** 书评

- [[https://app.yinxiang.com/shard/s52/nl/11551545/c6478ab5-60de-4f38-a4fb-7aee0ba613d1?title=%E5%8F%AA%E6%9C%89%E5%81%9A%E7%88%B1%E8%83%BD%E5%A4%9F%E5%AF%B9%E6%8A%97][只有做爱能够对抗]]

**** 观感

*** 《青铜时代》
:PROPERTIES:
:RANDOM:   reading
:END:

**** 《万寿寺》

***** 时间

- 1st :: 2016/02/17--2016/02/19

***** 摘录

***** 书评

***** 观感
**** 《红拂夜奔》

***** 时间

- 1st :: 2016/02/20--2016/02/21

***** 摘录

***** 书评

***** 观感

**** 《寻找无双》

***** 时间

- 1st :: 2016/02/22--2016/02/222

***** 摘录

***** 书评

***** 观感
***
** 米兰·昆德拉
*** 《不能承受的生命之轻》

**** 时间

- 1st :: 2013/10/28--2013/11/05

**** 摘录

**** 观感

** 罗素

*** 《幸福之路》

**** 时间

- 1st :: 2015/07/25

**** 摘录

Byronic Unhappiness

I am persuaded that those who quite sincerely attribute their sorrows
to their views about the universe are putting the cart before the
horse: the truth is that they are unhappy for some reason of which
they are not aware, and this unhappiness leads them to dwell upon the
less aggreeable characteristics of the world in which they live.


The human animal, like others, is adapted to a certain amount of
struggle for life, and when by means of great wealth homo sapiens can
gratify all his whims without effort, the mere absence of effort from
his life removes an essential ingredient of happiness. The man who
acquires easily things for which he feels only a very moderate desire
concludes that the attainment of desire does not bring happiness. If
he is of a philosophic disposition, he concludes that human life is
essentially wretched, since the man who ahs all he wants is still
unhappy. He forgets that to be vithout some of the things yyou want is
an indipensable part of happiness.

There can be no value in the whole unless there is value in the
parts. Life is not to be conceived on the analogy of a melodrama in
which the hero and heroine go through incredible misfortunes for which
they are comprensated by a happy ending.

I have by no means lost my belief in love, but the kind of love that I
can believe in is no the kind that the Victoians admired; it is
adventurous and open-eyed, and, while it gives knowledge of good, it
does not involve forgetfulness of evil, nor dees it pretend to be
sanctified or holy.


Love is to be valued in the first instance - and thist, though not its
greatest value, is essential to all the rest - as in itself a source
of delight.

In the second place, love is to be valued because it enhances all the
best pleasures, such as music, and sunrise in mountains, and the sea
under the full moon. A man who has never enjoyed beautiful things in
the company of a woman whom he loved has not experienced to the full
the magic power of which such things are capable.

Love is able to break down the hard shell of the ego, since it is a
form of biological cooperation in which the emotions of each are
necessary to the fullfilment of the other's instinctive purpose.

Man depends upon cooperation, and has been provided by nature,
somewhat inadequately, it is true, with the instinctive apparatus out
of which the friendliness requred for cooperation can spring. Love is
the first and commonest form of emotion leading to cooperation, and
those who have experienced love with any intensity will noe be content
with a philosophy that supposes their highest good to be indepnedent
of the person loved.

Competition

For my part, the thing that I would wish to obtain from money would be
leisure with security. But what the typical modern man desires to get
with it is more money, with a view to ostentation, splendour, and the
outshining of those who have hitherto been his equals.

Boredom and excitement

One of the esssentials of boredom consists in the contrast between
present circumstances adn some other more agreeable circumstances
which forc themselves irresistibly upon the imagination. It is also
one of the essentials of bordom that one's faculities must not be
fully occupied.

The opposite of boredom, nn a word, is not pleasure, but excitement.

A life too fill of excitement is an exhausting life, in which
continually stronger stimuli are needed to geive the thrill that has
comme to be thought an esential part of pleasure. There is an element
of boredom which is inseparable from the avoidance of too much
excitement, and too much excitement not only underlines the health,
but dulls the palate for every kind of pleasure, substituting
titillations for profound orgranic satisfactions, cleverness for
wisdom, and jagged surprises for beauty.

I do not want to push to extremes the objection to excitement. A
certain amount of it is wholesome, but like almost everything else,
the matter is quantitative. Too little may produce morbid cravings,
too much will produce exhaustion. A certain power of enduring boredom
is therefore essential to a happy life, and is one of the things that
ought to be taught to the young.

I do not mean that monotony has any merits of its own; I mean only
that certait good thing are not possible except where there is a
certain degree of monotony.

Consider the diffirence between love and mere sex attraction. Love is
an experience in which our whole being is renewed and refreshed as is
that of plants by rain after drought. In sex intercourse without love
there is nothing of this. When the momentary pleasure is ended, there
is fatigue, disgust, and a sense that life is hollow. Love is part of
the life of Earth; sex without love is not.

Fatigue

Most men and women are very deficient in control over their
thoughts. I mean by this that they cannot cease to think about
worrying topics at times when no action can be taken in regard to
them.

It is amazing how much both happiness and efficiency can be increased
by the cultivation of an orderly mind, which thinks about matter
adequately at the right time rather than inadepquately at all
times. When a difficult or worrying decision has to be reached, as
soon as all the data are available, give the matter your best thought
and make your decision; having made the decision, do not revise it
unless some new fact comes to your knowledge. Nothing is exhausting as
indecision, and nothing is so futile.

Gradually I taught myself to feel that it did not matter whether I
spoke well or ill, the universe would remain much the same in either
case. I found that the less I cared whether I spoke well or badly, the
less badly I spoke, and gradually the nervous strain diminished almost
to vanishing point. A great deal of nervous fatigue can be dealt with
in this way. Our doings are not so important as we naturally suppose;
our successes and failures do not after all matter very much. Even
great sorrows can be survived; troubles which seem as if they must put
an end to happiness for life fade with the lapse of time until it
becomes almost impossible to remember their poignancy. But over and
above these self-centered considerations is the fact that one's ego is
no very large part of the world. The man who can centre his thoughts
and hopes upon something transcending self can find certain peace in
the ordinary troubles of life which is impossible to the pure egoist.

My own belief is that a conscious thought can be planted into the
unconscious if a sufficient amount of vigour and intensity is put into
it. Most of the unconscious consisit of what were once highly
emotional conscious thoughts, and in this way the unconscious can be
led to do a lot of useful work. I have found, for example, that if I
have to write upon some rather difficult topic the best plan is to
think about it with very great intensity --- the greatest intensity of
which I am capable --- for a few hours or days, and at the end of that
time give oders, so to speak, that the work is to proceed
underground. After some months I return consciously to the topic and
find that the work has been done. Befor I had discovered this
technique, I used to spend the intervening months worrying because I
was making no progress; I arrived at the solution none the for this
worry, and the intervening months were wasted, whereas now I can
devote them to other pursuits.

Worry is a form of fear, and all forms of fear produce fatigue.

Now every kind of fears grows worse by not being looked at. The effort
to tuning away one's thoughts is a tribute to the horribleness of the
spectre from which one is averting one's gaze; the proper course with
every kind of fear is to think about it rationally and calmly, but
with great concentration, until it has become completely familiar. In
the end familiarity will blunt its terrors; the whole subject will
become boring, and our thoughts will turn away from it, not, as
formerly, by and effort of will, but through mere lack of interest in
the topic. When you find yourself inclined to brood on anything, no
matter what, the best plan always is to think about it even more than
you naturally would, until at last its morbid fascination is worn off.

Envy

Of al the characrteristics of ordinary human nature envy is the most
unfortunate; not only does the envious person wish to inflict
misforture and do so whenever he can with impunity, but he is also
himself rendered unhappy by envy. Instead of deriving pleasure from
what has has, he derives pain from what others have.

Fortunately, however, there is in human natre a compensating passion,
namely that of admiration. Whoever wishes to increase human happiness
must wish to increase admiration and to diminish envy.

Leaving saints out of account, the only cure for envy in the case of
ordinary men and women is happiness, and the difficulty is that envy
is itself a terrible obstacle to happiness.

But the envious man may say:'What is the good of telling me that the
cure for envy is happiness? I cannot find happiness while I continue
to feel envy, and you tell me that I cannot cease to be envious until
I find happiness.' But real life is never so logical as this. Merely
to realise the casuses of one's own envious feelings is to take a long
step towards curing them. The habit of thinking in terms of
comparisons is a fatal one. When anything pleasant occurs it should be
enjoyed to the full, without stopping to think that it is not so
pleasant as something else that may possibly be happening to someone
else.

With the wise man, what he has does not cease to be enjoyable because
someone else has something else. Envy, in fact, is one form of a vice,
partly moral, partly intellectual, which consists in seeing things
never in themselves, but only in their relations.

For all this the proper cure is mental discipline, the habit of not
thinking profitless thoughts. After all, what is more enviable than
happiness? And if I can cure myself of envy I can acquire happiness
and become enviable.

You cannot, therefore, get away from envy by means of success alone,
for there will always be in history or legend some person even more
successful than you are. You can get away from envy by enjoying the
pleasures that come your way, by doing the work that you have to do,
and by avoiding comarisions with those whom you imagine, perhaps quite
falsely, to be more fortunate than yourself.

Unnecessary modesty has a great deal to do with envy. Modesty is
considered a virtue, but for my part I am very doubtful whether, in
its more extreme forms, it deserves to be so regarded. Modest people
need a great deal of reassuring, and often do noe dare to attempt
tasks which they are quite capable of performing. Modest people
believe thmeselves to be outshone by those with whom they habitually
associate. They are therefore paritcularly prone to envy, and, through
envy, to unhappiness and ill will.

For my part, I think there is much to be said for bringing up a body
to think himself a fine fellow.

While it is true that envy is the chief motive force leading to
justice as between different classes, different nations, and different
sexes, it is at the same time true that the kind of justice to be
expected as a result of envy is likely to be the worst possible kind,
namely that which consists rather in diminishing the pleasures of the
fortunate than in increasing those of the unfortunate. Passions which
work havoc in private life work havoc in public life also. It is not
to be supposed that out of something as evil as evny good results will
follow. Thos, therefore, who from idealistic reasons desire profound
changes in our social system, and a great increase of social justice,
must hope that other force than envy will be instrumental in bringing
the changes about.

The sense of sin

Man must not allow themselves to be swayed by their moods, believing
one thing at one moment and another at another. The sense of sin is
especially prominent at moments when the conscious will is weakened by
fatigue, by illness, by drink, or by any other cause.

What a man deliberately believes with his whole reason when he is
vigorous out to be to him the norm as to what he had better believe at
all times.

But even when a man has offended against his own rational code, I
doubt whether a sense of sin is the best method of arriving a better
way of life. There is in the sinse of sin something abject, something
lacking in self-respect. No good was ever done to anyone by the loss
of self-respect. The rational man will regard his own undesirable acts
as those to others, as acts produced by certain circumstances, and to
be either by a fuller realisation that they are undesirable, or, where
this is possible, by avoidance of the circumstances that cause them.

An expansive and generous attitude towards other people not only gives
happiness to others, but is an immense source of happiness to its
processor, since it causes him to be generally liked. But such an
attitude is scarcely possible to the man haunted by a sense of sin.

Nothing so much diminishes not only happiness but efficiency as a
personality divided against itself. The time spent in producing
harmony between the difference parts of one's personality is time
usefully employed. I do not suggest that a man should set apart, say,
an hour a day for self-examination. This is do my mind by no means the
best method since it increases self-absorption, which is part of the
disease to be cured, for harmonious personality is directed
outward. What I suggest is that a man should make up his mind with
emphasis as to what he rationally believes, and should never allow
contrary irrational beliefs to pass unchallenged of obtain a hold over
him, however brief.

There is an idea that rationality, if allowed free play, will kill all
the deeper emotions. This belief appears to me to be due to an
entirely erroneous conception of the function of reason in human
life. It is not the business of reason to generate emotions, though it
may be part of its function to discover ways preventing such emotions
as are an obstacle to well-being, To find ways of minimizing hatred
and envy is no doubt part of the function of a rational
psychology. But it is a mistake to suppose that in minimizing these
passions we shall at the same time diminish the strength of those
passions which reason does noe condemn. In passionate love, in
parental affecttion, in friendship, in benevolence, in devotion to
science or art, there is nothing that reason should wish to
diminish. The rational man, when he feels any or all these emotions,
will be glad that he feels them and will do nothing to lessen their
strength, for all these emotions are parts of the good life, the life,
that is, that makes for happiness both in oneself and in others. There
is nothing irrational in the passions as such, and many irrational
people feel only th e most trivial passions. No man need fear that by
making himself rational he will make his life dull. On the contrary,
since rationality consists in the main of internal harmony, the man
who achieves it is freer in his contemplation of the world and in the
use of his energies to achieve external purposes that is the man who
is perpetually hampered by inward conflicts. Nothing is so dull as to
be encased in self, nothing so exhilarating as to have attention and
energy directed outwards.

And perhaps the sickness is a necessary stage in mental development. I
am inclined to think that the man who has passed beyond it by help of
reason has reached a higher level than the man who has never
experienced either the sickness or the cure.

The happiness that requires intoxication of no matter what sort is a
spurious and unsatisfying kind. The happiness that is genuinely
satisfying is accompanied by the fullest exercise of our faculties,
and the fullest realisation of the world in which we live.

Persecution mania

Our motives in doing good are seldom as pure as we imageing them to
be. Love of power is insidious; it has many disguises, and is often
the source of the pleasure we derive from doing what we believe to be
good to other people.

These illustrations suggest four general maxims, which will prove an
adequate preventive of persecution mania if their truth is sufficently
realised. The first is: remember that your motives are not always as
altruistic as they seem to yourself. The second is: don't
over-estimate your own merits. The third is: don't expect others to
take as much interest in you as you do yourself. And the fourth is:
don't imageine that the most people give enough thought to you to have
any special desire to persecute you.

Conventional morality inculcates a degree of altruism of which human
nature is scarcely capable, and those who pride themselvesupon their
virtue often imagine that they attain this unattainable ideal.

It is better therefore that a man should eat because he enjoys his
food than that the time he spends at his meals should be solely
inspired by a desire for the public good. And what applies to eating
applies to everything else. Whatever is to be done can only be done
adequately by the help of a certain zest, and zest is difficult
without some self-regarding motive.

No satisfaction based upon self-deception is solid, and, however
unpleasant the truth may be, it it better to face it once for all, to
get used to it, and to process to build your life in accordance with
it.

Fear of public opinion

Public opinion is always more tyrannical towards those who obviously
fear it than towards those who feel indifferent to it.

To be out of harmony with one's surroundings is, of course, a
misfortune, but it is not always a misfortune to be avoided at all
costs. Where the environment is stupid or prejudiced or cruel, it is a
sign of merit to be out of harmony with it.

There is a conmfortable doctrine that genius will always make its way,
and on the strength of this doctrine many people consider that the
persecution of youthful talent cannot do much harm. But there is no
gound whatever for accepting this doctrine. It is like the the theory
that murder will out. Obviously all the murders we know of have been
discovered, but who knows how many there may be which have never been
heard of? In like manner all the men of genius that we have ever heard
of have triumphed over adverse circumstances, but that is no reason
for supposing that there were nor inmumerable others who succumbed in
youth.

The arguments of parents should noe be a sufficient reason for
relinguishing the attempt. If, in spite of all they say, you carry out
your intention, they will soon come round, much sooner in fact than
either you or they suppose. If on the other hand you find professional
opinion discouraging, that is another matter, for professional opinion
mush always be treated with respect by beginners.

I think that in general, apart from expert opinion, there is too much
respect paid to the opinions of others, both in great matters and in
small ones. One should as a rule respect public opinion in so far as
is necessary to avoid starvation and to keep out of prision, but
anything that goes beyond this is voluntary submission to an
unnecessary tyranny, and is likely to interfere with happiness in all
kinds of ways.

There is, of course, no point in deliberately flouting public opinion;
this is still to be under its demination, though in a topsy-turvy
way. But to be genuinely indifferent to it is both a strength and a
source of happiness. And a society composed of men and women who do
not bow too much to the conventions is a far more interesting society
that one in which all behave alike.

Fear of public opinion, like every other form of fear, is oppressive
and stunts growth. It is difficult to achieve any kind of greatness
while a fear of this kind remains strong, and it is impossible to
acquire that freedom os spirit in which happiness consists, for it is
essential to happiness that our way of living should spring from our
won deep impulses and not from the accidental tastes and desires of
those who happen to be our neighbours, or even our relations.

Is happiness still possible

Pleasures of achievement demand difficulties such that beforehand
success seems doubtful although in the end it is usually
achieved. This is perhaps the chief reason why a not excessive
estimate of one's own powers is a source of happiness. The man who
underestimates himself is perpetually being surprised by success,
whereas the man who overestimates himself is just as often surprised
by failure. The former kind of surprise is pleasant, the latter
unpleasant. It is therefore wise to be not unduly conceited, though
also not too modest to be enterprising.

Cynicism such as one finds very frequently among the most highly
educate young men and women of the West results from the combination
of comfort with powerlessness. Powerlessness makes people feel that
nothing is worth doing, and comfort makes the painfulness of this
feeling just endurable.

Consider what a vast field of ecstasy opens before the imagination
when one thinks os old china, snuff-boxes, Roman coins, arrow-heads,
and flint implements. It it true that many of us are too 'superior'
for these simple pleasures. We have aoo experienced them in boyhood,
but have thought them, for some reason, unworthy of a grown man. This
is a complete mistake. *Any pleasure that does no harm to other people
is to be valued.*

Fads and hobbies, however, are in many cases, perhaps most, not a
source of fundamental happiness, but a means of escape from reality,
of forgetting for the moment some pain too difficult to be faced
with. Fundermental happiness depends more than anything else upon what
may be called a friendly interest in persons and things.

A friendly interest in persons is a form of affectionateness, but not
the form of which is grasping and possessive and seeking always an
emphatic response. This latter form is a very frequently a source of
unhappiness. The kind that makes fo r happiness is the kind that likes
to observe people and finds pleasures of those with whom it it brought
into contract without desiring to acquire power over them or to secure
their enthusiastic admiration. The person whose attitude towards
others is genuinely of this kind will be a source of happiness and a
recipient of reciprocal kindness. His relations with others, whether
slight or serious, will satisfy both his interests and his affections;
he will not be soured by ingratitude, since he will seldom suffer it
and will not notice when he does. The same idiosyncrasies which would
get on another man's nerves to the point of exasperation will be to
him a source of gentle amusement. He will achieve without effort
results which another man, after long struggles, will find to be
unattainable. Being happy in himself, he will be a pleasant companion,
and this in turn will increase his happiness. But all this must be
genuine; it must not spring from an idea of self-sacrifice inspired by
a sense of duty. A sense of duty is useful in work, but offensive in
personal relations. People wish to be liked, not to be endured with
patient resignation. To like many people spontaneously and without
effort is perhaps the greatest of all sources of personal happiness.

Zest

The more things a man is interested in, the more opportunities of
happiness he has, and the less he is at the mercy of fate, since if he
loses one thing that he can fall back on another. Life is too short to
be interested in everything, but it is good to be interested in as
many things as are necessary to fill our days. We are all prone to the
malady of the introvert, who, with the manifold spectacle of the world
spread out before him, turns away and gazes only upon the emptiness
with.

The mind is a strange machine which can combine the materials offered
to it in the most astonishing ways, but without materials from the
external world it is powerless, and unlike the sausage machine it must
seize its materials for itself, since events only become experiences
through the interest that we take in them: if they do not interest us,
we are making nothing of them. The man, therefore, whose attention is
turned within finds nothing worthy of his notice, whereas the man
whose attention is turned outward can find within, in those rare
moments when he examines his soul, the most varied and interesting
assortment of ingredients being dissected and recombined into
beautiful or instructive patterns.

Some men find almost everybody boring, others quickly and easily
develop a friendly feeling towards those with whom they are brought in
contact, unless there is some definite reason for feeling otherwise.

The man in whiome one desire runs to excess at the expense of all
others is ususally a man with some deep seated trouble, who is seeking
to escape frome a spectre. It is not pleasure in the object itself
that is sought, but oblivion.

Affection

The man who feels himself unloved may take various attitudes as a
result. He may make desperate efforts to win affection, probably by
means of exceptional acts of kindness. In this, however, he is very
likely to be unsuccessful, since the motive of the kindness is easily
perceived by their beneficiaries, and human nature is so constructed
that it gives affection most readily to those who seem least to demand
it.

If you are walking over a chasm on a narrow plank, you are much more
likely to fall if you feel fear than if you do not. And the same thing
applies to the conduct of life. The fearless man may, of cource meet
with sudden disaster, but it is likely that he will pass unscathed
through many difficult situations in which a timid man would come to
grief.

The amount of solicitude of which a person can be the object without
damage to himself depends upon his character: a person who is hardy
and adventurous can endure a great deal without damage, whereas a
timid person should be encouraged to expect little in this way.

人生的暴风雨和自然界的一样多，来时也一样的突兀；有时内心的阴霾和雷电，
比外界的更可怕更致命。

我的目的，是想提出一张治疗日常烦闷的方子，那烦闷是文明国家内大多数人感
着痛苦的，而且因为并无显著的外因，所以更显得无可逃避，无可忍受。我相信，
这种不快乐大部分是由于错误的世界观，错误的伦理学，错误的生活习惯，终于
毁掉了对一般可能的“事物”的天然的兴致和胃口，殊不知一切的快乐，不问是
人类的或野兽的，都得以这些事物为根基。

但最大部分，还须归功于一天天的少关心自己。象旁的受过清教徒教育的人一样，
我惯对自己的罪过，愚妄，和失败，作种种的冥想。我觉得自己是——当然是准确
地——一个可怜的标本。慢慢地，我学会了对自己和自己的缺陷不再介介于怀，而
对外界的事物，却一天天的集中我的注意：譬如世界现状，知识的各部门，以及
我抱有好感的个人等

虚荣心一过了头，把每种活动本身的乐趣毁掉了，于是使你不可避免地无精打彩，
百无聊赖。原因往往是缺少自信，对症的药是培养自尊心。

虚荣心一过了头，把每种活动本身的乐趣毁掉了，于是使你不可避免地无精打彩，
百无聊赖。原因往往是缺少自信，对症的药是培养自尊心。但第一得凭着客观的
兴趣去做进取性的活动，然后可以获得自尊心。

典型的不快乐者，是少年时给剥夺了某些正常的满足的人，以致后来把这一种满
足看得比一切其余的满足更重要，从而使他的人生往着单一的方向走去，并且过
于重视这一种满足的实现，认为和一切与之有关的活动相反。

忧郁的人象失眠的人一样，常常以此自豪。也许他们的骄傲好似失掉了尾巴的狐
狸底那种，如果如此，那末救治之道是让他们明白怎样可以长出一条新的尾巴。

我愿读者相信，不论你用何种论据，理性决不会阻遏快乐；不但如此，我且深信
凡是真诚地把自己的哀伤归咎于自己的宇宙观的人，都犯了倒果为因的毛病：

The causes of these various kinds of unhappiness lie partly in the
social system, partly in individual psychology — which, of course, is
itself to a considerable extent a product of the social system.

I believe this unhappiness to be very largely due to mistaken views of
the world, mistaken ‘ethics, mistaken habits of life, leading to
destruction of that natural zest and appetite for possible things upon
which all happiness, whether of men or animals, ultimately depends.

This is due partly to having discovered what were the things that I
most desired and having gradually acquired many of these
things. Partly it is due to having successfully dismissed certain
objects of desire - such as the acquisition of indubitable knowledge
about something or other - as essentially unattainable. But very
largely it is due to a diminishing preoccupation with myself.

Gradually I learned to be indifferent to myself and my deficiencies; I
came to centre my attention increasingly upon external objects: the
state of the world, various branches of

knowledge, individuals for whom I felt affection.

But pains of these kinds do not destroy the essential quality of life,
as do those that spring from disgust with self. And every external
interest inspires some activity which, so long as the interest remains
alive, is a complete preventive of ennui. Interest in oneself, on the
contrary, leads to no activity of a progressive kind. It may lead to
the keeping of a diary, to getting psycho-analysed, or perhaps to
becoming a monk. But the monk will not be happy until the routine of
the monastery has made him forget his own soul. The happiness which he
attributes to religion he could have obtained from becoming a
crossing-sweeper, provided he were compelled to remain one. External
discipline is the only road to happiness for those unfortunates whose
self-absorption is too profound to be cured in any other way.

views of the world, mistaken 'ethics, mistaken habits of life, leading
to destruction of that natural zest and appetite for possible things
upon which all happiness, whether of men or animals, ultimately
depends. These are matters which lie within the power of the
individual, and I propose to suggest the changes by which his
happiness, given average good fortune, may be achieved

But very largely it is due to a diminishing preoccupation with myself

learned to be indifferent to myself and my deficiencies; I came to
centre my attention increasingly upon external objects: the state of
the world, various branches of knowledge, individuals for whom I felt
affection. External interests, it is true, bring each its own
possibility of pain: the world may be plunged in war, knowledge in
some direction may be hard to achieve, friends may die. But pains of
these kinds do not destroy the essential quality of life, as do those
that spring from disgust with self. And every external interest
inspires some activity which, so long as the interest remains alive,
is a complete preventive of ennui. Interest in oneself, on the
contrary, leads to no activity of a progressive kind. It

mean the man who is absorbed in the consciousness of sin. This man is
perpetually incurring his own disapproval, which, if he is religious,
he interprets as the disapproval of God. He

has an image of himself as he thinks he ought to be

which is in

site for Russellian in Japan continual

All serious success in work depends upon some genuine interest in the
material with which the work is concerned

Consequently the man whose sole concern with the world is that it
shall admire him is not likely to achieve his object

Consequently the man whose sole concern with the world is that it
shall admire him is not likely to achieve his object. But even if he
does, he will not be completely happy, since human instinct is never
completely self­centered, and the narcissist is limiting himself
artificially just as truly as is the man dominated by a sense of sin

Vanity, when it passes beyond a point, kills pleasure in every
activity for its own sake, and thus leads inevitably to listlessness
and boredom. Often its source is diffidence, and its cure lies in the
growth of self­respect

Power kept within its proper bounds may add greatly to happiness, but
as the sole end of life it leads to disaster, inwardly if not
outwardly

The typical unhappy man is one who, having been deprived in youth of
some normal satisfaction, has come to value this one kind of
satisfaction more than any other, and has therefore given to his life
a one­sided direction, together with a quite undue emphasis upon the
achievement as opposed to the activities connected with it

Men who are unhappy, like men who sleep badly, are always proud of the
fact. Perhaps their pride is like that of the fox who had lost his
tail; if so, the way to cure it is to point out to them how they can
grow a new tail

The man who acquires easily things for which he feels only a very
moderate desire concludes that the attainment of desire does not bring
happiness. If he is of a philosophic disposition, he concludes that
human life is essentially wretched, since the man who has all he wants
is still unhappy. He forgets that to be without some of the things you
want is an indispensable part of happiness

Truth, however, is not always interesting, and many things are
believed because they are interesting; although, in fact, there is
little other evidence in their favour

strike the balance,

Even in the pursuit of really important objects it is unwise to become
so deeply involved emotionally that the thought of possible failure
becomes a constant menace to peace of mind

Efficiency in a practical task is not proportional to the emotion that
we put into it; indeed, emotion is sometimes an obstacle to
efficiency.

The man who has suffered such fundamental defeat that he has given up
hope of serious achievement may learn the resignation of despair, and,
if he does, he will abandon all serious activity. He may camouflage
his despair by religious phrases, or by the doctrine that
contemplation is the true end of man, but whatever disguise he may
adopt to conceal his inward defeat, he will remain essentially useless
and fundamentally unhappy.

Itshould be our endeavour therefore, both in education and in attempts
to adjust ourselves to the world, to aim at avoiding self­centred
passions and at acquiring those affections and those interests which
will prevent our thoughts from dwelling perpetually upon ourselves. It
is not the nature of most men to be happy in a prison, and the
passions which shut us up in ourselves constitute one of the worst
kinds of prisons

Moreover, those who deceive themselves generally know at bottom that
they are doing so, and live in a state of apprehension lest some
untoward event should force unwelcome realisations upon them

**** 观感

*** 《西方哲学史》

**** 时间

- 1st :: 2015/09/27

**** 摘录

**** 观感

开始系统地阅读哲学，包括罗素、康德、尼采、黑塞等

** 黑塞
*** 《德米安》

**** 时间

- 1st :: 2015/09/23

**** 摘录

他的事情是找到自己的命运，不是随便哪个命运，并在内心充分享受它，完整而
不间断地享受它。其它一切都是不完整的，都是企图逃脱，都是逃回中庸的命运，
都是适应，都是害怕自己的内心。

我不能这样一丝不挂地、孤独地站着，我也是一条可怜的、懦弱我狗，它需要些
许温暖和食物，有时想要感觉到它同类的接近。

桌上放着几卷尼采的书。我跟他生活在一起，感受着他灵魂的孤独，嗅到了不断
驱赶着他的命运，跟他一起痛苦，并对曾经有过一位如此坚定不移走自己的道路
的人感到无比快乐。

每个人的真正职业只有一个：走向自身。

对觉醒的人们来说，除了寻找自己，，内心坚定起来，在自己的道路上摸索前进
而不管它通向何方这样一种责任以外，绝没有其它责任。

如果我最终不能赢得这场斗争，如果我屈服下来，重新使自己陷入污浊，那么我
会比所有其他从未奋斗过的人都更会。

凡是我们心灵所希望的，都不可以害怕，不可以看作禁忌。

每种宗教都是美好的，宗教是心灵，不管是用基督圣餐还是去麦加朝圣，都一样。

我喜欢听音乐，不过只喜欢听您弹那种完全没有限制的音乐，从这种音乐中可以
感觉到有一个人震撼着天堂和地狱。我想我很喜欢这种音乐，因为它没有什么道
德说教，我寻找某些不是说教的东西。在道德说教中我始终只有痛苦。

我除了要想按照我内心自然产生的愿望去生活以外，别无他求，这为什么如此艰
难？

欢乐和恐惧、男人和女人混合在一起，最神圣的和最卑劣的东西纠缠在一起，深
重的罪孽在最温柔的纯洁中闪光——这就是我的爱情梦幻，阿卜拉克萨斯也就是这
样。爱情不再是我开初所惊恐不安地感觉到的那种动物一样朦胧的情欲，也不再
是我献给贝雅特丽齐画像的内心虔诚的崇拜。爱情是两者兼而有之，两者兼而有
之或者还要多得多，爱情是寓于一体的天使形象和魔鬼、男人和女人，以及人和
动物，极善和极恶。我觉得自己必定会有这种经历，为此付出代价是我的命运，
我思念命运，害怕命运，但它总是在那里，总是控制着我。

鸟从蛋里挣脱出来，蛋即是世界。谁想要出生，就必须抽毁一个世界。鸟飞向神，
上帝叫阿卜拉克萨斯。

我不是生活在醉酒和污秽之中，生活中麻木和迷茫之中，直到正是我自身中的对
立面——对纯洁的渴念、对神圣的向往以一种活力激昂起来。

在我们自身内有一个人什么都知道，什么都想要，什么都比我们做得要更好。

命运和性情是一种概念的名称。

我把从黑暗势力收回的那部分生命献给了光明势力，我的目标不是情欲，而是纯
洁，不是幸福，而是美和智慧。

只有愿望完全在我自己心中，我的本质确实完全被愿望所充实，我才能把它付诸
实践，才能抱着足够强烈的念头。一旦出现这种情况，一旦你按照自内心对你发
出的命令去尝试某件事情，那么事情就成了。

每个人和生活都是一条通向自身的道路，都是对一条道路的尝试，对一条途径的
暗示。没有人曾经完全成为他自身；但是每个人都在努力变成他自身，有的人模
糊，有的人清醒一点，每个人都在尽自己的努力。

每个人和故事都是至关重要的、永恒的、神圣的，每个人只要他生活着，实现着
大自然的意志，他就是奇妙的、值得人人关注的，在每个人身上，精神变成了形
体，在每个人身上造物在忍受痛苦，在每个人的身上都有一个拯救者被钉在十字
架上。
你一直在光明世界里，但吸引着你的永远是黑暗世界。也许前面除了深不可测的黑暗什么都没有，每一步都是危险。但只有踏入黑暗世界并从中再爬起来，你才能走向自我。除此之外没有捷径。

我除了要想按照我内心自然产生的愿望去生活之外，别无他求，这为什么如此艰难？

因此，每个人的故事都是重要的、永恒的、神圣的,每个人只要他在生活着,实现着大自然的意志，他就是奇妙的、值得人人关注的，在每个人身上，精神变成了形体，在每个人身上造物在忍受痛苦，在每个人的身上都有一个拯救者被钉在了十宇袈上。

每个人的生活都是一条通向自身的道路，都是对一条道路的尝试，对一条途径的暗示。没有人曾经完全成为他自身；但是每个人都在努力变成他自身，有的人模糊，有的人清醒一点，每个人都在尽自己的努力。

只有当愿望完全在我自己心中，我的本质确实完全被愿望所充实，我才能把它付诸实施，才能抱着足够强烈的念头。一旦出现这种情况，一旦你按照内心对你发出的命令去尝试某件事情，那么事情就成了，

我把从黑暗势力那里收回的那部分生命献给了光明势力，我的目标不是情欲，而是纯洁，不是幸福，而是美和智慧。

贝雅特丽齐

命运和性情是一种概念的名称。"

在我们自身内有一个人什么都知道，什么都想要，什么都比我们自己做得更好

我不是生活在醉酒和污秽之中，生活在麻木和迷惘之中，直到正是我自身中的对
立面一一对纯洁的渴念，对神圣的向往以一种活力激昂起来吗？

"鸟从蛋里挣脱出来，蛋即世界。谁要想出生，就必须摧毁一个世界。鸟飞向上
帝。上帝叫阿卜拉克萨斯。"

欢乐和恐惧、男人和女人混合在一起，最神圣的和最卑劣的东西纠缠在一起，深
重的罪孽在最温柔的纯洁中闪光——这就是我的爱情梦幻，阿卜拉克萨斯也是这样。
爱情不再是我开初所惊恐不安地感觉到的那种象动物一样朦胧的情欲，也不再是
我献给贝雅特丽齐画像的内心虔诚的崇拜。爱情是两者兼而有之，两者兼而有之
或者还要多得多，爱情是寓于一体的天使形象和魔鬼、男人和女人，以及人和动
物，极善和极恶。我觉得自己必定会有这种经历，为此付出代价是我的命运，我
思念命运，害怕命运，但是它总是在这里，总是控制着我。

我除了要想按照我内心自然产生的愿望去生活之外，别无他求。这为什么如此艰
难？

我研究的始终是我，始终是我自我非常热切地渴望现在最终也能够过上一段生活，
把我内心的某些东西给予世界，与世界产生联系，并与之作出斗争。

如果急需某样东西的人觉得这是他必不可少的东西。那么他所遇到的就不是巧合，
而是他自己、他自己的热望和使命把他引过去的。

我喜欢听音乐，不过只喜欢听您弹的那种完全没有限制的音乐，从这种音乐中可
以感觉到有一个人震撼着天堂和地狱。我想我很喜欢这种音乐，因为它没有什么
道德说教，我寻找某些不是说教的东西。在道德说教中我始终只有痛苦。

每种宗教都是美好的。宗教是心灵，不管是用基督教圣餐还是去麦加朝圣,都一
样。"

凡是我们的心灵所希里的，都不可以害怕，不可以看作禁忌。"

如果我最终不能赢得这场斗争，如果我屈服下来，重新使自己陷入污浊，那么我
会比所有其他从未奋斗过的人都更坏。

对觉醒的人们来说,除了寻找自己，内心坚定起来,在自己的道路上摸索前进而不
管它通向何方这样一种责任之外，绝没有其他责任——这深深地震动了我,这是我
的这场经历的收获。

每个人的真正职业只有一个：走向自身。

他的事情是找到自己的命运，不是随便哪一个命运,并在内心充分享受它,完整而
不间断地享受它。其他一切都是不完整的，都是企图逃脱，都是逃回中庸的理想，
都是适应，是害怕自己的内心。

我不能这样一丝不挂地，孤独地站着，我也是一条可怜的、懦弱的狗，它需要些
许温暧和食物，有时想要感觉到它的同类的接近。

桌上放着几卷尼采的书。我跟他生活在一起，感受着他灵魂的孤独，嗅到了不断
驱赶着他的命运，跟他一起痛苦，并对曾经有过一位如此坚定不移地走自己的道
路的人而感到无比快乐。

**** 观感

** 列夫·托尔斯泰
*** 《安娜卡列尼娜》

**** 时间

- 1st :: 2016/01/05--2016/02/06

**** 摘录

幸福的家庭都是相似的，不幸的家庭各有各的不幸。

斯捷潘·阿尔卡季奇是一个忠实于自己的人。

她的衣服和姿态看上去都没有什么特别引人注目的地方，但是列文在人群中找出
她来，就好像在荨麻里找到蔷薇一样地容易。由于她，万物生辉。她是照耀周遭
一切的微笑。

因为现在我是幸福的，至少在希望上是幸福的……而以后呢？……但是我一定要，
我一定要，懦弱滚开吧！”

。他深知列文的那种感情，在他看来，世界上的少女应当分成两类：有一类——她
以外的全世界的少女，那些有着所有人类缺点的少女，最普遍的少女；另外一
类——她一个人，丝毫弱点都没有，而且超出全人类。

你是始终如一的。这是你的优点，也是你的缺陷。你有始终如一的性格，你要整
个生活也是始终如一的——但事实决不是这样。你轻视公务，因为你希望工作永远
和目的完全相符——而事实决不是这样。你还要每个人的活动都有明确的目的，恋
爱和家庭生活始终是统一的——而事实决不是这样。人生的一切变化，一切魅力，
一切美都是由光和影构成的

有些人，无论在什么事情上面，遇到成功的敌手的时候，马上就不睬他的一切优
点，只看到缺点。反之，也有些人，他们顶希望在幸运的敌手身上找出胜过自己
的特点，带着剧烈的创痛专门寻找长处。列文属于第二种人。

他不晓得他对基蒂的这种行为有一个特定的名称，那就是向少女调情而又无意和
她结婚，这种调情是像他那样风度翩翩的公子所共有的恶行之一。他以为他是第
一个发现这种快乐的，他正在尽情享受着他的发现。

，我不能埋怨谁，也没有什么好埋怨的。都是我自己不好。我有什么权利以为她
愿意和我结成终身伴侣呢？就是什么人，我算个什么？是一个谁都不需要、对于
谁都没有用处的一无可取的人呀。

他感到自在起来，不再作分外之想了。他现在唯一希望的就是要变得比从前更好
一些。第一，他下决心从此不再希望结婚能给予他罕有的幸福，因此也不再那么
轻视他现有的东西。第二，他再也不让自己沉溺于卑劣的情欲中，在他决心求婚
的时候，回想起过去的情欲曾经使他那么苦恼

不，你不会离开我们，你不会变成另外的样子，你还会和从前一样的：老是怀疑，
永远不满意自己，徒劳无益地妄想改革，结果总是失败，永远憧憬着你不会得到、
而且不可能得到的幸福。”

他十分明白他在贝特西或任何其他社交界人们的眼里并没有成为笑柄的危险。他
十分明白在他们心目中做一个少女或任何未婚女性的单恋者的角色也许是可笑的；
但是一个男子追求一个已婚的妇人，而且，不顾一切，冒着生命危险要把她勾引
到手，这个男子的角色就颇有几分优美和伟大的气概，而决不会是可笑的；

这在他看来是非常荒谬和不可思议的，因为这就是生活本身

而每一次他与现实发生冲突的时候，他就逃避现实。现在他体验到这样一种心情，
仿佛一个人泰然自若地走过深渊上的桥梁的时候，突然发觉桥断了，下面是无底
深渊

伪善不论在什么事情上也许可以欺骗最聪明最机灵的大人，但是最不灵敏的小
孩也能识破伪善，对它抱着恶感，不管它掩饰得多么巧妙。

他自言自语，极力想替自己把他在这短短的一夜里体会到的一切思想感情表达出
来。他所体会到的一切思想感情分成了三个不同的思路。一个是抛弃自己过去的
生活，抛弃自己的完全无用的学识和教育。这种抛弃会给与他快乐，而且对他说
来是简单容易的。另一类的思想和想像是有关他现在所渴望过的生活的。他明晰
地感觉到这种生活的单纯、纯洁和正当，而且深信他会在这种生活中寻找到他所
痛感缺乏的满足、平静和高尚品德。但是第三类的思想却围绕着怎样使旧生活转
变成新生活的问题。

在光明完全战胜黑暗的黎明将要来临之前，通常总有一个幽暗的顷刻。

。这就是基蒂。他明白了她正从火车站坐车到叶尔古绍沃去。在那不眠的一夜里
使列文激动不安的一切事情，他所下的一切决心，全都一下子烟消云散

，只要了解了你所爱的妻子，你就会比认识一千个女人的人更了解所有的女人。

人们争论得那么热烈，往往只是因为不能领会对方所要证明的事情。

他们为什么要辩论呢？您知道从来没有人能够说服谁。

结婚中的重要因素就是爱情，有了爱情，人总是幸福的，因为幸福全在自己身上。

我多么清楚会这样啊！我从来不敢这样希望；可是在我心里我却总是深信不疑的，

凡上帝要毁灭者，先使其疯狂

有人打你的右脸，连左脸也由他打；有人夺你的上衣，连衬衣也给他

他是幸福的，但是进入家庭生活以后，他处处看到这和他所想像的完全不同。他
处处感到这样一种心情，如同一个人叹赏湖上一叶小舟平稳而幸福地漂浮，等到
自己坐上小舟的时候心情就有些两样。他发现：这并不只是平稳地坐着，毫不摇
晃，人还得要思想，片刻不能忘记他要到什么地方去；而且下面还有水，人还得
划桨；他的不习惯划桨的手还会疼痛；只是看着容易，可是做起来的时候，虽说
是非常愉快，却也是很不容易啊。

独身的时候，他看见别人的婚后生活，看到他们的琐屑的忧虑、争吵、嫉妒的时
候，他往往只是在心里轻蔑地讥笑。在他未来的夫妻生活中，他相信决不会有这
种事情；就连他的结婚生活的外表形式，在他想来，也准会和别人的生活完全不
同。可是出乎意外，他和他妻子的生活不但没有独树一格，而且，恰好相反，完
全是由他以前那么轻视的极其琐碎的小事构成的，而现在，那些小事，违反他的
意愿，却具有了异乎寻常的、无可争辩的重要性。列文看到要把所有这些琐事安
顿好，完全不像他以前想像的那么容易。

他开始说话，竭力找话来与其说是说服她，不如说是安慰她。但是她不听他，随
便他说什么也不理睬。他弯下腰，拉住她那只在抗拒他的手。他吻她的手，吻她
的头发，又吻她的手——她却始终沉默着。但是当他用两手捧着她的脸，叫了声
“基蒂！”的时候，她突然恢复了镇静，哭了一会，于是他们就和好了

一切事情都难料呢，

一个家庭要采取任何行动之前，夫妻之间要么是完全破裂，要么是情投意合才行。
当夫妇之间的关系不确定，既不这样，又不那样的时候，他们就不可能采取任何
行动了。

他还模糊地意识到他所谓的那种信念不但是无知，而且还是那么一种思想方法，
靠这种思想方法要取得他所需要的知识是不可能的。

当列文想到他是什么和为什么活着的时候，他找不到答案，于是陷入悲观失望；
但是当他不再问自己这些问题的时候，他反倒好像知道他是什么和为什么活着了，
因为他坚决而明确地生活着和行动着；最近他甚至比以前更坚定明确得多了。

推究把他引入了疑惑之中，妨碍他看清他该做什么，不该做什么。但是当他不动
脑筋，只是这么活着的时候，他就不住地感觉到他的心灵里有一个绝对正确的审
判官，在评判那可能发生的两种行动，哪样好，哪样歹；而他刚一做了不该做的
事，他立刻就感觉到了

这种新的情感并没有使我有所改变，没有使我感到幸福，也没有像我梦想的那样
突然间使我大彻大悟，只是像我对我儿子的感情一样。这也没有什么出人意外的
地方。但就是信仰也罢，不是信仰也罢——我不知道这到底是什么呢，——这种情感
不知不觉地历尽痛苦产生了，在我心中牢固地扎下根来

我照样还会跟车夫伊万发脾气，照样还会和人争论，照样还会不合时宜地发表自
己的意见；在我心灵最神圣的地方和其他的人们，甚至和我的妻子之间仍然会有
隔阂；为了我自己的恐惧我还会责备她，并且还会因此感到后悔；我的理智仍然
不可能理解我为什么祈祷，但是我照样还会祈祷；但是现在我的生活，我的整个
生活，不管什么事情临到我的身上，随时随刻，不但再也不会像从前那样没有意
义，而且具有一种不可争辩的善的意义，而我是有权力把这种意义贯注到我的生
活中去的！”

**** 书评

- [[https://app.yinxiang.com/shard/s52/nl/11551545/eb2aab59-88a1-46e7-b834-0e953d4da6d7?title=%E5%A4%A7%E5%B8%88%E4%B8%8E%E5%8D%A1%E5%88%97%E5%AE%81%E5%A8%9C%20(%E8%AF%84%E8%AE%BA%3A%20%E5%AE%89%E5%A8%9C%C2%B7%E5%8D%A1%E5%88%97%E5%AE%81%E5%A8%9C)][大师与卡列宁娜]]
- [[https://app.yinxiang.com/shard/s52/nl/11551545/aac81858-4715-49a4-b6a9-0ad5d113526d?title=%E7%95%99%E5%9C%A8%E6%88%91%E5%BF%83%E5%BA%95%E7%9A%84%E4%BA%BA%20(%E8%AF%84%E8%AE%BA%3A%20%E5%AE%89%E5%A8%9C%C2%B7%E5%8D%A1%E5%88%97%E5%B0%BC%E5%A8%9C)][留在我心底的人]]

**** 观感

*2016/02/06*

02/02 到 02/06 四天读完了 98%
极其喜欢列文和基蒂的爱情，也同情安娜。 --

** 王阳明

*** 《传习录》
**** 时间

- 1st :: ??

**** 摘录

心即理也

未有知而不行者。知而不行，只是未知。

见好色属知，好好色属行。只见那好色时已自好了，不是见了后又立个心去好，
闻恶臭属知，恶恶臭属行。只闻那恶臭时已自恶了，不是闻了后别立个心去恶。

。知行如何分得开？此便是知行的本体，不曾有私意隔断的。

某尝说知是行的主意，行是知的功夫。知是行之始，行是知之成。若会得时，只
说一个知，已自有行在。只说一个行，已自有知在

今人却就将知行分作两件去做，以为必先知了，然后能行。我如今且去讲习讨论
做知的工夫，待知得真了，方去做行的工夫。故遂终身不行，亦遂终身不知。此
不是小病痛，其来已非一日矣。某今说个知行合一，正是对病的药，又不是某凿
空杜撰。知行本体原是如此。今若知得宗旨时，即说两上亦不妨，亦只是一个。
若不会宗旨，便说一个，亦济得甚事？只是闲说话

但意念所在，即要去其不正，以全其正，即无时无处不是存天理，即是穷理。天
理即是明德，穷理即是明明德

知是心之本体，心自然会知。见父自然知孝，见兄自然知弟，见孺子人井自然知
恻隐。此便是良知，不假外求。若良知之发，更无私意障碍，即所谓充其恻隐之
心，而仁不可胜用矣。然在常人，不能无私意障碍，所以须用致知格物之功，胜
私复理。即心之良知更无障碍，所以充塞流行，便是致其知。知致则意诚。”

好色则一心在好色上，好货则一心在好货上，可以为主一乎？是所谓逐物，非主
一也。主一是专主一个天理。

日间工夫觉纷扰，则静坐。觉懒看书，则且看书。是亦因病而药。

此是汝一生大病根。譬如方丈地内，种此一大树，雨露之滋，土脉之力，只滋养
得这个大根。四傍纵要种些嘉谷，上面被此树树叶遮覆，下面被此树根盘结，如
何生长得成？须用伐去此树，纤根勿留，方可种植嘉谷。不然，任汝耕耘培壅，
只是滋养得此根

人须在事上磨，方立得住，方能静亦定，动亦定。

夫目可得见，耳可得闻，口可得言，心可得思者，皆下学也；耳不可得闻口号不
可得言，心不可得思者，上达也。如木之栽培灌溉，是下学也；至于日夜之所息，
条达畅茂，乃是上达。人安能预其力哉？故凡可用功，可告语者，皆下学。上达
只在下学里。凡圣人所说，虽极精微，俱是下学。学者只从下学里用功，自然上
达去，不必别寻个上达的工夫。

惟一是惟精主意，惟精是惟一功夫，非惟精之外复有惟一也

只要去人欲、存天理，方是功夫。静时念念去人欲、存天理，动时念念去人欲、
存天理，不管字静不字静。若靠那字静，不惟渐有喜静厌动之弊，中间许多病痛，
只有潜伏在，终不能绝去，遇事依旧滋长。以循理为主，何尝不字静？以字静为
主，未必能循理。

立志用功，如种树然。方其根芽，犹未有干；及其有干，尚未有枝，枝而后叶，
叶而后花、实。初种根时，只管栽培灌，勿作枝想，勿作叶想，勿作花想，勿作
实想。悬想何益？但不忘栽培之功，怕没有枝叶花实？”

岂有邪鬼能迷正人乎？只此一怕，即是心邪，故有迷之者。非鬼迷也，心自迷耳。
如人好色，即是色鬼迷；好货，即是货鬼迷；怒所不当怒，是怒鬼迷；惧所不当
惧，是惧鬼迷也。”“定者，心之本体，天理也。动静，所遇之时也。

道无方体，不可执著。欲拘滞于文义上求道，远矣。如今人只说天，其实何尝见
天？谓日、月、风、雷即天，不可；谓人、物、草、木不是天，亦不可。道即是
天。若识得时，何莫而非道。人但各以其一隅之见，认定以为道止如此，所以不
同。若解向里寻求，见得自己心体，即无时无处不是此道。亘古亘今，无终无始，
更有甚同异？心即道，道即天。知心则知道、知天。”又曰：“诸君要实见此道，
须从自己心上体认，不假外求，始得

在一时一事，固亦可谓之中和。然未可谓之大本、达道。人性皆善。中、和是人
原有的，岂可谓无？但常人之心既有所昏蔽，则其本体虽亦时时发见，终是暂时
暂灭，非其全体大用矣。无所不中，然后谓之大本；无所不和，然后谓之达道。
惟天下之至诚，然后能立天下之大

在一时一事，固亦可谓之中和。然未可谓之大本、达道。人性皆善。中、和是人
原有的，岂可谓无？但常人之心既有所昏蔽，则其本体虽亦时时发见，终是暂时
暂灭，非其全体大用矣。无所不中，然后谓之大本；无所不和，然后谓之达道。
惟天下之至诚，然后能立天下之大本。” 曰：“澄于中字之义尚未明。” 曰：
“此须自心体认出来，非言语所能喻

在一时一事，固亦可谓之中和。然未可谓之大本、达道。人性皆善。中、和是人
原有的，岂可谓无？但常人之心既有所昏蔽，则其本体虽亦时时发见，终是暂时
暂灭，非其全体大用矣。无所不中，然后谓之大本；无所不和，然后谓之达道。
惟天下之至诚，然后能立天下之大本。” 曰：“澄于中字之义尚未明。” 曰：
“此须自心体认出来，非言语所能喻

毕竟从好色、好利、好名等根上起，自寻其根便见。如汝心中决知是无有做劫盗
的思虑，何也？以汝元无是心也。汝若于货、色、名、利等心，一切皆如不做劫
盗之心一般，都消灭了，光我只是心之本体，看有甚闲思虑？此便是寂然不动，
便是未发之中，便是廓然大公。自然感而遂通，自然发而中节，自然物来顺应

毕竟从好色、好利、好名等根上起，自寻其根便见。如汝心中决知是无有做劫盗
的思虑，何也？以汝元无是心也。汝若于货、色、名、利等心，一切皆如不做劫
盗之心一般，都消灭了，光我只是心之本体，看有甚闲思虑？此便是寂然不动，
便是未发之中，便是廓然大公。自然感而遂通，自然发而中节，自然物来顺应

毕竟从好色、好利、好名等根上起，自寻其根便见。如汝心中决知是无有做劫盗
的思虑，何也？以汝元无是心也。汝若于货、色、名、利等心，一切皆如不做劫
盗之心一般，都消灭了，光我只是心之本体，看有甚闲思虑？此便是寂然不动，
便是未发之中，便是廓然大公。自然感而遂通，自然发而中节，自然物来顺应。”

毕竟从好色、好利、好名等根上起，自寻其根便见。如汝心中决知是无有做劫盗
的思虑，何也？以汝元无是心也。汝若于货、色、名、利等心，一切皆如不做劫
盗之心一般，都消灭了，光我只是心之本体，看有甚闲思虑？此便是寂然不动，
便是未发之中，便是廓然大公。自然感而遂通，自然发而中节，自然物来顺应

中国禅宗中有顿悟与渐悟之分,二者的代表人物是六祖惠能和上座神秀。两人都
是五祖弘忍大师的弟子。一天,弘忍要求弟子每人都呈上一首偈子,看谁真正悟了
谁就成为祖师衣钵传的第六代继承人。上座神秀呈上的偈语说:“身是菩提树,心
如明镜台,时时勤拂拭,勿使惹尘埃。”而一字不识的惠能闻听此偈后,即请人代
笔也题上一偈,曰:“菩提本无树,明镜亦非台,本来无一物,何处惹尘埃?”弘忍看
了二人的偈语后,竟然将祖师衣钵传给了惠能。从此,神秀和惠能各分南北,形成
南顿北渐,两者互相交流,共同弘扬禅宗一脉。

知之真切笃实处即是行,行之明觉精察处即是知。

**** 观感

** 西方文学
*** 《简爱》  夏洛蒂·勃朗特

**** 时间

- 1st :: 2013/09/07--2013/09/20

**** 摘录

**** 观感

*** 《呼啸山庄》  艾米莉·勃朗特

**** 时间

- 1st :: 2013/10/10--2013/10/26

**** 摘录

**** 观感

*** 《了不起的盖茨比》  司各特·菲茨杰拉德

**** 时间

- 1st :: 2015/01/01--2015/01/04

**** 摘录

***** 人物

- 尼克.卡拉威： 美国西部中产阶级子弟，战后到东部做票券生意。
- 盖茨比： 尼克的邻居
- 黛西： 尼克的表妹
- 汤姆.布坎恩：黛西的丈夫，同事尼克的大学旧识
- 乔丹.贝壳：黛西的女友

***** 第一章

/每当你要批评什么人的时候，你切要记着，并非这个世界上的所有人都具备你
所具有的条件。/

从此我总是倾向于对事不妄做任何评断。

草坪从海岸边起始到房屋的前门有四分之一英里长，期间越过了日晷、铺砖的便
道和鲜花盛开的花园——最后当它抵达屋前时又以鲜绿的藤蔓沿着墙壁攀缘上去，
好像是它一路疾跑的动力使它一跃而起一般。

她舒服地躺在沙发的一端，一动也不动，她的下巴微微地翘起了一点儿，好像是
在维持着她下巴上一块快要掉下来的什么东西的平衡。

这是那种不由得人们不去竖起耳朵倾听的音调，好像她的每一句话都是一组你终
身再也难以听到的优美旋律。

此时，太阳的最后一抹余晖带着诗情和爱恋照在她娇艳的脸庞上。她那动人的声
音吸引着我倾着身子屏息地聆听——接着余晖消失了，条条光束不无遗憾地离开了
她，那依依不舍就像是顽童在黄昏时不忍丢下热闹的街市而离去一样。

这时，风已经不再刮了，夜空显得明净而大地上却是万籁齐鸣，连树林里也不断
有鸟儿拍动翅翼的声音——宛如大地上的风箱一齐拉响，把青蛙吹得鼓噪起来。

他奇怪地朝着黑漆漆的海水伸开他的双臂，尽管我不在近前，可是我敢发誓他正
在颤抖。我不由得也向海边望去——什么也看不见，除了孤零零的绿色灯火，那么
微小那么遥远，也许在一个码头的最最边缘处。

**** 观感

*** 《麦田的守望者》  塞林格

**** 时间

- 1st :: 2015/07/03

**** 摘录

**** 观感

*** 《一九八四》  奥威尔

**** 时间

- 1st :: 2015/08/25

**** 摘录

**** 观感

*** 《在路上》  杰克·凯鲁亚克

**** 时间

- 1st :: 2015/09/01

**** 摘录

**** 观感

*** 《人生的枷锁》 毛姆

**** 时间

- 1st :: 2015/10/01

**** 摘录

**** 观感

** 古典文学
*** 《西游记》

**** 时间

- 1st :: 2013/11/08--2014/01/20

**** 摘录

**** 观感

*** 《肉蒲团》  李渔

**** 时间

- 1st :: 2015/09/05

**** 摘录

**** 观感

*** 《老子》 李耳

**** 时间

- 1st :: 2015/12/01--2015/12/20
     简要迅速地读过一遍，为侄女起名字。有待重读。

**** 摘录

此处所讲的“无为”不是无所作为，随心所欲，而是要以辩证法的原则指导人们
的社会生活，帮助人们寻找顺应自然、遵循事物客观发展的规律

“相反相成

朴素的辩证法，是老子哲学中最有价值的部

他既不讲人性善，也不讲人性恶，而是说人性本来是纯洁素朴的，犹如一张白纸。
如

为腹不为目：只求温饱安宁，而不为纵情声色之娱。"腹"在这里代表一种简朴宁
静的生活方式；"目"代表一种巧伪多欲的生活方式。

日出而作，日入而息。凿井而饮，耕田而食。帝力于我何有哉？

上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。不笑不足以为
道。

道生一①，一生二②，二生三③，三生万物。万物负阴而抱阳④，冲气以为和⑤。

祸莫大于不知足；咎莫大于欲得。

祸兮，福之所倚；福兮，祸之所伏。

图难于其易，为大于其细；天下难事，必作于易；天下大事，必作于细

**** 观感

*** 《诗经》

**** 时间

- 1st :: 2015/12/24--2015/12/26
     概要地扫描了一遍，找到了给侄女起名字的灵感。

**** 摘录

《诗经》共三百零五首，简称“诗三百”。按其内容，可分为“风”、“雅”、
“颂”三类。“风”乃风土之曲，即民间歌谣，共一百六十篇，总称为十五国风。
“雅”乃朝廷之乐，多为京都一带朝廷官吏的作品，共一百零五篇，分为《大雅》
和《小雅》。“颂”乃庙堂之音，是王侯举行祭祀或其他重大典礼专用的乐歌，
共四十篇，分为《周颂》、《鲁颂》、《商颂》，合称三颂。

。读《诗经》，重在读、贵在读、趣在读。

关关雎鸠，在河之洲。窈窕淑女，君子好逑。 参差荇菜，左右流之。窈窕淑女，
寤寐求之。 求之不得，寤寐思服。悠哉悠哉，辗转反侧。 参差荇菜，左右采之。
窈窕淑女，琴瑟友之。 参差荇菜，左右芼之。窈窕淑女，钟鼓乐之。

桃之夭夭，灼灼其华。之子于归，宜其室家。 桃之夭夭，有蕡有实。之子于归，
宜其家室。 桃之夭夭，其叶蓁蓁。之子于归，宜其家人。

我心匪石，不可转也。我心匪席，不可卷也。

“死生契阔”，与子成说。执子之手，与子偕老。

契：合。阔：疏。“契阔”在这里是偏义复词，偏用“契”义。

投我以木瓜，报之以琼琚。匪报也，永以为好也。 投我以木桃，报之以琼瑶。
匪报也，永以为好也。 投我以木李，报之以琼玖。匪报也，永以为好也。

彼黍离离，彼稷之苗。行迈靡靡，中心摇摇。知我者谓我心忧，不知我者谓我何
求。悠悠苍天！此何人哉？ 彼黍离离，彼稷之穗。行迈靡靡，中心如醉。知我
者谓我心忧，不知我者谓我何求。悠悠苍天！此何人哉？ 彼黍离离，彼稷之实。
行迈靡靡，中心如噎。知我者谓我心忧，不知我者谓我何求。悠悠苍天！此何人
哉？

**** 观感
** 艺术
*** 《西方美学史》 朱光潜

**** 时间

- 1st :: 2013/09/21--2013/09/10

**** 摘录

**** 观感

** 心理
*** 《内向者优势》

**** 时间

- 1st :: 2015/01/01

**** 摘录

***** 序

#+BEGIN_QUOTE
幸福快乐的首要之点就在于一个人愿意成为他自己。 by Erasmus
#+END_QUOTE

***** 前言

#+BEGIN_QUOTE
没有那些具有创造性的少数人的引导，民主是不可能存在的。 by Harlan.F. Stone
#+END_QUOTE

性格内向与性格外向的人在数量上大约是 /一比三/ 。

内向和外向处于能量连续体的相反的两端。我们落入那连续体的什么位置，就决
定了我们获得自己生活精力的方式。处于连续体的偏内向那一端的人倾向于向内
以获得精力，而处于连续体的偏外向那一端的人倾向于向外以获得精力。

每一个个性都有积极的方面，只是彼此有一些不同。

内向和外向的人会受到相反一方的吸引，以帮助加强和实现我们每个人所缺少的
成分，这是我们欣赏彼此互补的一种自然发展的方式。

#+BEGIN_QUOTE
安静的人们常常具有深刻的洞察力。浅浅的溪流或河水奔流迅速，较深的水域似
乎较为平静。 by James Rogers
#+END_QUOTE

- 性格内向的人对任何问题都认为其高深莫测。
- 他们都有大脑空白的体验，所以为了避免那可怕的大脑一片空白的时刻，他们
  尽可能多的收集各种各样的信息来做准备。
- 因为他们常常不与人谈论自己的所思所想，所以他们不会得到任何的返回来帮
  助自己了解自己究竟知道了多少东西。

#+BEGIN_QUOTE
没有任何东西像书这么迷人。 by Sydney Smith
#+END_QUOTE

***** 第一章

性格内向从本质上讲是一种个性特征。它与害羞和具有孤僻的性格特征不同，与
疾病无关。

它不是能被改变的事物，但是你可以学着利用它，而不是对抗它。

性格内向最显著的特征是他们精力的来源：从他们的内在世界，如思想，情绪和
观念中获得精力。

性格内向的人需要限制自己的社会交往，以免被弄得精疲力竭。同时，需要对独
处的时间和在外界活动的时间加以平衡，否则会失去很多的机会和人际关系。

精力平稳的性格内心之人具有独立思考、高度集中注意力、创造性工作的毅力和
能力。

****** 性格内向和性格外向的区别

1. 精力的回复

   性格外向的人可以通过与外部世界的互动而非常容易地使自己恢复精力。

   性格内向的人从自己的内部世界——如思想、观念和情绪中获得精力。

   在如今生活节奏变快的社会里，对性格内向的人来说，需要用比性格外向的
   人更多的时间来恢复精力，而精力的消耗却又比性格外向的人更快。

   因此，性格内向的人需要计算某件事情将消耗多少精力，他们需要保存多少
   精力，并相应地加以计划。

2. 对刺激的反应

   性格外向的人喜欢体验大量的外部刺激，而性格内向的人喜欢对自己体验的
   事物了解较多。

   性格内向的人有很高的内心活动水平，从外部世界进入其大脑的任何事物都
   会使他们的紧张水平迅速提高。这有点向挠痒——感觉开始是美妙并且有趣，
   但很快就变成了令人不舒服的“刺激太多”的感觉。

   所以，如何对刺激过多的体验加以管理，是一个问题！

   性格内向的人通常在没有意识到为什么的时候就试图整理有限的外部刺激所
   带来的体验。

   当性格内向的人在学习时，他们可能接受很多的信息而感到压力太多。

3. 知识和经验的接近方式

   性格外向的人在积累知识和经验时，一般会将网撒得很开，而性格内心的人
   喜欢进行窄一点、深入一点的研究。

   性格外向的人喜欢宽度——许多的朋友和经验，对任何事情都知晓一点，是一
   个通晓多方面知识的人。对他们来说，生活就是积累经验。他们想抓住生活
   中每一点能抓住的刺激。

   多样性是刺激和精力的源泉。

   性格内向的人喜欢深度，他们限制从外部进入的经验，但对每一经验都体验
   较深。他们通常只有较少的朋友，但与这些朋友的关系都比较亲密。他们喜
   欢深入钻研问题，对某一问题深入性的探讨甚于宽泛性的追寻。这就是为什
   么很有必要将他们思考的问题限制为一个或两个，否则他们会感到压力太大
   的原因。他们从外部世界吸收信息，思考它并发展它。而且他们会在获取这
   些信息很久之后还再次思考它——这有点像牛反？食物。

   要将性格内向的人从集中精力的思考中拉出来是件很困难的事情，他们想要
   再次达到那种集中精力的状态要花费大量额外的精力，而这些额外的精力往
   往是他们所不具备的。

****** 性格内向的优势

- 高度集中注意力的能力
- 对每一个相关人员因变化而受到影响的体会
- 观察力
- 拜托限制
- 思考问题的习性
- 做出不同寻常决定的意志力
- 使外界放缓脚步的潜力

**** 观感

*** 《发现未知的自己:CBT改变生活》

**** 时间

- 1st :: 2015/02/25--2015/03/05

**** 摘录

**** 观感

*** 《爱的艺术》 弗洛姆

**** 时间

- 1st :: 2016/02/06--2016/02/08

**** 摘录

爱情不是一种与人的成熟程度无关，只需要投入身心的感情

如果爱是一门艺术，那就要求人们有这方面的知识并付出努力。或

在一个商业化占统治地位以及把物质成功看得高于一切的文化中，事实上是没有
理由对下列事实抱有吃惊的态度：人与人之间的爱情关系也遵循同控制商品和劳
动力市场一样的基本原则。

产生在爱这件事上一无可学这一看法的第二个原因是人们认为爱的问题是一个对
象问题，而不是能力问题。

但他们之中没有人认为，人们本可以学会去爱。 　　他们之所以持有这种特殊
态度是有其各种原因的，这些原因反过来又分别地或总和地加强了他们的这一态
度。大多数人认为爱情首先是自己能否被人爱，而不是自己有没有能力爱的问题

产生在爱情这件事上一无可学这一看法的第三个错误是人们不了解“堕入情网”
同“持久的爱”这两者的区别。如果我们用falling in love和being in love这
两个英文搭配也许就能更清楚地区分这两个概念。

要认识爱情是一门艺术。人们要学会爱情，就得像学其他的艺术——如音乐，绘画，
木工或者医疗艺术和技术一样的行动。

，除了学习理论和实践外还有第三个必不可少的因素，即要把成为大师看得高于
一切，这一目标必须占据他整个身心。

人的存在的根本要点是人超越了动物界，超越了本能的适应性，脱离了自然——尽
管人永远不可能完全脱离自然。

人——所有时代和生活在不同文化之中的人——永远面临同一个问题，即：如何克服
这种孤独感，如何超越个人的天地，实现人类的大同。

在某种程度上性纵欲是克服孤独感的一种自然和正常的方式，并有部分效果。许
多不能用其他的方式减轻孤独感的人很重视性纵欲的要求，实际上这和酗酒和吸
毒并无多大区别。有些人拼命地想借性纵欲使自己克服由于孤独而产生的恐惧感，
但其结果只能是越来越孤独，因为没有爱情的性交只能在一刹那间填补两个人之
间的沟壑。

同共生有机体结合相对立的是成熟的爱情，那就是在保留自己完整性和独立性的
条件下，也就是保持自己个性的条件下与他人合二为一。

爱情可以使人克服孤寂和与世隔绝感，但同时又使人保持对自己的忠诚，保持自
己的完整性和本来的面貌。

。如果一个人是在积极的情绪支配下行动，他就是自由的，是情绪的主人。如果
他是被一种消极的情绪所支配，那他就是受外力驱使者，是他自己都不了解的动
机的对象

爱情是一种积极的，而不是消极的情绪。一般来说可以用另一个说法来表达，即
爱情首先是给而不是得。

有没有能力把爱情作为一种给的行为取决于人的性格发展，这一事实似乎没有必
要加以强调了。取得这一能力的先决条件是人要有一种占主导地位的生产性倾向

爱情的积极性除了有给的要素外，还有一些其他的基本要素。这些要素是所有爱
的形式共有的，那就是：关心、责任心、尊重和了解。

爱情是对生命以及我们所爱之物生长的积极的关心。如果缺乏这种积极的关心，
那么这只是一种情绪，而不是爱情。

，爱的本质是创造和培养，爱情和劳动是不可分割的。

关心和关怀还包括爱情的另一方面，即责任心。今天人们常常把责任心理解为是
义务，是外部强加的东西。但是责任心这个词的本来意义是一件完全自觉的行动，
是我对另一个生命表达出来或尚未表达出来的愿望的答复。“有责任”意味着有
能力并准备对这些愿望给予回答

如果爱情没有第三个要素：尊重，那责任心就很容易变成控制别人和奴役别人

。尊重这个词的出处就是有能力实事求是地正视对方和认识他独有的个性。尊重
就是要努力地使对方能成长和发展自己，因此尊重决无剥削之意。

只有当我自己达到独立，在没有外援的情况下独立地走自己的路，即不想去控制
和利用别人，只有在这种情况下，尊重对方才成为可能。只有在自由的基础上才
会有 　　爱情，

人们只有认识对方，了解对方才能尊重对方。如果不以了解为基础，关心和责任
心都会是盲目的，而如果不是从关怀的角度出发去了解对方，这种了解也是无益
的。了解的方式多种多样。成为爱情一要素的了解是要深入事物

我只有用他人的眼光看待他人，而把对自己的兴趣退居二位。我才能了解对方

我们永远不可能靠智力来了解人和宇宙的秘密，但可以通过爱情去把握它。心

成熟的人只想拥有他自己的劳动果实，放弃了获取全力和全知的自恋幻想，并有
一种谦恭的态度。这一态度的基础是他内心的力量，单单这股力量就能使他进行
真正的、创造性的劳动。

天真的、孩童式的爱情遵循下列原则：“我爱，因为我被人爱。”成熟的爱的原
则是：“我被人爱，因为我爱人。”不成熟的、幼稚的爱是：“我爱你，因为我
需要你”，而成熟的爱是：“我需要你，因为我爱你。”

爱首先不是同一个特殊的人的关系，而更多的是一种态度，性格上的一种倾向。
这种态度决定一个人同整个世界，而不是同爱的唯一“对象”的关系。如果一个
人只爱他的对象，而对其他的人无动于衷，他的爱就不是爱，而是一种共生有机
体的联系或者是一种更高级意义上的自私

一切爱的形式都以博爱为基矗我指的博爱就是对所有的人都有一种责任感，关心、
尊重和了解他人，也就是愿意提高其他人的生活情趣。

利己者眼里只有自己，总是按照对自己是否有利的标准来判断一切人和一切事物，
他们原则上没有爱的能力

悖论逻辑的导师认为人只有在现实的矛盾中才能感觉现实，人永远无法在思想上
把握最终实体，把握宇宙。

爱情不是性满足的结果，而是性的幸福，甚至掌握所谓的性技巧也是爱情的结果。

。这要爱情是一个白日梦，他们就能加入进来，但如果爱情成为两个真实的人之
间的一种现实关系——他们就僵化了。

。现在人不是生活在过去就是生活在未来，但不是现时。

。现在人不是生活在过去就是生活在未来，但不是现时。他们满怀感伤地回忆童
年和母亲——或者为未来制定伟大的计划。不管是通过参与别人的非真正的爱情经
历来体验爱情，还是通过吧现时推移到过去和未来的方法来躲避爱情的现实，这
些抽象的和异化的爱情形式其作用就和鸦片一样，都是为了减轻现实、人的孤独
和与世隔绝所带来的痛苦。

。有些人对他人的每一个细微错误的反应都十分灵敏，而对自己的问题和弱点却
不闻不问，他们永远是在考虑如何指责对方或者教育对方。

。按“在任何情况下都应避免痛苦和悲伤”的世俗之见，所以现代人也认为，爱
情就是意味着没有冲突。他们还以他们所见之争吵都是毁灭性的争论，对双方都
没有好处的事实作为理论依据。但是真正的原因在于大多数人的“冲突”实际上
都是为了避免真正的冲突。这些冲突只是对一些鸡毛蒜皮的小事产生分歧而已，
而这些小事按其本质来看是无法澄清或者无法解决的。但人与人之间的真正冲
突——那些不应该被遮掩，也不应该投射到别处的冲突，那些属于人的内在现实并
能在人的心灵深处体验到的冲突——绝不是毁灭性的。这些冲突会得到澄清，会带
来一种净化，从而是双方能变得更有知识，更坚强。

爱情只能产生于这样两个人中间，这两个人都从他们生存的圈子里跳出来并互相
结合，同时他们每个人都又能脱离自我中心去体验自己。只有这种“中心体验”
才是人的现实，才是生活，才是爱情的基础。这样体验到的爱情是不断地挑战，
这种爱情不是避风港，而是一种共同的努力、成长和劳动

爱情的存在只有一个证明：那就是双方联系的深度和每个所爱之人的活力和生命
力。这也是我们所能看到的爱情的唯一成果。

除了进行实践外，难道可以从纸上了解一些有关实践爱的艺术的问题吗？

首先要求有纪律。如果没有纪律，我将会一事无成。如果我是凭一时的“兴致”
去行事，这也许会成为使我感到愉快的一种嗜好，但我永远成不了大师

集中是掌握艺术的一个必要条件，这一点是无需证明的了。每一个试图学会一门
艺术的人都了解这一点

第三个因素是耐心。学过艺术的人都值得要达到目的就必须要有耐心。想尽可能
快的取得结果的人永远也学不会一门艺术。

学会一门艺术还有另一个条件那就是对掌握这门艺术要有极大的兴趣

在谈及学会一门艺术的一般条件时还必须提及一点，那就是人们从来不是一开始
就直接地学会一门艺术，而总是间接地学会这门艺术。

为了使自己成为一门艺术的大师，必须把一生献给这门艺术。在实践这门艺术时，
自己要成为工具并保持一定的状态，以适应需要完成的任务。这一点在实践爱的
艺术上就意味着所有想成为大师的人应该把生活的每一个阶段训练纪律、集中和
耐心作为实践爱的艺术的开端。

那么如何训练纪律呢？我们的爷爷辈能更好地回答这一问题。他们会建议我们早
起，不要过奢华的生活，要努力工作。

每天早晨按时起床，按时进行一定的活动，如禅坐、看书、听音乐和散步，不做
或者有限度地做一些分散注意力的是如看侦探小说和电影，不暴饮暴食——这些都
是明显的基本要求。

每天早晨按时起床，按时进行一定的活动，如禅坐、看书、听音乐和散步，不做
或者有限度地做一些分散注意力的是如看侦探小说和电影，不暴饮暴食——这些都
是明显的基本要求。但是最重要的是不要把纪律看作是外部强加的东西，而应该
成为自我意志的体现，应该感到这是一种愉快，并且逐渐习惯于一种生活态度，
一旦放弃它，便会若有所思

，与身心有益的东西必定使人舒适，即使开始的时候需要克服一定的阻力。

。最重要的步骤是要学会一个人单独呆着，而且不看书，不听广播，不抽烟和不
喝酒。有没有集中的能力表现在能不能单独地呆着——而这种能力

最重要的步骤是要学会一个人单独呆着，而且不看书，不听广播，不抽烟和不喝
酒。有没有集中的能力表现在能不能单独地呆着——而这种能力优势学会爱的一个
条件

，他在思考工作中遇到的困难或者是考虑今天晚上上哪里去。但是做一些简单的
练习就能帮助他集中，譬如：轻松地坐着（即不要懒散，也不要紧张），把眼睛
闭上，努力使自己的眼前出现一片白色，并排除一切干扰自己的画面和念头。然
后可试着观察自己的呼吸——不要去想它，也不要去影响它，而只是要意思到自己
在呼吸

。除这些练习外还有学会专心做一切事：专心听音乐、看书、谈话或欣赏图画。
如果专心地干，那么干什么就无关紧要了，无论干什么，重要的或者不重要的都
会增加一层现实意义，因为干事的人是完全开放的。

在同别人的关系中要记住首先就意味着要有听别人讲话的能力。

每一件聚精会神完成的事会使人清醒（尽管干完时候出现能恢复的自然疲劳状
态）。而懒懒散散的干事只能使人产生倦意——

集中意味着要完全地在现时地生活，而不是赶着这事想那事

如果人们不知道学会每一种事都要有一个过程，都应自己给自己施加压力，那就
永远不会学会集中

有孩子学走路的耐心和集中他会作出多么大的成绩啊！

集中还要求另一样东西，那就是对自己要保持清醒

我们也可以以同样的方式清醒地面对自己。譬如在感觉到累或者消沉的时候，不
应该听之任之和用随时可以捡来的消沉的想法去加剧这种感受，而应该问问自己：
到底发生了什么？为什么我那么一蹶不振？同样在我们生气或者迷惑不解的时候，
在我们开始想入非非的时候，都应该这样问自己。在所有这种情况下，终于的是
要觉察内心的活动，而不是用各种各样的方法去找到为自己辩护的借口。这样我
们就此次会听到内心的一种声音，在向我们讲述，为什么会害怕、消沉或者迷惑
不解。一般人对自己体内的活动都有一定的警觉性；能感觉到每种变化和甚至能
发现几乎感觉不到的疼痛。注意身体的变化是比较容易做到的，因为大多数人都
了解自己的健康状态。

根据我对爱情本质的论述，获得爱的能力的主要条件是克服自恋。自恋倾向是人
的一种态度，具有这种态度的人体验到底现实只是内心活动，主要是他们自己的
贪婪和恐惧，对他们来说，外部世界的现象本身是不现实的，只有对他们有利或
者威胁他们的食物才有意义。同自恋相反的是客观性，客观性就是对人和事物吧
友开放的态度，能实事求是地看待事物。这个意义上的客观性就是能从表面深入
现象核心的实现主义。同自恋相反，客观性的基础不是与外部世界毫无关系，而
是由强烈的联系

能进行客观思考的能力就是理智，以理智为基础的感情是谦恭。我们只有摆脱了
童年时代妄图得到全知、全能的幻想，才能有客观性和运用自己的理智。

爱的能力取决于我们本人成熟的程度，以及在我们同世界和同自己的关系中能不
能发展一直创造性的倾向。这种脱离自己的过程、诞生和成熟的过程需要另一种
品质作为必不可少的条件：那就是信仰。爱情是以信仰为基础的。

信仰是否同理智和理性的思考对立？

我理解的非合理的信仰是指服从一种非理性权威的信仰（信仰一个人或者一种思
想）。与此相反，合理的信仰是扎根于自己思想或感情体验的一种坚定的信念。
合理的信仰首先不是信仰什么东西，而是一种确认，这种确认是符合建筑在自己
真实经历上的坚定的信念。信仰是全部人格的一个性格特点，而不是同某些被看
作为对的思想内容有关的东西。合理的信仰牢牢扎根于创造性的智力和情感的积
极活动

不合理的信仰意味着只相信权威或大多数人的意见，而合理的信仰是产生一种独
立的信念，相信自己创造性的观察和思考——尽管大多数人的看法与之不同。

在爱情方面，就是要把相信自己的爱情并相信这种爱情能唤起别人的爱以及相信
这种爱的可靠性看作是爱情的基本条件

在一定的条件下，人类有能力建立一个以平等、正义和爱为原则的社会制度。迄
今为止人类没有做到这一点，所以就需要有深信人类能做到这一点的信仰。但是
同每一种理性的信念一样，这一信仰绝不是相信会出现奇迹；它更多的是以迄今
为止的人类历史为基础，以及每个人的内心经历、对理智和爱的体验为基础。

培养自己的信仰和勇气可以从日常生活的点滴小事做起。第一个步骤就是要认识
到在什么时候和什么地方失去信仰，要看穿用来辩护失去信仰的各种借口和要认
识到什么地方胆怯了并找了哪些辩解的借口；另外还要认识到每一次的自我欺骗
指挥消弱自己，而越来越软弱又会导致新的自我欺骗，如此恶性循环，一直到人
没有信仰为止

另外一种与实践爱的艺术不可分割的态度是积极的活动。

爱情是一项积极的活动，如果我爱，我对所爱之人就抱有积极的态度，而且还不
限于对他（她）。

有些人认为可以把自己的生活分为两个部分，这样在爱情的范畴可以有创造性，
而在其他的范畴就不需要有创造性，这种想法只是一种幻想。生产力的本质决定
了不会有这样的分工

如果爱上一种性格特点，那么爱必须不仅仅出现在我们对自己家庭和朋友的关系
中，也必然能在同与我们的工作、职业有关的人的关系中找到。在我们对我们家
人的爱和对陌生人的爱之间是没有“分工”的。相反，对陌生人的爱是对家人爱
的前提。

“己所不欲，勿施于人”的准则被解释为是“要公正地同别人做生意”。

**** 观感
** 社会
*** 《寂静的春天》

**** 时间

- 1st :: 2015/03/17--2015/04/03

**** 摘录

**** 观感

*** 《如何阅读一本书》

**** 时间

- 1st :: 2016/02/23--

**** 摘录

**** 书评

**** 观感
** 历史
*** 《明朝那些事儿》  当年明月

**** 时间

- 1st :: 2015/08/15

**** 摘录

座右铭：你的就是我的，我还是我的

大凡皇帝出世，后来的史书上都会有一些类似的怪象记载。

元朝，老百姓如果不能上学和当官就没有名字，只能以父母年龄相加或者出生的
日期命名。

在这个马上民族统治中国六十余年后，他们的国家机器已经到了无法承受的地步，
此时的元帝国就好像是一匹不堪重负的骆驼，只等那最后一根稻草。

赈灾物品拨到各路（元代地方行政单位），地方长官们再留下点，之后是州、县。
一层一层下来，到老百姓手中就剩谷壳了。然后地方上的各级官员们上书向皇帝
表示感谢，照例也要说些感谢天恩的话，并把历史上的尧舜禹汤与皇上比较一下，
皇帝看到了报告，深感自己做了大好事，于是就在自己的心中给自己记上一笔。

谓化缘就是讨饭，我们熟悉的唐僧同志每次的口头禅就是：悟空，你去化些斋来。

长期的困难生活，最能磨练一个人的意志，有很多人在遇到困难后，只能怨天尤
人，得过且过，而另外一些人虽然也不得不在困难面前低头，但他们的心从未屈
服，他们不断的努力，相信一定能够取得最后的胜利。

，即使你拥有人人羡慕的容貌，博览群书的才学，挥之不尽的财富，也不能证明
你的强大，因为心的强大，才是真正的强大。

元的腐朽官吏为推翻元朝的统治实在是不遗余力，立了大功。

所谓璋，是一种尖锐的玉器，这个朱元璋实际上就是诛元璋，朱重八把他自己比
成诛灭元朝的利器，而这一利器正是元朝的统治者自己铸造出来的。在今后的二
十年里，他们都将畏惧这个名字。

待得秋来九月八，我花开时百花杀。 冲天香阵透长安，满城尽带黄金甲。

迷信是封建时代人们的通病，要想占有天下，必须要占据王气之地，南京就是这
么一个地方，紫金山纵横南北，恰似巨龙潜伏，而石头山则临江陡峭，如虎盘踞，
这就是南京龙蟠虎踞的来历，此外在南京的前方还有一条长江，皇帝和我们一样，
买房子前都要看风水，南京背山面水，实在风水好得爆棚。

真理往往是站在少数人一边的。

时穷节乃现，一一垂丹青。

在这个世界上，从来就不存在着完美的东西，任何制度都有缺陷，任何体系都有
漏洞

特务政治是明朝的一个特点，其代表机构就是锦衣卫。

个庄严的使命落在了朱元璋的身上，他经过慎重考虑，取“朝日鲜明之国”之意，
为这个王朝确定了新的名字——朝鲜。

善用刀剑者，死于刀剑下。

一般领导提拔你之前总是要打压一下的，所谓磨练就是这样来的，千万不要为此
和领导闹意见，否则就真有可能一辈子压制下去了。

书生办事，真正是不知所谓。

从犯罪心理学的角度来分析，杀人犯在残杀第一个人时是最困难的，但只要开了
先例，杀下去是很容易的。

坚持宽于律己，严于待人的原则，以圣人的标准来要求别人

盲目的自信往往比自卑更可怕。

这就是我所认为真正的英雄——畏惧并战胜畏惧的人。 关键只在于那畏惧的一刻，
你是选择战胜他，还是躲避他。

于谦祠

不自是，故彰；不自伐，故有功；不自矜，故长；夫唯不争，故天下莫能与之争

山近月远觉月小，便道此山大于月。 若人有眼大如天，当见山高月更阔。

守仁格竹

无论何时，何地，有何种理由，人性都是不能，也不会被泯灭的，它将永远屹立
于天地之间。

士不可以不弘毅，任重而道远！仁以为己任，不亦重乎！死而后已，不亦远乎！

天理即是人欲。

知行合一

此心不动，随机而行

无善无恶心之体， 有善有恶意之动。 知善知恶是良知， 为善去恶是格物

观点斗争是假的、方向斗争也是假的，只有权力斗争才是真的。

滚滚长江东逝水，浪花淘尽英雄， 是非成败转头空，青山依旧在，几度夕阳红。
白发渔樵江渚上，惯看秋月春风， 一壶浊酒喜相逢，古今多少事，都付笑谈中！〗

利益，只有充足的利益，才有驱动人们的魔力，这就是这个世界的真实面目，极
其的残酷，却异常的真实。 在这个残酷的现实面前，徐阶终于明白了知行合一
的真意，无论有多么伟大正直的理想，要实现它，还必须懂得两个字——变通。只
有变通，只有切合实际的行动，才能适应这个变化万千的世界。

只有真正了解这个世界的丑陋与污浊，被现实打击，被痛苦折磨，遍体鳞伤、无
所遁形，却从未放弃对光明的追寻，依然微笑着，坚定前行的人，才是真正的勇
者。 不经历黑暗的人，是无法懂得光明的。

小人物的愤怒是毫无用处的。

兵熊熊一个，将熊熊一窝，

来这个世界上还有很多人不喜欢诗词书画，也没有那么多的忧伤哀愁，他们想要
的只是一碗掺着沙子的米饭，对那些骨瘦如柴、眼凹深陷的饥民而言，一幅字画
是王羲之的还是怀素的，一点也不重要，重要的是那张字画纸够不够厚，方不方
便消化。

我所经历的痛苦与折磨，不想再让别人承受。

他认为，自己是唯一的清醒者。 然而他错了。 海瑞是糊涂的，事实证明，徐阶
看到了，高拱看到了，张居正也看到了，他们不但看到了问题，还有解决问题的
方法。而海瑞唯一能做的，只是痛骂而已。

把复杂的问题搞简单，那是能耐。

你还很年轻，将来你会遇到很多人，经历很多事，得到很多，也会失去很多，但
无论如何，有两样东西，你绝不能丢弃，一个叫良心，另一个叫理想。

你是个好人，却并无用处

所以主战者未必勇，主和者未必怯。

战争是政治的继续，打仗说穿了，最终的目的就是要对方听话，如果有别的方法
能达到目的，何必要打呢？

所谓流年，是一流到底，绝不半流而废。

诸臣误朕，朕死，无面目见祖宗，自去冠冕以发覆面，任贼分尸，勿伤百姓一人

人只活一辈子，如何生活，都是自己的事，自己这辈子浑浑噩噩地没活好，厚着
脸皮还来指责别人，有多远，就去滚多远。

成功只有一个——按照自己的方式，去度过人生。

**** 观感

** 奇幻
*** 哈利波特

**** 《哈利波特与密室》

***** 时间

- 1st :: 2015/02/10--2015/02/12

***** 摘录

***** 观感

**** 《哈利波特与魔法石》

***** 时间

- 1st :: 2015/02/10

***** 摘录

***** 观感

**** 《哈利波特与阿兹卡班囚徒》

***** 时间

- 1st :: 2015/02/13--2015/02/15

***** 摘录

***** 观感

**** 《哈利波特与火焰杯》

***** 时间

- 1st :: 2015/02/16--2015/02/18

***** 摘录

***** 观感

**** 《哈利波特与凤凰社》

***** 时间

- 1st :: 2015/02/19--2015/02/24

***** 摘录

***** 观感

读到此本以前,哈利波特系列给我的印象一直是一部童话,一部真正的童话.《魔
法石》和《密室》的单纯，《阿兹卡班》和《火焰杯》的成长，都让我爱不释手。

然而，到了《凤凰社》这部,一切都不再是那么美好了.罗琳好像要以更长的篇幅
去容纳更多的元素,事实上也确实如此.15岁的哈利在这一年中,经历了五系列的
负面情绪,以往的勇敢也裹携了更多的自以为是和鲁莽.

*** 福尔摩斯
**** 《福尔摩斯精选集》

***** 时间

- 1st :: 2015/03/06--2015/03/16

***** 摘录

***** 观感

*** 科幻
**** 《三体1》

***** 时间

- 1st :: 2015/04/03--至 2015/04/17

***** 摘录

***** 观感

2016/02/11

个人感觉名过其实，并不出彩。

** 其他

*** 《The source code of my world》

**** 时间

- 1st :: 2015/06/01

**** 摘录

**** 观感

花了些时间有选择地读完了胡正的这本”随笔体“，虽然其中有许多偏激的思想，
但是也不能因此而全盘否定。通过阅读这本怪异的书，也让我首次接触到了天才
的想法---的确与众不同，这个世界有很大一部分因为这些人而不同。

知道胡正，是因为使用星际译王的缘故---一开始还不明白为何取这么一个名字，
了解到作者本人的思想才知道他是要做大一统的词典。星际译王本身十分优异，
这点无可否认。

读了这本随笔，才意识到自己的想法有多么普通，而”天才“的想法多么怪异。
胡正的思想里有佛教的和尼采的，真是奇怪的结合。

我本能上认为佛教的思想是很好的，是三大宗教中我唯一可能认同的。只是我远
未到接受这些思想的时候，或者用佛教本身的话说，就是没有慧根。 既然如此，
我只有等到生活阅历积累到一定程度的时候才能去接触这种思想。

现在的我比较易于接受一些偏激的思想，偏激并不代表不正确。 虽然过度必然
是不好的，这里真理，但是年轻的我还是没有达到认同中庸的境界。通往中庸的
道路必然是偏执的，这也许可以用这样一句话来形容：不疯魔不成活。

现在的我还是选择做一个偏执的人，同时接触偏激的思想，如尼采等等，也接触
中庸的思想。

*** 《悟空传》

**** 时间

- 1st :: 2015/07/15

**** 摘录

那也不对，如果大家都不想活了，鬼神又靠谁来供奉呢？你看那些鸡狗猪羊，被
养在圈里，长大就杀掉，它们活着有何意义？本无意义，它们活和死都只是因为
人需要罢了。人又何尝不是一样？他们的生死也不过是因为神的需要罢了。神要
从万物的灵蕴中吸取能量，若是世间没有活物了，神也会枯萎消亡。灵魂是种子，
人是庄稼，神种下这些种子，然后让他们长大，产生欲望，去争斗，去爱恋，因
为欲望而痛苦，痛苦就会祈求神灵，就会愿意把自己的一切供奉，所以神才成为
神。如果没有人，神又有什么优越？正因为做人如此痛苦，神才受人景仰。正因
为人的卑微，神才高高在上。正如鸡犬的眼中，人也是神，也可以主宰它们的命
运一样。”

你入我眼，如花映水中，便不是花，色本是空，万物皆为红尘。

我要这天，再遮不住我眼， 要这地，再埋不了我心， 要这众生，都明白我意，
要那诸佛，都烟消云散！

想必道不可道，是要你自行开悟才是

也许每个人出生时都以为这天地是为他一个人而存在的，当他发现自己错的时候，
他便开始长大了

我爱你。 我却总是沉默。 我不会让任何人伤害你。 即使我从未开言。 这是我
的许诺，寂静无声。 你无须知晓。 它只在我心。

我放声大笑， 挥开如意金箍棒， 打它个地覆天也翻。 从今往后一万年， 你们
都会记住我的名字， 齐天大圣孙悟空。

可我喜欢在树上跳跳，地上跳跳，如果抬起头来正好看到了蓝天，我就更高兴了，
你难道不是吗？

西游果然只是一个骗局。 没有人能打败孙悟空。能打败孙悟空的只有他自己。
所以要战胜孙悟空，唯一的办法就是让他怀疑他自己，否认他自己，把过去的一
切当成罪孽，把当年的自己看成敌人，一心只要解脱，一心只要正果。

不断地寻找痛苦，比我更深的痛苦。这样我就知足，就宽心，就领悟神的力量，
他使追求越多的人越痛苦，而安卧于他脚下的人得极乐。

若天压我，劈开那天，若地拘我，踏碎那地，我等生来自由身，谁敢高高在上？

只因心高嫌地窄，立心端要破瑶天！

**** 观感

关于悟空迷失自我，唐僧的悟，八戒和月女的爱情，龙女对唐僧的爱慕，很奇特，
富有想像力。

剧情乱，有些语言故作高深，其实并经不起推敲，有趣，但并不欣赏。

*** 《盗墓笔记》

**** 时间

- 1st :: 2015/07/15

**** 摘录

**** 观感

读的电子版太乱

* Movie

** 我的电影

*** 使用 org-mode 进行管理
*** org-mode property 记录基本信息

- Director
- Leader
- Type
- Time

*** 使用 <百度云> 盘搜索，观看并留存云端

- 与本地一致
- 网络资源暂且保存在 <我的资源>(INBOX) 中, 有待后续整理

*** 使用 <虾米> 收藏原声大碟

*** 使用 <KMPlayer+终极解码> 对音频或视频片段进行捕捉

- 这个还没有折腾会，再说

*** 豆瓣影评

- 原声音评
- 豆瓣上有不错的 图片，收藏到印象笔记中

*** 关于本地收藏

- 使用移动硬盘收藏
- 整理规范
  - 艺人和类型混合整理
  - 与 org-mode 大纲一致
** 归来

2014/05/24

影院

** 明日边缘

2014/06/14

影院

** 后会无期

2014/07/24

影院

** 银河护卫队

2014/10/11

影院

** 大话西游

2014/11/02

影院

** 速度与激情7

2015/05/05

影院

** 侏罗纪世界

2015/06/21

影院

** 变形金刚4：绝迹重生

2015/07/06

影院

** 西游记之大圣归来

2015/08/04

影院

** 终结者：创世纪

2015/09/03

影院

** 小王子

2015/10/30

影院

** 大话西游

2015/12/13

影院

** 寻龙诀

2015/12/19

影院

** 荒野猎人

2016/01/17

** 蛮荒故事
:PROPERTIES:
:MOVIE:    1
:END:

2016/02/12

** 怦然心动
:PROPERTIES:
:MOVIE:    1
:END:

*** 时间

- 1st :: xxxx/xx/xx
- 2nd :: xxxx/xx/xx
- 3rd :: 2016/02/16

*** 台词

A painting is more than the sum of its parts. A cow by itself is just a cow. A meadow by itself is just grass, flowers. And the sun peeking through the trees is just a beam of light. But you put them all together and it can be magic.
一幅画不是众多物件简单拼凑而成的。牛只是一头牛，草地也只有青草和鲜花，而穿过树枝的阳光也仅仅只是一束光，但如果将它们放到一起，就会产生魔一般的魅力。

The higher I got, the more amazed I was by the view.
我爬得越高，眼前的风景便愈发迷人。

Some days the sunsets would be purple and pink. And some days they were a blazing orange setting fire to the clouds on the horizon. It was during one of those sunsets that my father's idea of the whole being greater than the sum of its parts moved from my head to my heart.
有时落日泛起紫红的余晖，有时散发出橘红色的火光燃起天边的晚霞。在这绚烂的日落景象中，我慢慢领悟了父亲所说的整体胜于局部总和的道理。

Sometimes a little discomfort in the beginning can save a whole lot of pain down the road.
有时起初的隐忍可以避免一路的疼痛。

Some of us get dipped in flat, some in satin, some in gloss. But every once in a while you find someone who's iridescent, and when you do, nothing will ever compare.
有些人沦为平庸浅薄，金玉其外，而败絮其中。可不经意间，有一天你会遇到一个彩虹般绚丽的人，从此以后，其他人就不过是匆匆浮云。

The first day I met Bryce Loski, I flipped. It was those eyes, something in those dazzling eyes.
见到布莱斯·罗斯基的第一天，我心动了。他的双眸有种魔力让我如痴如醉。

The next thing I know, he's holding my hand and looking right into my eyes. My heart stopped. Was this it? Would this be my first kiss?
接下来，我所知道的就是，他紧紧握住我的手，与我深情对视。我的心跳停止了。就要来了吗？我的初吻就要来了吗？

Sherry Stalls was nothing but a whiny, gossipy, backstabbing flirt. All hair and no substance. And there she was holding hands with Bryce. My Bryce. The one who was walking around with my first kiss.
雪利·斯道尔斯是个絮絮叨叨、阴险毒辣的长舌妇，头发长见识短。可她竟然牵起了布莱斯的手。那可是我的布莱斯！带着我的初吻到处招摇的布莱斯！

- And she's been stalking me since the second grade.
- Well, a girl like that doesn't live next door to everyone.
- 她从二年级起就老是缠着我。
- 这种女孩可是可遇不可求的。

One’s character is set at an early age. I'd hate to see you swim out so far you can't swim back.
从小看到老，我可不愿看到你做边城浪子回不了头。

The way she talked about what it felt like to be up in that tree to be held above the earth, brushed by the wind. Who in junior high talks like that? This weird feeling started taking over in the pit of my stomach and I didn't like it.
她说起那种置身树梢的感觉时说就像被高高举起，微风拂面。哪个初中生会说出这样的话呢？这种怪怪的感觉在我胃里翻腾，我不喜欢这种感觉。

The apple doesn't fall far from the tree.
树上掉下的苹果它落的地离树能有多远？

And I realized Garrett was right about one thing: I had flipped. Completely.
我意识到加利特一件事是说对了：我心动了。完全心动了。

*** 影评

- [[https://app.yinxiang.com/shard/s52/nl/11551545/a57f7bc9-d2bf-4f3a-86b0-aca91f475113?title=Let%20it%20be%20the%20one%20merits%20you(%E5%89%A7%E9%80%8F)%20(%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8%20%E5%BD%B1%E8%AF%84)][Let it be the one merits you]]

*** 观感

和哥哥一起坐在客厅中看的，看一次感动一次。 2016/02/17

** 放牛班的春天

*** 时间

- 1st :: xxxx/xx/xx
- 2nd :: 2016/02/17

*** 台词

*** 影评

*** 音乐

*** 观感

每二次看感觉情节很平缓。  2016/02/19

** 里约大冒险

*** 时间

- 1st :: 2016/02/18

*** 台词

*** 影评

*** 音乐

*** 观感

蛮有趣的。  2016/02/19

* Music
#+PROPERTY: ARTIST_ALL 陈迹迅 张国荣 朴树 "the Beatles"
#+PROPERTY: GENRES_ALL pop jazz classic
#+PROPERTY: TYPE_ALL EP
** 我的音乐
*** 使用 <虾米> 听音乐
*** 浏览 <豆瓣> 乐评

- 使用 Evernote 收藏乐评

*** 使用 Org-mode 记录

- 混合按 *艺人* 和 *类别* 分级
- 每张专辑使用一个标题管理
- 使用 Org-mode 的 *Property* 管理专辑信息

*** Org-mdoe properties
:PROPERTIES:
:END:

#+BEGIN_EXAMPLE
:PROPERTIES:
:Artist:   Eason Chan
:Title:    Taste the Atmosphere
:Time:     2010/10/15
:Genres:   pop music
:Type:     EP
:END:
#+END_EXAMPLE

- Title
- Artist
- Time
- Genres
- Type

*** 本地管理规范

- 在移动硬盘中收集音乐
- 按一定规范进行整理， 与 org-mode 大纲一致

*** 使用 <百度云> 云端保存

- 文件组织与本地一致

*** 音乐文件命名规范

#+BEGIN_EXAMPLE
+-- 歌手
      |
      |-- 时间-专辑名
           |
           |-- 专辑名.ape/flac
           |-- 专辑名.cue
#+END_EXAMPLE


+ 文件名后面可以在括号中添加补充信息

+ 文件名中可以有特殊字符,因为有的专辑名中带有特殊符号

+ 文件名中不要有空格,使用驼峰式命名规范

+ 歌手文件夹下可以分为无损和MP3两个文件夹，分别收藏不同格式的音乐文件

  - 无损是必要的，尽管听不出区别
  - 既然如此，也就没有必要在意MP3文件所占用的硬盘空间

+ 增量式地完成

  - 一次性完成太累人
  - 平时保持良好习惯

*** Foobar 是最爱的音乐播放器

- 支持无损及其索引
- 播放列表最人性化
- 支持格式众多
- 可以在整轨和分轨之间进行文件转换

*** 学习时适合听音乐么

Q: 学习时适合听音乐么？

A: 不适合。这样两样事情都没有做好。学习时即使环境嘈杂也不能拿耳机堵上
耳朵，这样更不容易专注。将音乐当作背景音乐，是生活不用心的一种体现。

*** TODOs
**** TODO Mayday 文件按规范重命名
**** TODO 张国荣音乐整理
**** TODO 朴树音乐文件按规范重命名
**** TODO 更新百度云
**** DONE Eason 无损整理
- State "D       from "TODO"       [2016-02-13 六 17:45]
**** TODO Eason 由于修改文件名而导致 cue 文件无效，修改 cue 文件内容
**** TODO 更新 Org-mode 的专辑信息 Property

** 陈奕迅
*** Taste the Atmosphere
:PROPERTIES:
:TITLE:    Taste the Atmosphere
:TIME:     2010/10/15
:GENRES:   pop
:TYPE:     EP
:ARTIST:   陈迹迅
:END:

2016/02/11

*** Stranger Under My Skin
:PROPERTIES:
:Title:    Stranger Under My Skin
:Time:     2011/02/22
:Genres:   pop music
:Type:     EP
:ARTIST:   陈迹迅
:END:

2016/02/04

*** Time Flies (EP)
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2016/01/29

*** The Key
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2016/01/22

*** Listen to Eason Chan
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2016/01/16

*** H3M
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/12/31

*** 不想放手
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/12/25

*** 认了吧
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/12/18

*** What's Going On…?
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/12/11

*** 怎么样
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/12/04

*** Life Continues…
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/11/27

*** U-87
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/11/21

*** Live For Today
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/11/13

*** Special Thanks To…
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/30

*** The Line-Up
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/23

*** The Easy Ride
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/16

*** 反正是我
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/10

*** Get A Life 演唱会
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/04

*** Shall We Dance? Shall We Talk!
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/10/03
*** 打得火热
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/25

*** Nothing Really Matters
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/18
*** 幸福
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/11

*** 与我常在
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/05

*** 婚礼的祝福
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/04

*** DUO 陈奕迅2010演唱会
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/09/03

*** 天佑爱人
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/08/28

*** 新生活
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/08/21

*** 我的快乐时代
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2015/08/16

*** ?
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

2016/02/19

** 张国荣

*** 一切随风

2015/07/08

*** 劲歌集

2015/07/08

*** 大热

2015/07/08

*** Untitled

2015/07/08

*** 陪你倒数

2015/07/03

*** 这些年来

2015/07/03

*** Printemps

2015/06/26

*** 红

2015/06/19

*** 宠爱

2015/06/13

*** LESLIE 侧面

2015/06/05

*** 兜风心情

2015/05/30

*** Salute

2015/05/24

*** HOT SUMMER

2015/05/22

*** Virgin Snow

2015/05/15

*** Summer Romance

2015/05/09

*** 爱慕

2015/05/01

*** 张国荣

2015/04/24

*** Stand Up

2015/04/19

*** 全赖有你 夏日精选

2015/04/17

*** 为你钟情

2015/04/10

*** Leslie

2015/04/06

*** 张国荣的一片痴…

2015/03/28

*** 风继续吹

2015/03/22
** The Beatles
*** Please Please Me

2015/01/11

*** Beatles for Sale

2015/01/11

*** Revolver

2015/01/11

*** Sgt. Pepper's Lonely Hearts Club Band

2015/01/11

*** The Beatles

2015/01/11

*** Abbey Road

2015/01/11

*** Let It Be

2015/01/11

*** Help!

2014/12/07

*** A Hard Day's Night

2014/12/02

*** With the Beatles

2014/11/21

*** Rubber Soul

2014/11/17

** 朴树

*** 生如夏花

2014/09/05

*** 我去2000年


2014/08/27
** 五月天


*** 知足 最真杰作选

2014/09/20

*** 时光机

2014/09/18

*** 神的孩子都在跳舞

2014/09/17

*** 人生海海

2014/09/11

*** 爱情万岁

2014/09/09

*** 第一张创作专辑

2014/09/05
** 陈绮贞

*** 让我想一想

2014/10/27
** 孙燕姿

*** 风筝

2014/10/17

*** 我要的幸福

2014/10/15

*** 孙燕姿 同名专辑

2014/10/14

** 影视原声


*** 2015/10/03  Soundtrack   Friends (The Ultimate Soundtrack)

*** 2015/10/01  Thomas Newman   WALL-E (An Original Walt Disney Records Soundtrack)

*** 2015/09/15  Soundtrack   I Am Sam (Music From and Inspired by the Motion Picture)
*** 2015/09/14  City of Prague Philharmonic Orchestra   The Godfather Trilogy
*** 2015/09/14  其他原声带   Three Idiots
** 古典音乐

*** 2015/04/11  Ludwig van Beethoven   Complete Beethoven Edition Vol.1: Symphonies

*** 2015/08/23  Wolfgang Amadeus Mozart   Ultimate Mozart: The Essential Masterpieces
** 其他

*** 2015/03/15  万晓利 	  这一切没有想象的那么糟

* Running


** 我的跑步
*** 每周进行一次长距离训练

2013/11/29  周五

每周至少一次，至少两个小时二十公里，多者不限。
挑空气质量良好，风小的晚上跑步，不要自虐，注重身体。

周六跑30公里吧。

** 2016

- 2016/01/04  5
- 2016/01/05  5

** 2016 马拉松

+ 3.20 无锡
+ 4.17 金陵长城
+ 5.29 秦皇岛
+ 9.11 天津
+ 9.18 北京
+ 11.5 上海
+ 12.4 深圳/广州

** record

- 2015/01/02  4
- 2015/01/06  10
- 2015/01/07  6
- 2015/01/10  6
- 2015/01/19  10
- 2015/01/20  4
- 2015/01/27  5
- 2015/03/12  5
- 2015/03/13  5
- 2015/03/16  5
- 2015/03/19  10
- 2015/03/20  5
- 2015/03/22  4
- 2015/03/24  5
- 2015/03/25  5
- 2015/03/27  2.5
- 2015/04/06  20
- 2015/04/10  2
- 2015/04/20  4
- 2015/04/22  5
- 2015/04/26  5
- 2015/04/27  3.6
- 2015/05/16  5
- 2015/05/25  5  晨跑
- 2015/05/26  5  晨跑
- 2015/05/27  5  晨跑
- 2015/05/28  5  晨跑
- 2015/05/29  5  晨跑
- 2015/05/30  5  晨跑
- 2015/05/31  5  晨跑
- 2015/06/01  5  晨跑
- 2015/06/02  5  晨跑
- 2015/06/03  5  晨跑
- 2015/06/04  5  晨跑
- 2015/06/05  5  晨跑
- 2015/06/06  5  晨跑
- 2015/06/07  5  晨跑
- 2015/06/08  5  晨跑
- 2015/06/09  5  晨跑
- 2015/06/10  5  晨跑
- 2015/06/11  5  晨跑
- 2015/06/12  5  晨跑
- 2015/06/13  1  晨跑 雨
- 2015/06/14  5  晨跑
- 2015/06/15  6  晨跑
- 2015/06/16  5  晨跑
- 2015/06/17  5  晨跑
- 2015/06/18  5  晨跑
- 2015/06/19  5  晨跑
- 2015/06/20  5  晨跑
- 2015/06/21  5  晨跑
- 2015/06/22  1  晨跑
- 2015/06/30  4
- 2015/07/12  5  奥森
- 2015/07/13  3  晨跑
- 2015/07/15  5  晨跑

* Guita


** 我的吉它

+我会尽快重新上手的，没有必要天天练习，每周抽出一两次时间即可，每次练
习的时间要长一些。+ (每天练习，作为放松的一种途径 2016/02/18)

** 丁香花
* 心灵鸡汤

** Dream

*** I have a dream.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** A man is not old until regrets take place of dreams.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 梦想一定要有的，万一实现了呢？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人如果没有梦想，那跟咸鱼有什么分别？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你能飞的时候就不要放弃飞；当你能梦的时候就不要放弃梦；当你能爱的时候就不要放弃爱。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人只要不失去方向，就不会失去自己！重要的不是所站的位置，而是所朝的方向。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不管现在你对未来多困惑，多迷茫，都不要忘了树立一个目标。一个人过去或现在的情况并不重要，将来想要获得什么成就才最重要。除非你对未来有理想，否则做不出什么大事来 。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Impossible is nothing.只要选择了目标，不要再想太远，每天脚踏实地，风雨兼程。生命不息，奋斗不止。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “出发时，你们就要定下高目标，不断努力。我希望你们找到生命中真正的意义、快乐和激情。希望你们能安渡艰难时光，并收获更强的力量与更坚定的决心。希望你们能怀着进取之心，在事业里全心投入，去掌控世界。因为世界需要你们去改变！”——facebook 首席运营官 谢丽尔·桑德伯格
:PROPERTIES:
:SOULSOUP: 1
:END:

*** You got a dream, you gotta protect it. Ｐeople can't do something themselves, they wanna tell you you can't do it. If you want something, go get it.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 追寻心中所想 永远都不会太晚
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做人如果没有梦想，跟咸鱼有什么区别。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要有最遥远的梦想和最朴素的生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每天都会冒出许多念头，那些不死的才叫梦想。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 梦想使生活得以忍受。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 目标和梦想是成长的核心成分。 勤奋学习和努力工作是成长的必经之路。 征服的勇气和愉悦的心情是成长的营养剂。 不断的阅读和独立思考是成长的加速器。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “梦想，可以天花乱坠，理想，是我们一步一个脚印踩出来的坎坷道路。”—《我親愛的三毛》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 没有抛弃人的梦想，只有抛弃梦想的人，再牛逼的梦想，也抵不住傻逼似的坚持！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “预测未来的最好方法就是创造未来。” -- Alan Kay
:PROPERTIES:
:SOULSOUP: 1
:END:

** Endeavor
*** 尽人事而后听天命，人自助则天助。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个优秀的人都有一段沉默的时光。那一段时光是付出了很多努力，忍受孤独和寂寞，不抱怨不诉苦，日后说起时，连自己都能被感动的日子。from《关于这个世界，你不快乐什么》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 将来的你，一定会感激现在努力的自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你所负担的将变成礼物。你所受的苦将照亮你的路。 泰戈尔
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Live as if you were to die tomorrow. Learn as if you were to live forever.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 天助自助者。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 以大多人的努力程度之低，根本轮不上拼天赋。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 父母年纪大了。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你不努力，谁也给不了你想要的生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每天清晨起床走到镜子面前对自己说：今天将是你余生中最年轻的一天，你没有理由不全力以赴。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 业精于勤荒于嬉，行成于思毁于随。 韩愈
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 越努力，越幸运。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你必须非常努力，才能看起来毫不费力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 今天很残酷，明天更残酷，后天很美好。但是大多数人都死在明天的晚上，看不到后天的太阳。 马云
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你配得上你想要的生活么？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每次想到在有限的生命里，竟要被那些傻逼的人和事所束缚，便会油然而生一种没来由的斗志，书剑满血复活。 马良《坦白书》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Work hard in silence. Let your success be your noise.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【一个人努力奋斗一生，大多是为了实现三大追求】1、财务自由：有足够金钱养活自己和家人，需要用钱时不发愁；2、时间自由：有可支配时间灵活安排工作、休息和娱乐；3、心灵自由：跟随自己内心，不让梦想憋屈。实现自由最容易的时间段，不是未来的某天而是现在。「转」
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 灾难总是接踵而至，这正是世间的常理。你以为只要解释一下，就有谁会来救你吗？要是死了，就只能说明我不过是如此程度的男人。 By罗罗诺亚·索隆
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “所谓的幸运，就是当你准备好了的时候，机会来了。” ——《把时间当作朋友》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我们确实活得艰难，一要承受种种外部的压力，更要面对自己内心的困惑。在苦苦挣扎中，如果有人向你投以理解的目光，你会感到一种生命的暖意，或许仅有短暂的一瞥，就足以使我感奋不已，所以我们要学会感激。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 面对不公平的东西,不要抱怨,你的不公平可能恰恰是别人的公平。所以，你不如去努力的奋斗，争取你自己最合适的公平。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你和你的朋友会一起在将来打造一个可能很辉煌的事业。很好听是吗？记住，你们都要努力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你有足够的理由佩服每天早起的人,不信的话,你去做。做到后会发现有很多人佩服你呢。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你的父母正在为你打拼，这就是你今天坚强的理由。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 以大多数人的努力程度之低，根本轮不上去拼天赋。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 嗯，加油，要做一个让未来的自己感动到要哭的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要抱怨的话，先努力完了再说。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** To strive, to seek, to find and not to yield.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不是每一次努力都能收获成功，但每一次成功都离不开努力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你打算放弃梦想时，告诉自己再多撑一天、一个星期、一个月，再多撑一年吧。你会发现，拒绝退场的结果令人惊讶。---力克.胡哲
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活最沉重的负担不是工作，而是无聊。——《成成驾到脱口秀》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 成长的路上只需全神贯注地努力就好，剩下的交给运气，不好的事情总会过去的
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果这世界上真有奇迹，那只是努力的另一个名字。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你现在得到的不是你所想要的回报，只能证明你付出的还不够。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人经历地越多，他的抱怨就会越少。这是一个有趣的现象，因为跟那些成天抱怨的人比起来，他经受的波折可能更多。越是优秀越是努力。这一现象的症结在于，优秀的人总能看到比自己更好的，而平庸的人总能看到比自己更差的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你必须很努力，才能做到看起来毫不费力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 将来的你，一定会感谢现在拼命努力的你。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Persist

*** 不论你在什么时候开始，重要的是开始之后就不要停止。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 最遗憾的不是失败，而是，我本可以。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生最大的是失败，就是放弃。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 守之甚严，而持之有恒者！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 糖，是熬出来的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 坚持下去，并不是我们真正的足够坚强，而是我们别无选择。并不是我们喜欢一件事情就可以把它做好，而是我们在做的时候，学会喜欢它。我没有别的，只有热血，眼泪和汗水可以奉献。这些都是我最宝贵的财富。请记住：永远不要放弃你自己。 丘吉尔
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做你想做的，坚持下去，那就是你的未来。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 宝剑锋从磨砺出，梅花香自苦寒来。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 其实这个世界上的大部分传奇，不过是普普通通的人们将心意化成了行动，坚持至极致而已。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当我年轻时我梦想改变世界；当我成熟后，我发现我不能改变世界，我将目光缩短，决定只改变我的国家；当我进入暮年，我发现我不能改变国家，我的最后愿望仅仅是改变一下家庭，但这也不可能。当行将就木，我突然意识到：如果一开始我仅仅去改变自己，我可能改变家庭、国家甚至世界——威斯敏斯特教堂碑文
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生命太过短暂，今天放弃了明天不一定能得到。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一种对工作和学习的冲击力及持久力会让你有特殊的魅力和个人实力
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 在坚持不懈的过程中，实在累了的时候，拿来读一读，看一看，又会有继续奋斗的动力。记住，再苦再累是自己选择的路，决不能放弃，更不能掉眼泪。只有毕业胜利的时候，眼泪才能流下。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Keep moving forward.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有记者问科比：“科比，你为什么如此成功？”科比反问记者：“你知道洛杉矶凌晨4点的样子吗？”记者摇摇头。科比：“我知道每一天凌晨4点洛杉矶的样子。”
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如果一件事情的成功率是1%，那么反复100次至少成功1次的概率是多少？】备选答案：10%，23%，38%，63%。——正确答案居然是63%，计算方法：成功率1%，失败率即99%，反复尝试100次，失败率99%的100次方约等于37%的失败率，那么成功率即63%。一件事若反复尝试，它的成功率居然可以不可思议的发生质变！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 成功的秘密就是每天淘汰自己。你不与别人竞争，不意味着别人不会与你竞争；你不淘汰别人，就会被人淘汰。别人进步时你没有进步就等于退步。如果你没有构建任何适应竞争、抗击风险的能力，当下一次危机来临时，你就将第一个倒下！追求安稳，是坐以待毙的开始。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 事情一件一件去做 | 夢想先生隨後就到
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果想成为一颗太阳，那就从尘埃做起；如果想成为一条大江，那就从水滴做起；如果想成为世界瞩目的英雄，那就从最普通、最平凡的人做起。循序渐进永远好过急于求成，每个想法的实现都是通过积累获得。——《微改变》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每天花一点钟看10页有用的书，每年可看3600多页书，30年读11万页书。诸位，11万页书足可以使你成为一个学者了。可是，每天看三种小报也得费你一点钟的工夫；四圈麻将又得费你一点钟的光阴。看小报呢？还是打麻将呢？还是努力做一个学者呢？——胡适
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【管理微寓言】老钟对小钟说：“你一年要摆31536000下。”小钟说：“我怎么可能完成？”老钟说：“你只需一秒摆一下，每一秒坚持下来就行。” 小钟想着：一秒摆一下,每一秒坚持下来。一年过去了，小钟真摆了31536000下！制定目标不难，难的是如何分解目标，一步步去实现。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有些事情不是看到希望才去坚持，而是坚持了才会看到希望。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 再苦再累，也要坚持，因为我知道生活就是这样的残酷现实，我除了坚持，还得坚持。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 傻逼样的去坚持，自会看见牛逼的结果
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Sometimes a winner is just a dreamer that never gives up.——有时候，成功者只是坚持梦想不放弃的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你现在的付出，都会是一种沉淀，它们会默默铺路，只为让你成为更好的人
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学着坚持自己认定的事，不要管别人怎么说，人活着，不是要取悦别人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 感觉累的时候，也许你正处于人生的上坡路。坚持走下去，你就会发现到达了人生的另一个高度。

** Love

*** 当你喜欢我的时候，我不喜欢你；当你爱上我的时候，我喜欢上你；当你离开我的时候，我却爱上你；是你走得太快，还是我跟不上你的脚步。
:PROPERTIES:
:FROM:     豆瓣
:END:

*** 我们早就过了向往轰轰烈烈爱情的年纪。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做自己就好，爱情的真谛在于相互的吸引,志趣相投的同行，而不是追逐和依附。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 那些与你毫无关系的人，就是毫无关系的，永远是毫无关系的。从认识的第一天开始，其实你就知道。就算是笑得甜甜蜜蜜，就算是有过无关痒痛的来往，就算你努力经营这段关系。而那些与你有关的，就是与你有关的，是逃也逃不掉的，就算你们只见过三次，就算你们三年彼此才搭理一次，就算是你简直想不起他或者她的样子，就算是你们隔着十万八千里。from《送你一颗子弹》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不忘初心，方得始终。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活太残酷了，如果我们不相信爱，还能为什么而活呢？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有些东西根本无法抗拒，比如孤独，比如回忆，比如爱上你。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 世界上只有一种真正的英雄主义，那就是认清生活的真相后依然热爱生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学生问追一个女孩总是追不上怎么办？我回答：女孩不是追来的，是吸引来的，你追的过程是吸引女孩的过程，如果女孩没有看上你，再追都是没有用的。也许用更多的时间丰富自己，让自己变得更有内涵，再出现在女孩面前，她就喜欢你了。另外，爱是有缘分的，哪怕再有内涵气质的人，也不能让所有女孩喜欢。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 好感和反感是你在观察人的时候最有害的一种心态，你要在事前就对一个人形成了好感或者反感，就没有办法诚实和客观地观察他了。----柴静
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 语言很多时候都是假的，一起经历的事情才是真的
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 自惭多情污梵行，入山又恐误倾城。世间安得双全法，不负如来不负卿？——仓央嘉措
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 永不期待，永不假设，永不强求。顺其自然，若是注定发生，必会如你所愿。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱一个人而那个人不爱你是很让人难受的，但更痛苦的是，爱一个人，却永远都没勇气告诉他。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱的力量大到可以使人忘记一切，却又小到连一粒嫉妒的沙石也不能容纳。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 假如一千个人从我身边踏过的，我也能听出你的脚步声，因为 999个人的脚是踏在地上，只有你的脚步声是踏在我的心上。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 家！甜蜜的家！天下最的莫过于家。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 得不到你所爱的，就爱你所得的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 思恋一个人的滋味就像喝了一大杯冰水，然后用很长很长的时间流成热泪。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 就像一双袜子，越是瞧起来不顺眼的袜子，越有可能永远陪在你身边，越是的漂亮袜子经常会少一只。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 只需一分钟就可以碰到一个人，一小时上一个人，一天爱上一个人，但需要花尽一生的时间去忘掉一个人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 鱼说：你看不见我的眼中的泪，因为我在水里；水说：我能感受到你的泪，因为你在我心里。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 宠和爱是不同的两件事，宠可以没有交流，而爱则不能。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 两人相爱时，渴求无限甜蜜的吻，但为何在争吵时，却要用接吻的嘴互相伤害呢？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 妈妈说过没有人值得你为他哭，唯一值得你为他哭的那个人，永远都不会让你为他哭。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 眼泪的存在，是为了证明悲伤不是一场幻觉。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱你的人，不管你接不接受，你都应该感谢对方，这是对他们的尊重。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你可以选择坚持，也可以选择放弃。没有对错。我是说对爱情来说，但是重要的是坚持你的选择。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要在女孩子面前就慷慨解囊，俨然一个款哥，即便你的确很有钱。要知道，看中你现有金钱的女人，终究有一天会因为金钱背叛你。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 喜欢一个人，就勇敢的告诉他或者她，我在天涯说过大学是学习的地方，但是我理解爱情的力量。追求你真正爱的人，只要自己认为值得，那就是值得的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 经常给家里打个电话，即使嘴上都说不想对方，其实内心早已情动于中；有了女（男）朋友，也不能忘了爹和娘。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 那个第一个向我表白的人，谢谢你让我知道了人生的第一次被爱。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我渴望能见你一面，但请你记得，我不会开口要求要见你。这不是因为骄傲，你知道我在你面前毫无骄傲可言，而是因为，唯有你也想见我的时候，我们见面才有意义。—— 西蒙娜·德·波伏娃
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 只要你要只要我有。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 即使现在形单影只，明日依旧满怀希望。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 总有一个合适的人在未来与我相遇 而我所能做的就是使自己更好 更足够配得上她 而在这之中 我会遇到很多人 或许她们会有她们的轨迹 而这些轨迹只是恰好与我有一小段在一起 这也没关系 我只需要做好自己能做的一切就行 夕阳也有自己的轨迹 但当它谢幕前 它染红了云彩 没有人知道自己走的路对不对 我能做的只有把手头的事情做到最好 对未来充满希望热爱现在的生活 我得到的都是侥幸啊 我失去的都是人生 失去的当作礼物眼下的就是幸福
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 顺其自然 不乱于心
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 先想想你能给别人什么，再说你想要什么。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 够真心，才是最厉害的武器。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人遇见一个人是可以获得重生的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 谦和，温顺且自持地生活，不乱于心，不困于情，不畏将来，不念过去。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱情不是生命的全部。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 世间安得两全法， 不负如来不负卿。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我知道自己喜欢你，但我不知道将来在哪里。因为我知道，无论哪里，你都不会带我去。而记忆打亮你的微笑，要如此用力才变得欢喜。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你是非常可爱的人，真应该遇上最好的人，我也真希望我就是。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 真正相爱的人是不需无时不刻在一起的，他们需要精神上的沟通和默契。他们尊重对方的生活方式，同时拥有自己的人格和世界。他们不会溺在一起，因为过分的依赖，特别是对他人身体、时间、空间、物质的无度占据，不是爱，是身心不独立的表现。不占有、不控制、而是精神契合
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱情如果不落到穿衣、吃饭、睡觉、数钱这些实实在在的生活中去，是不会长久的。真正的爱情，就是不紧张，就是可以在他面前无所顾忌地打嗝、放屁、挖耳朵、流鼻涕；真正爱你的人，就是那个你可以不洗脸、不梳头、不化妆见到的那个人。——三毛
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 恋人之所以会吵架，往往不是感情浅，而是用情深。两个人都深爱时，一点点矛盾都会让人受伤很重。因为太重视对方，所以放不下。其实，如果不爱，分手无所谓。但有感情，还是相互宽解和容忍吧。爱情，没有不吵架的，但底线是不分手。因为爱就是坚持在一起。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 想爱就爱了，不要自责，不要顾忌，不要纠结，不要拧巴，不要感叹，不要患得患失…尽量不要…！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要因为一点瑕疵而放弃一段爱情，毕竟爱情——需要的是真情，而不是完美。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 既然选择了你、我就会去好好的去爱你，我只想好好的爱你，我只想做你的唯一，陪你一起走下去，走到生命停止的那一刻，你若不离不弃、我定生死相随，现在我更明白了什么是珍惜，所以我没轻易放下这段感情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 努力赚钱，是为了不让自己的爱情受到别人金钱的考验——这就是现实。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 喜欢一个人，一定要让对方知道。也许得不到答案，至少你努力过，不必后悔。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “那个第一个向我表白的人，谢谢你让我知道了人生的第一次被爱。 ”——《听见涛声》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱情的十分之九是由爱人自己造成的，十分之一才靠那被爱的对象。——莫洛亚
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你能明白，只要一想起某个人，心就会绞着疼的那种感觉吗？——《分手合约》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学生问追一个女孩总是追不上怎么办？我回答：女孩不是追来的，是吸引来的，你追的过程是吸引女孩的过程，如果女孩没有看上你，再追都是没有用的。也许用更多的时间丰富自己，让自己变得更有内涵，再出现在女孩面前，她就喜欢你了。另外，爱是有缘分的，哪怕再有内涵气质的人，也不能让所有女孩喜欢。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个人的内心都有一座孤城，里面住着一个想赶也赶不走的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** When you're about to say goodbye, think twice, look back, and remember how hard it was to say hello. 当你想说再见的时候，请三思，请回回头，想想当初遇见的时候是多么不容易。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 情不知所起，一往而情深，怎奈何，如花美眷，终不敌，似水流年。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 叫你滚你就滚啊 不知道过来抱紧一点就没事了吗
:PROPERTIES:
:SOULSOUP: 1
:END:

*** When someone appears in your dreams, it means that person misses you. ~~~当某人出现在你的梦里，意味着那个人在想你。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不懂得自爱的人，就没有能力去爱别人
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我喜欢香蕉，可是你给了我一车苹果，然后你说你被自己感动了，问我为什么不感动。我无言以对，然后你告诉全世界，你花光了所有的钱给我买了一车苹果，可是我却没有一点点感动，我一定是一个铁石心肠的人！我的人品确定是有问题的！我只是喜欢香蕉而已啊。。——借此言送给那些对爱情盲目执着的人
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 时间很短，天涯很远。往后的一山一水，一朝一夕，自己安静地走完。倘若不慎走失迷途，跌入水中，也应记得，有一条河流，叫重生。这世上，任何地方，都可以生长；任何去处，都是归宿。那么，别来找我，我亦不去寻你。守着剩下的流年，看一段岁月静好，现世安稳。——白落梅
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 时光静好，与君语；细水流年，与君同；繁华落尽，与君老。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 情不知所起，一往而深。恨不知所踪，一笑而泯。
:PROPERTIES:
:SOULSOUP: 1
:END:
*** 别抱怨了，要怪就怪自己。有本事喜欢上别人，没本事让人家喜欢你。

*** 大部份的痛苦，都是不肯离场的结果，没有命定的不幸，只有死不放手的执着。—— 素黑
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要因为也许会改变就不肯说那句美丽的誓言；不要因为也许会分离就不敢求一次倾心的相遇。——席慕容
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我想，如果你有那么一点点喜欢我，就一点点，我也会有勇气去争取。可是，我也不知道怎么去分辨，生怕或许我以为的表示，也只是自己的自作多情。这样的自己，就会显得那么的渺小而力不从心。当对某人放进了感情，那么在他/她面前，你就像个神经，会惶恐，会不安，会焦虑，会患得患失。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 永不期待，永不假设，永不强求。顺其自然，若是注定发生，必会如你所愿。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** The person who can make you feel better is also the reason why you cry..能让你好起来的那个人通常也是那个让你哭的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 世界真的很小，好像一转身，就不知道会遇见谁；世界真的很大，好像一转身，就不知道谁会消失。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 在乎才会乱想，不在乎连想都不会想。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有些人，有些事，该忘就忘了吧，人家从没把你放心里过，你又何必自作多情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要学会在轻淡无形，不给别人施加压力的情况下去爱一个人。很好的爱一个人需要经过漫长的时间，甚至用一生的时间才能办到——保持足够距离，拥有适宜的谦卑。——梅·萨藤《独居日记》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 越有本事的男人，越没脾气。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人总是在接近幸福时倍感幸福，在幸福进行时却患得患失。——张爱玲
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你害怕失去一样东西时，这意味着，你只能要么放弃这样东西，要么放弃你自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 忘记一个人，并非不再想起，而是偶尔想起，心中却不再有波澜。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Time

*** 此心拖泥带水是人生最苦处。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你总是喜欢把事情拖到第二天，你不能总是这么拖了。有一天，你会有很多事情要做，你的余生都不够用了。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 时间就像海绵里的水，只要愿挤，总还是有的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你所浪费的今天，是所有昨天所有死去的人所期待的明天。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不负光阴不负心。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Yesterday is history. Tomorrow is a mystery. Today is a gift. That's why it's called present.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Your future is created by what you do today not tomorrow.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你能念书时，你念书就是；当你能做事时，你做事就是；当你能恋爱时，你再去恋爱；当你能结婚时，你再去结婚。环境不许可时，强求不来；时机来临时，放弃不得。这便是一个人应有的生活哲学了。——罗兰《我们的路》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你总是喜欢把事情拖到第二天，你不能总是这么拖了，有一天，你会有很多事情要做，你的余生都不够用。一一《余生的第一天》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要欺骗自己，想当然地认为自己在“最后关头”会表现得最好。你做不到这一点。没完成的任务会一直潜伏在你的潜意识里，这不会消除你的压力，相反你会感到压力越来越大。某件事非常重要，而且是必须要做的，即使你讨厌，你也一定要去做，现在就做。（约瑟夫·费拉里）
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 昨日种种譬如昨日死，今日种种譬如今日生
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 能冲刷一切的除了眼泪，就是时间，以时间来推移，时间越长，冲突越淡，仿佛不断稀释的茶。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要铭记在心：每天都是一年中最的日子。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Life is short. No procrastination.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Yesterday you said tomorrow.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 总是说明天再做的人是蠢蛋，老想着还有明天，会吃到苦头的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你的时间就是你自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1.时间是治疗心灵创伤的大师,但绝不是解决问题的高手。2.人生三不斗:不与君子斗名，不与小人斗利，不与天地斗巧。人生三不争:不与上级争锋，不与同级争宠，不与下级争功。人生三大憾事:遇良友不交，遇良机不握，遇好书不读。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有人问我怎样才能不浪费时间，我说忘掉时间才是真正的不浪费时间。如果做一件事情专注到忘掉时间，就意味着全心投入。只要这件事情本身是有意义的，就一定会有所成就。凡是我们每天赶时间的事情，大部分是没有意义浪费时间的事情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有人问我怎样才能不浪费时间，我说忘掉时间才是真正的不浪费时间。如果做一件事情专注到忘掉时间，就意味着全心投入。只要这件事情本身是有意义的，就一定会有所成就。凡是我们每天赶时间的事情，大部分是没有意义浪费时间的事情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 耿耿于怀着过去和忐忑不安着未来的人，也常常挥霍无度着现在。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Faith
*** 前方是绝路，希望在转角。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不管未来平坦还是泥泞，只要热爱生命，一切都在预料之中。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人要有信仰。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Tomorrow the birds will sing.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Everything will be OK.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你的前面有阴影，你的背后一定有亮光。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你值得拥有最好的一切。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 怎能将这个世界，让给那些你所鄙夷的人！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要让未来的你，讨厌现在的自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Pain is inevitable. Suffering is optional.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你永远比你想象的要强大。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Stay hungry. Stay foolish.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 永远年轻，永远热泪盈眶。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Tomorrow is another day.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个人都有潜在的能量，只是很容易：被习惯所掩盖，被时间所迷离，被惰性所消磨。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每天告诉自己一次：我真的很不错。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要做的事情总找得出时间和机会，不要做的事情总找得出借口。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 抱最大的希望，为最大的，做最坏的打算。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 发光并非太阳的专利，你也可以发光。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 记住该记住的，忘记该忘记的。改变能改变的，接受不能改变的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你可以输给任何人，但不能输给自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活再苦再累，请在心里对自己说：给老子笑。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Sky is your limit.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 为什么要登山——因为山就在那里
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 弱小即是罪孽。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Ｈold On Pain End —— hope
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一旦放弃的话比赛就结束了。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我可以失败，但我绝不放弃。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果有一天我们湮没在人潮之中，庸碌一生，那是因为我们没有努力活得丰盛。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 天行健 君子以自强不息 地势坤 君子以厚德载物
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要叹气。每叹一口气，就会少一分自信。要时刻提醒自己，我无所不能。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要把自己的信念挂在墙上。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要太把钱当回事，也不要不把钱当回事，它值多少就多少。金钱是一个好仆人，却是一个坏主子。——小仲马
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 只要你想做成一件事，全世界都会来帮你。 －－《搭车去柏林》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 撑不住的时候，可以对自己说声“我好累”，但不要对自己说“我不行”。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Hope is wishing something would happen. Faith is believing it will happen. Courage is making it happen. “愿望”是希望某事发生。“信念”是相信它会发生。“勇气”是让它发生。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你嘴上所说的人生就是你的人生。“好的”“一定会有办法的”“没问题”，每天都能说出这种积极话语的人，他们的每一天都会过得非常顺利，即使遇到了困难，他们也能够渡过难关。相反，每天听嚷着“太糟了”“太让人气愤了”“没办法了”的人，遇到的挫折也特别多，运气也显得特别糟糕。——佐藤富雄
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我不管这个世上的人怎麼说我...我只想依照我的信念做事，绝不后悔，不管现在将来都一样! ——罗罗亚·索隆
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “愿望”是希望某事发生。“信念”是相信它会发生。“勇气”是让它发生。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你看到面前的阴影，别怕，那是因为你的背后有阳光。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我们必须接受失望，因为它是有限的，但千万不可失去希望，因为它是无穷的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你是什么人便会遇上什么人；你是什么人便会选择什么人。——竹久梦二《出帆》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 曾经输掉的东西，只要你想，就一定可以再一点一点赢回来！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你真心相信一切都会好的时候，一切就会真的好了。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Hope的含义: Hold On, Pain Ends. 坚持住, 痛苦终会过去。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Courage
*** Look! If you had one shot, one opportunity, to seize everything you ever wanted one moment. Would you apture it, or just let it slip?
:PROPERTIES:
:SOULSOUP: 1
:END:

*** You have to kill those excuses, or they will kill you.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不求思想上的纯粹，只求行动上的坚决。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 逆风的方向，更适合飞翔。我不怕千万人阻挡，只怕自己投降。 五月天《倔强》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你没有变强，是因为你一直很舒服。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** tried. Ever failed. No matter. Try again. Fail again. Fail better.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生没有太晚的开始。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Go home or stand up. It's your fucking choice.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 比起害怕挑战失败，更可怕的是你什么都不做。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一切不能毁灭你的，都是你变得更强大。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活不是用来妥协的，你退缩得越多，让你喘息的空间就越有限；日子不是用来将就的，你表现得越卑微，一些幸福的东西就会离你越远。在有些事情中，无须把自己摆得太低，属于自己的，都要积极争取；在有些人前，不必一而再德容忍，不能让别人践踏你的底线。只有挺直了腰板，世界给你的回馈才会多点。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 也许，在所有不被看好，无人尝试的错误的选择背后，会有不曾见到的可能，不曾设计的未知。未知让人恐惧，引人好奇，也因此证明你的勇气，成就你的自信。在每个死胡同的尽头，都有另一个维度的天空，在无路可走时迫使你腾空而起，那就是奇迹。——廖一梅《像我这样笨拙地生活》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 对明天如此恐惧，你今天又怎么能过好呢？————《三傻大闹宝莱坞》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 积极的人在每一次忧患中都看到一个机会，而消极的人则在每个机会都看到某种忧患。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做你没做过的事情叫成长，做你不愿意做的事情叫改变，做你不敢做的事情叫突破。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 大部分的恐惧与懒惰有关，这句我深以为然。我们常常会害怕改变，其实都是因为自己太懒了，懒得去适应新的环境，懒得去学习新的知识，涉足新的领域，但如果总是这样的话如何能让自己成熟起来呢？—— M·斯科特·派克《少有人走的路》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Eleanor Roosevelt says that “You must do the thing you think you cannot do.” 罗斯福夫人说过，“你必须做你认为自己做不了的事。”
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你知道什么叫失败？ 真正失败的人，就是那种特别害怕不能成功，怕死了，连试都不敢试的人。——《阳光小美女》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 相信自己，你能作茧自缚，就能破茧成蝶。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “你相信人能改变命运么？”“人应竭尽所能……然后再听天由命。”——《最后的武士》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有勇气并不表示恐惧不存在，而是敢面对恐惧、克服恐惧。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我们缺少的不是机会，而是在机会面前将自己重新归零的勇气。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 冷静，有大事时，能安静并能快速想出办法的人，很厉害。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 好好利用公开场合锻炼、展示自我，哪怕只是一次课堂上的发言，别怕尴尬，更别怕丢人，也不要笑话在公众面前丢脸的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 遇到再大困难的时候，不要惊慌，千万要学会冷静；不要去想着求别人，以前有家人帮你，现在需要你一个人面对挑战，从绝望中寻找希望，人生终将辉煌。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 好好利用在公共场合说话的机会来锻炼自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 别怕丢人，追求丢人是一种成功的尝试，至于为此笑话你的人，你可以把他们从你将来人生对手的名单中排除了，你也要为每一位上台唱歌的人鼓掌。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “自信来源于成功的暗示；自卑来源于失败的暗示。” 如果你有自信，它会在无形之中释放出能量，推动你走向成功；如果你自卑或恐惧，它也会在无形之中释放出能量，导致你走向失败。成功的人会因为体验到成功的快乐而更加自信；失败的人也会因为体验到失败的痛苦而更加自卑。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无论你犯了多少错，或者你进步得有多慢，你都走在了那些不曾尝试的人的前面。No matter how many mistakes you make or how slowly you progress, you are already ahead of those who never tried.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人怎么看待自己，决定了此人的命运，指向了他的归宿。我们的展望也这样，当更好的思想注入其中，它便光明起来。不管你的生命多么卑微，你要勇敢地面对生活，不用逃避，更不要用恶语诅咒它。—— 梭罗《种子的信念》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 因为害怕结果就什么都不做么？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 机会永远降临在有准备的人身上。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 能不能暂时把你的勇气给我 在梦想快消失的时候 让我的歌 用力地穿过天空为我爱的人 做一秒英雄
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 面对就会简单 奋斗带来自由
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我不怕千万人阻挡 只怕自己投降
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 灾难总会接踵而至 这是世间的常理。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 担责任也是证明自己的一种方式。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** It's better to burn than to fade away.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 怕什么就会想到什么，信什么就会听到什么，让我们恐惧的，不是外面的世界，而是我们的内心。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每年，至少要去一个从没去过的地方
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Don't worry too much about the ambiguous future, just make effort for explicit being present. 不为模糊不清的未来过分担忧，只为清清楚楚的现在奋发图强。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “我们必须勇敢地面对可怕的事情，因为我们不可能逃避它们、忘记它们。你越早渡过这一关，越早对自己说，‘是的，事情已经发生，我无能为力。’就越早能开始你自己的生活。” ----安妮·普鲁
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你知道什么叫失败吗？真正失败的人就是那种特别害怕不能成功，连试都不敢试的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 因为害怕结束，就避免了开始； 因为害怕跌倒，就避免了奔跑； 因为害怕失去，就避免了拥有； 因为害怕伤痛，就避免了相恋； 因为害怕失败，就避免了尝试；因为害怕离别，就避免了欢聚； 因为害怕了害怕，只能不断徘徊着徘徊； 因为避免了避免，只剩失去自己的自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 所谓坚强，不是在灾难面前不哭，而是要笑着面对以后。——《背包十年》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 爱因斯坦：“If you always do what you always did, you will always get what you always got.”（如果你一直重复过去做过的事情，那么你将只会获得已经拥有的东西。）
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 别让怯弱否定自己，别让懒惰误了青春。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Happiness
*** 如果没有那么多的感动，那么多的痛苦，在狂喜和绝望的两极来来回回，活着还有什么意思呢？from 《恋爱的犀牛》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 感觉快乐，就要忙东忙西；感觉累了，就放空自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 幸福本身就是虚妄，它只存在于追求幸福的过程中。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 获取幸福最重要的是：有所为，有所爱，有所期待。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 最快乐的人并不是一切东西都是最好的，但他们会充分享受自己已有的东西。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 聪明人是快乐的，自以为聪明的才烦恼。帮助别人减轻三分烦恼，自己就会享受七分快乐。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 快乐要懂得分享，才能加倍的快乐。
:PROPERTIES:
:SOULSOUP: 1
:END:
*** 多笑笑，会慢慢让自己真的快乐起来。

*** If there is light in everybody, so send out your ray of sunshine.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Ｈappiness is only real when shared.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 什么样的工作比较可能给你快乐?第一,它给你意义;第二,它给你时间;你的工作是你觉得有意义的，你的工作不绑架你使你成为工作的俘虏,你就比较可能是快乐的。当你的工作在你心目中有意义,你就有成就感。当你的工作给你时间,不剥夺你的生活,你就有尊严。成就感和尊严,给你快乐。——龙应台《亲爱的安德烈》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你不快樂，那就出去走走、世界這么大。風景很美、機會很多、人生很短，不要捲縮在一處陰影中。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Individuality
*** 我所理解的“内心坚硬”，是在对世界有基本了解的前提下，找到适合自己处事方式，尽可能高效低耗地协调内外矛盾。
:PROPERTIES:
:SOULSOUP: 1
:END:
*** Follow Excellence. Success will chase you.

*** 继续向前买进吧。你不是有健全的双脚么，不需要依靠任何东西。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 安慰捉襟见肘，唯有冷暖自知。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Loser always whine their best.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 在完全了解一件事物之前，你并不拥有否定它的资格，对人亦是如此。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 少说话多做事。我认为我是个好家伙。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我们无法选择自己的缺点，它们也是我们的一部分，我们必须去适应它们。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之，不笑不足以为道。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 仰望星空时，我们知道这些星星距离我们成百上千光年，有些甚至已经不存在了。它们的光花了很长很长时间才到达地球，而在此期间，他们本身已经消失或爆炸瓦解成红矮星了。这些事实会让人觉得自己很渺小，如果生活中遇到了困难，不妨想想这些，你就会明白什么叫微不足道。 by 马克·哈登
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果看不清自己，就看看身边的人。你只是你周围的事物。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人活的应该是自己，并且干净。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Be the changes you want to see in the world. 圣雄甘地
:PROPERTIES:
:SOULSOUP: 1
:END:

*** when you reach for the stars you may not quite get one, but you won't come up with a handful of mud either. Leo Burnett
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个人走的路，都是自己选的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 自己选择的路，跪着也要走完；宁愿笑着流泪，也不哭着说后悔。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 把人们引向艺术和科学的最强烈的动机之一，就是要逃避日常生活中令人厌恶的粗俗和使人绝望的沉闷，是要摆脱人们反复无常的欲望的桎梏。一个修养有素的人总是渴望逃避个人生活而进入客观知觉和思维的世界；这种愿望好比城市里的人渴望逃避喧嚣拥挤的环境，而到高山去享受幽静的生活，在那里透过清寂而纯洁的空气，可以自由地眺望，陶醉于似乎是为永恒而设计的宁静景色。叔本华
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 走自己的路，让别人去说吧。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果因为一个借口而不想去做一件事情，那么这个借口的存在便是去做的理由。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 优于别人，并不高贵，真正的高贵应该是优于过去的自己。━━━ 海明威
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【内向者更易成为卓越领导者？】40%美国公司高管是“内向者”,包括盖茨和巴菲特。内向者的力量源自“安静”：1.他们先思考,再发言：善于沉默,往往会被更好地倾听；2.更注重深度；3.平和的自信：让团队安心归附；4.更热衷文字交流：更清晰、准确地表达立场；5.习惯孤独：不为社交浪费太多精力，善承压。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 托尔斯泰：“一个人越聪明、越善良，他看到别人身上的美德越多；而人越愚蠢、越恶毒，他看到别人身上的缺点也越多。”
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 放纵自己的欲望是最大的祸害；谈论别人的隐私是最大的罪恶；不知自己过失是最大的病痛。—— 亚里士多德
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你必须只有内心丰富，才能摆脱这些生活表面的相似。——王朔《致女儿书》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 对于我而言，其实真正能够让我生活的心安理得的，不是锦衣玉食的生活，而是那种知识深入骨髓的踏实感，是那种每天都看到自己在进步，在前进，没虚度年华
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 只承诺你能做到的，然后尽力超越你承诺的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 思想的本质是不安。一个人的观念一旦产生动荡，新的思想就已经萌芽，人们需要的只是给这个萌芽一个剥离掉泥土，让它露出来的机会。-----摘自柴静清华讲座
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做自己的观察者，不做情绪的小跟班！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 成熟是给陌生人看的，傻逼是给小伙伴看的，幼稚是给喜欢的人看的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 士人读书，第一要有志，第二要有识，第三要有恒。有志，则断不甘为下流。有识，则知学问无尽，不敢以一得自足；如河伯之观海，如井蛙之窥天， 皆无见识也。有恒，则断无不成之事。此三者缺一不可。——曾国藩
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人真正关心别人的时候，才会忘记自己。---《看见》之非典纪录
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人要是太关注自己了，就会失去正常的判断能力了。——藤田宜永
:PROPERTIES:
:SOULSOUP: 1
:END:

*** “你要按你所想的去生活，否则，你迟早会按你生活的去想。” by 陈楸帆
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 拥有的资源多少并不重要，如果你不懂得使用，永远都是不够的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 自己要先看得起自己，别人才会看得起你。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有些事情本身我们无法控制，只好控制自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果敌人让你生气，那说明你还没有胜他的把握。如果朋友让你生气，那说明你仍然在意他的友情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 失因为贪 ——说真的，老实人很少上当。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活中若没有朋友，就像生活中没有阳光一样。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每一件事都要用多方面的角度来看它。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 在世，应该这样，在芬芳别人的同时美丽自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人有生就有死，但只要你活着，就要以最好的方式活下去。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 成大事的方法多种多样 ，别不接受你看不惯的方法
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要把过去的事全让人知道，尊敬不喜欢你的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 坚持在背后说别人好话，别担心这好话传不到当事人耳朵里,有人在你面前说某人坏话时，你只微笑。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 对陌生人，或者把对方当做一张白纸，或者把对方当你的朋友，总之别当做敌人，即使你听到再多的关于他（她）的不好的传闻。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果老是去琢磨哪些人你讨厌，哪些人与你志趣相投，那么你就大错了，要想着如何让别人接纳你，而不是你能接受什么样的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生百态,不要对新的看不惯的东西生气,无所谓的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你的确要学的有心计,但是记住,永远记住,在社会上要胜利的唯一的方法永远只是一个,那就是实力,永远不用怀疑。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 永远不要瞧不起家境贫困的同学，他们在相对差的条件下做到了和你一样的成绩，已经说明他们比你更加出色。每个人的生活都应该是平等的，尽你所能去帮助他们。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 心烦意乱或者无聊闲着的时候，多到图书馆去泡泡，书中有现实中难得的纯明和清静；多看些书，生活会渐渐少一些迷茫，多一些追求。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果周围有人嫉妒你，那么你可以把他从你的竞争者之列排除了。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 别为你自己和别人下定论，你所看到听到的可能只是一面。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 施人之恩，不发于言。受人之惠，不忘于心。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要轻言你是在为谁付出和牺牲，其实所有的付出和牺牲最终的受益人都是自己。人生是一场与任何人无关的独自的修行，这是一条悲欣交集的道路，路的尽头一定有礼物——就看你配不配得到。——卡玛《人生是一场独自的修行》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 温柔要有，但不是妥协，我们要在安静中，不慌不忙地坚强。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你太在意别人的眼光，你永远做不了自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我就是我 是颜色不一样的烟火 天空开阔 要做最坚强的泡沫 我喜欢我 让蔷薇开出一种结果 孤独的沙漠里 一样盛开得赤裸裸
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 成功只有一个——按照自己的方式，去度过人生。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 冬天里吃冰淇淋也别有风味。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 保持自我比你整天装逼活得更愉快。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 让我做个行动上的流氓思想上的文青吧
:PROPERTIES:
:SOULSOUP: 1
:END:

*** It's very easy to be different, but very difficult to be better.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人要像一支队伍，对着自己的头脑和心灵招兵买马，不气馁，有召唤，爱自由。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 对于大多数人来说，生活是由环境决定的。他们在命运的拨弄面前，不仅逆来顺受，甚至不能随遇而安。我尊重这些人，可我并不觉得他们令人振奋。还有一些人，他们把生活紧紧地掌握在自己手里，似乎一切要按照自己的意愿去创造生活。这样的人虽然寥若星辰，却深深吸引着我。——毛姆《生活的道路》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 乔布斯年轻时每天凌晨四点起床，九点半前把一天工作做完。他说：自由从何而来？从自信来，而自信则是从自律来！先学会克制自己，用严格的日程表控制生活，才能在这种自律中不断磨练出自信。自信是对事情的控制能力，如果你连最基本的时间都做控制不了，还谈什么自信？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 自信来自于内心，而不是来自于和别人的比较，和别人比较永远不可能带来真正的自信。比较的结果不是产生虚妄的优越感，就是产生强烈的自卑感。这两种感觉和真实的你无关，也和自信无关。自信是一种自我肯定，肯定自己在某些方面能够做得比较出色，而不是在所有方面都比别人好。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 亚马逊CEO杰夫-贝索斯说：善良比聪明更难。聪明是一种天赋，而善良是一种选择。天赋与生俱来，选择则颇为不易。你可能被天赋所诱惑，这可能会损害到你做出的选择。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果脸上长了个疙瘩，我们就会特别注意掩饰，害怕别人注视，总觉得会很难看，其实别人基本上不太关注，看到了也不会有什么负面评价；但对于那些无形的缺点比如自以为是、小气狭隘等，我们常常不加掩饰或改正，以为别人看不到，但恰恰人的本能是看不清自己，却能看清别人，所以会对你的缺点洞若观火。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 「成事之道」1、事大，须有宏远的观点；事小，须有谨慎的态度；事难，须有无畏的精神；事易，须有珍惜的心情。 2、凡事不着意，则宏伟的大事，变成小事；万事皆有心，则微细的小事，终成大事。 3、缘不聚，则一事难成；缘相聚，则万事俱可。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活，就是一种永恒沉重的努力，努力使自己在自我之中，努力不至迷失方向，努力在原位中坚定存在。——米兰·昆德拉《被背叛的遗嘱》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生最大的勇敢之一，就是经历欺骗和伤害之后，还能保持信任和爱的能力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无论环境多么恶劣，你总还可以做最好的自己，改变不了大环境，就改变小环境，做自己力所能及的事情。你不能决定太阳几点升起，但可以决定自己几点起床！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每天告诉自己：你的生命非常有限，所以，不要浪费在重复他人的生活上；不要被教条束缚，不要被他人喧嚣的声音掩盖你内心；你要有勇气，听从你心灵和直觉的指示，你的内心知道你想要成为什么样子的。其他事情都是次要的
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当所有人都拿我当回事的时候，我不能太拿自己当回事。当所有人都不拿我当回事的时，我一定得瞧得上自己。这就是淡定，这就是从容。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 面对别人的优秀时，发自内心地赞美。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** A smile is an inexpensive way to improve your looks. 微笑是改善容貌的一种并不昂贵的方式。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 施人之恩，不发于言。受人之惠，不忘于心。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【脸皮薄的人难以成功】1、我们干大事的从来不要脸。——严介和（太平洋集团前总裁） 2、只有不要脸的人，才会成为成功的人。——任正非（华为总裁） 3、为了面子坚持错误是最没有面子的事情。——巍巍（经济刊物主编）4、当你知道了面子是最不重要的东西时，你便真的长大了。——格瓦拉
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无趣的不是这个世界，而是我们没有坚持那些有趣的活法。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一位印度老人对孙子说，每个人的身体里都有两只狼，他们残酷地互相搏杀。一只狼代表愤怒、嫉妒、骄傲、害怕和耻辱；另一只代表温柔、善良、感恩、希望、微笑和爱。小男孩着急地问：“爷爷，哪只狼更厉害？”老人回答：你喂食的那一只。— — 你的心所朝的方向就是你未来人生的路。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** ＂文化＂可以用四句话表达：植根于内心的修养；无需提醒的自觉；以约束为前提的自由；为别人着想的善良。——梁晓声
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 托尔斯泰：“一个人越聪明、越善良，他看到别人身上的美德越多；而人越愚蠢、越恶毒，他看到别人身上的缺点也越多。”
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【炫耀源于内心的不自信】心理学上认为，“爱向别人炫”是一种内心需要被关注被肯定的表现，很可能是因为某种东西自己不常有，一旦拥有，希望藉以外界的羡慕来建立自信。不向别人晒自己的幸福会憋死你么？如果会，最好问问为什么。记住：生活不是演戏，自己精彩就好！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你是一个什么样的人，就会听到什么样的歌，看到什么样的文，写出什么样的字，遇到什么样的人。你能听到治愈的歌，看到温暖的文，写着倔强的字，遇到正好的人；你会相信那些信念，温暖，梦想和坚持这些早就老掉牙的字眼；是因为你就是这样的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你要克服的是你的虚荣心，是你的炫耀欲，你要对付的是你的时刻想要冲出来想要出风头的小聪明。—— 毛姆
:PROPERTIES:
:SOULSOUP: 1
:END:

*** It's never too late to be what you might have been.勇敢做自己，永远都不迟。（乔治·艾略特）
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有关的人太多，所以还不如做一个想要做的人，人生都太短暂，去疯去爱去孤单一场，真正能平静自己的只有自己。人都是孤独的，孤独不可怕，可怕的是惧怕孤独。想要摘星星的孩子，孤独是我们的必修课，我不怕自己努力了不优秀，我只怕比我优秀的人比我更努力。—— 《孤独是你的必修课》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个人都要有个骨灰级的爱好。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Be crazy. Be stupid. Be weird. Be whatever. Because life is too short to be anything but happy.疯就疯吧，笨就笨吧，怪就怪吧，想怎么样就怎么样。生命短暂，快乐至上。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 做人最高境界不是一味低调，也不是一味张扬，而是不卑不亢。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 得按你想的去生活，否则，你迟早会按你生活的去想。——连岳
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 有件事我们必须明白：从现在到30岁，我们都必须为生活而进行各种尝试，防止堕落。置身于生活之中。我必须打一场漂亮的战争，我们一定要成为有出息的人，尽管现在我们都没有。直觉告诉我：我们一定能干一番大事业，一定会与别人不一样。—— 《梵高书信集》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人所受苦的根源就是来自于不清楚自己是谁，而盲目地去攀附、追求那些不能代表我们的东西。——张德芬
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 自爱，沉稳，而后爱人。 ———亦舒
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 没有谁能一路单纯到底，但要记住，别忘了最初的自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 与其热闹着引人夺目，步步紧逼，不如趋向做一个人群之中真实自然的人，不张扬，不虚饰，随时保持退后的位置。心有所定，只是专注做事。——安妮宝贝《素年锦时》
:PROPERTIES:
:SOULSOUP: 1
:END:

** Habbits
*** 一本好书会让我安静下来，会让我有内心生活。我每天出去都是应酬、谋生、作假，片刻的安静都是读书带来的。法国人蒙田有句话，大意是人类的一切灾难在于人回到家还安静不下来。我很庆幸我没有变成在自己的房间里面安静不下来的人。这和我这么多年坚持阅读有很大的关系。我对阅读充满感激。——陈丹青
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 梁启超曾告诫已到美国留学三年的梁思成：你该挤出一部分时间学些常识性东西，特别是文学或人文科学，稍稍多用点工夫就能有大的收获。我深怕你因所学太专一的缘故，把多彩的生活弄得平平淡淡，生活过于单调，则生厌倦心理，厌倦一生即成苦恼之事……书宜杂读，业宜精钻。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 抽时间出来锻炼身体。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 很多事情别人通知你了，要说谢谢，没有通知你，不要责怪，因为那些事你其实应该自己弄清楚。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 别说脏话，随便的一个字或者几个字会让你在别人心中的形象大打折扣，切忌无病呻吟的成天喊“堕落与颓废”。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 最小的善行胜过最大的善念
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如何成为一个高效的人】1）将自己的表拨快10分钟。2）为目标设定像1-2-3这样的优先级。3）把大目标细分为可以立刻执行出结果的小任务。4）第一次就做对。5）每天自学1小时，一年365小时，3年可成专家。6）每周5天，每天花5分钟改进自己的工作，在5年里将使同一个工作被改进1200余次。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【10招帮你赢取上司最佳印象】1、早到；2、从不以“这不是我份内的工作”为由逃避责任；3、面对艰巨任务时淡定；4、立刻动手；5、口风紧；6、听从上司的临时指派；7、拿着解决方案汇报工作；8、以无欲的心态做事；9、善于在关键时候作出果断决定；10、专业及相关信息丰富。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【电子简历小建议】1. 联络信息中强调电子邮件；2. 清晰简明地表述职业目标；3. 可以插入视频或音频；4. 将个人能力放到更明显区域；5. 详细描绘工作经验和工作业绩，注意应包括所有关键字；5. 将学历、专业和毕业院校集中在一行；6. 最好在最后包含推荐人信息；7. 最终命名时应与求职工作相关。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1凡事第一反应找方法，不是找借口。2养成记录习惯，好记性不如烂笔头。3每天自我反省。4用心倾听，不打断别人的话，作个倾听高手。5遵守诚信，说到做到。6时刻微笑待人处事。7无论什么会议都找前排坐。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【格式塔心理疗法】 格式塔心理疗法是心理学中一种修身养性的疗法，归纳为九项原则：1.生活在现在；2.生活在这里；3.停止猜想，面向实际；4.暂停思考，多去感受；5.接受不愉快的情感；6.不要妄断和发表参考意见；7.不要盲目地崇拜偶像和权威；8.我就是我；9.对自己负责。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 上班族趴在桌上睡觉易导致青光眼：趴在桌上睡觉，胳膊会压住眼睛，醒后就会出现短暂视力模糊。这是因为压迫到了眼球，造成眼压过高。如果长此以往，还有可能形成青光眼。因此建议，午睡最好躺着睡。可在办公室里备一个颈枕，背靠在椅子上睡，颈椎也能处于跟躺着睡觉时一样自然放松的状态。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无论你的收入是多少，记得分成五份进行规划投资：增加对身体的投资，让身体始终好用；增加对社交的投资，扩大你的人脉；增加对学习的投资，加强你的自信；增加对旅游的投资，扩大你的见闻；增加对未来的投资，增加你的收益。好好规划落实，你会发现你的人生逐步会有大量盈余。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 死记硬背也许能让你通过大学4年，但会毁掉你接下来的40年。 —— 《三个傻瓜
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 最短命的活法：1.长时间对着电脑 2.晚上十一点以后睡觉 3.不能保证睡眠时间 4.极度缺乏体育锻炼 5.有病不求医 6.吃饭口味偏重，特别喜食咸的和辣的 7.不饿不吃，不困不睡，不累不息 8.与家人缺少交流 9.长时间用手机打电话，享受近距离辐射 10.三餐饮食无规律。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** Everyone knows about principles of life. But it is hard to control blue mood.大道理人人都懂，小情绪却是难以自控
:PROPERTIES:
:SOULSOUP: 1
:END:

*** ＂注意你所想的，因为它们会变成嘴里的话；注意你所说的，因为它们会变成实际的行动；注意你的行为，因为它们会形成习惯；注意你的习惯，因为它们会形成你的人格；注意你的人格，因为它们会影响你的命运；我们想的是什么，就会成为什么样的人。＂----玛格丽特·希尔达·撒切尔。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不吃早餐的人不能委以重任，一个连自己健康都不在意的人不会在意任何项目的细节。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 别在喜悦时许诺，别在忧伤时回答，别在愤怒时做决定.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要想太多，定时清除消极思想。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如何使大脑精神集中】1. 合理安排工作计划：先做需要精神集中的工作，再进行简单的工作；2. 谨慎分配自己的时间：明确自己每天在何时、何地能更好地集中精力，安排艰难任务；3. 刻意训练：每天花一些时间强迫自己集中地做一件事，也许从坚持5分钟开始，逐步累加。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人丑就该多读书。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【三条丢弃规则】1.如果让你心情沉重、对自己有不好的感觉、阻碍你前行的，把它丢掉。2.如果只是占有空间，对你的人生毫无正面贡献，把它丢掉。3.任何事物，要丢还是要留，你得花很长的时间权衡利弊，或是烦恼不知所错的，那把它丢掉。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Loss
*** 有时不吃些苦头，就看不清真相。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 治疗悲伤最有效的方法就是去学习一些东西。当你受到打击，经历挫折，从骨子里颤抖，看到你的世界被人摧毁，体验你的荣誉被踩进下水道，发生这些事情之后，你要学的只有一件事情。学习世事为何如此变化，发生了哪些变化。这是唯一可以让心永不疲惫，永不疏离，永不后悔的事情 - T.H. White
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当我们失去的时候，才知道自己曾经拥有。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 后悔是一种耗费精神的情绪.后悔是比损失更大的损失,比错误更大的错误.所以不要后悔。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 处于人生的最低谷，有个好处，就是无论从那个方向努力，都是向上。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 上帝关上了一扇门，必然会为你打开另一扇窗。你失去了一种东西，必然会在其他地方收获另一个馈赠。关键是，我们要有乐观的心态，相信有失必有得。要舍得放弃，正确对待你的失去，因为失去可能是一种生活的福音，它预示着你的另一种获得。大舍大得，小舍小得，不舍不得。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活的有趣还在于，你昨日的最大痛楚，极可能会造就你明日的最大力量。 —— 德鲁.巴里摩尔
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生最低处有一个好处，就是无论从哪个方向努力，都是向上的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** "要评估一个人，看他失败后的表现，而不是成功后的表现。" "Judge a man on how he reacts to failure, not success. " -- Martin Luther King
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 所谓成功，就是不停地经历失败，并且始终保持热情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无痛不快，无苦何甜，活着，本就是一种修行。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Growth
*** 这需要一个很疼的过程---频繁的取舍、多种关系的平衡，有跌倒有爬起、有忍受有收获...最终，可能会寻得到一种看似“伤害最小化“的方式，然后变得情绪稳定、云淡风轻、不再为任何悬而不决的事情而忧心忡忡。但也有可能在某种程序上丧失了好奇热情、勇往直前的冲动。
:PROPERTIES:
:SOULSOUP: 1
:END:
*** 人格的成长，大都是从一个遵从欲望的生物体，变成一个有多重矛盾的精神体。（弗洛伊德）
*** 你非常年轻的时候，最敏感最细腻最有激情的时候一定要背起包，睁眼看一看外面的世界，看看朝阳如何从海面上升起，看看满天神佛的寺庙日落的样子，看看外国的月亮有没有更圆一点，打开自己的心灵，前往世界的另一边，尝试一下有时差的生活，看看不同文化不同生活背景的其他人的生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 让你难过 的事情，总有一天你会笑着说出来。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每个人在他的人生发轫之初，总有一段时光，没有什么可留恋，只有抑制不住的梦想，没有什么可凭仗，只有他的好身体，没有地方可去，只想到处流浪。by E·B·怀特
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 日出东海落西山，愁也一天，喜也一天；遇事不钻角尖，人也舒坦，心也舒
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 没有人因水的平淡而厌倦饮水，也没有人因生活的平淡而摒弃生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要幻想自己成为招聘会上的宠儿，当你明白百分之七十的初中生都可以上大学时，你应该明白人们不会去崇拜一个群体的大多数的，单位需要的是工作的人 而不是当官的人 。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 社会充满竞争，大学也在竞争，赢得竞争靠的是自己的实力。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 无论你是什么级别的学生干部，即使已成为学生会主席，也要尊重普通同学，大家都是学生，更应该是朋友。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 永远别渴望做个任何人都不得罪的人，有人反对有人支持然后自己做出决定是精彩的人生。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学生会的干部，如果你尊重他们，告诉自己那是因为他们是你的学长而不是因为他们是你的上级，大家都只是学生而已。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 大学是一个新环境，你的所有过去对于他们来说是一张白纸，这是你最好的重新塑造自己形象的时候，改掉以前的缺点，以全新的形象出现。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 放假的时候，要么留在家里多陪陪父母，帮他们做点事，远走高飞的你能像以前天天守在他们身旁的时间已不多；要么多去社会中体验生活，因为你不但要懂得生活，还要学会如何去生活。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不论男人还是女人,如果在大学里还把容貌当作重要的东西而过分重视的话,可能不会吃亏,但是早晚会吃亏.可能,很可能。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不要抱怨学校的差异和现实的不公平，你的不公平对于别人而言却是公平，要靠你自己去改变不如意的环境，争取合理的公平。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你一直是一个人去食堂吃饭或者去上自习，别在意，大学里一个人是正常的，你觉得孤独？你的朋友是怕你觉得你没有自由的空间，所以别以为你没有朋友。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学会说谢谢，但谢谢并不是随便敷衍，是对别人帮助的肯定和回报；更要学会说对不起，但对不起不是借口，是对自己过错的弥补和内疚。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 当你上了高年级后,要让自己有大人的形象,大一的孩子看到你,要让他们感觉到你是他们的学长.你很成熟.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 让自己的尊严有足够大的承受力，社会是一个最喜欢打碎人尊严的地方,除了你自己,没人会为你保留它，你呆的地方是大学，所以你有空间承受失败和打击。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 不管别人怎么说大学是个提高综合能力的地方云云，如果你学习失败了，你就什么也不是——不排除意外，处世能力过分出众而成功得人是有，但你考虑好了吗？你会是那个意外吗？？
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 很多事情当你再回忆时会发现其实没什么。所以，不管当时你多么生气都告诉自己不必这样，你会发现其实真的不必。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【改变命运的十个途径】①比大多数人勤奋认真。②做好每一件小事。③微笑面对命运的不公。④时间比金钱重要。⑤养成好习惯，习惯决定命运。⑥不断与人性弱点斗争。⑦天才都是有心人。⑧机会无大小，只有时间早晚，永不嫌弃小机会。⑨等待大机会是痴心妄想。⑩坚持不懈锻炼身体。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 临危而不惧，途穷而志存；苦难能自立，责任揽自身；怨恨能德报，美丑辩分明；名利甘居后，为理愿驰骋；仁厚纳知己，开明扩胸襟；当机能立断，遇乱能慎行；忍辱能负重，坚忍能守恒；临弱可落泪，对恶敢拼争；功高不自傲，事后常反省；举止终如一，立言必有行。——南怀瑾
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我很庆幸生在这样一个家庭，即非富二代也非官二代，但我有衣服穿，有书读，不会挨饿。爸爸妈妈给了我能力范围内最好的生活，虽然不是ipad3也不是LV，但足够让我出去走走。比起花别人的钱却瞧不起别人的人，我宁愿自己努力改变生活。这样的人生我很喜欢，再来一次我还会选。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如何让自己强大】斯坦福大学教授杰弗瑞·菲佛的建议是：1、别信某人天生具备领导才能，那是鬼话；2、不要人见人爱；3、和老板的关系比业绩重要；4、帮助强者；5、建立有效的关系网，但不拉帮结派；6、接近核心资源；7、准确的自我评价；8、提早行动；9、别害怕发火；10、准确的自我评价。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【想上进就去努力培养，别说很难】 1.培养自信的语言 2.让你的笑容像阳光一样 3.紧张的时候深呼吸 4.别为小事生气 5.学会控制自己的情绪 6.悲观时，进行自我暗示 7.每天自省一小时 8.戒烟戒酒，戒掉恶习 9.永远是跑步一族 10.定期体检，为健康护航 11.养成不屈不挠的风格 12.记住别人的姓名。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【什么是人脉?】1）人脉不是你利用多少人，而是你帮助多少人！2）人脉不是多少人在面前吹捧你，而是多少人在背后称赞你！3）人脉不是辉煌时多少人奉承你，而是落魄时多少人愿意帮助你！4）人脉不是你认识多少人，而是多少人认识你！5）人脉不是你和多少人打过交道，而是多少人愿意主动和你打交道！
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 读大学的价值也许在，能认识未来几十年最重要的朋友，能分辨哪些人自己一辈子都不会交往，能集中解决很多困惑，从而形成自己的原则，开始学会拒绝。读大学的价值也在于你明白世界上有很多优秀的人，你开始有靠近的动力。读书，不是为了拿文凭或发财，而是成为一个有温度懂情趣会思考的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如何保持年轻】1. 保持求知若渴：不光对知识，也应积极向身边优秀的人才学习，不论年龄大小；2. 保持热情和能量：时常微笑，正能量会感染周围员工；3. 保持好奇心：通过好奇继续学习、成长；4. 不被规则束缚：勇于尝试新想法；5. 看到每个人的优点：挖掘员工潜能。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【摆脱“穷忙”人生的十大黄金定律】1、思考你想要的生活；2、明白你为谁工作；3、找到“穷”与“富”，“忙”与“闲”的平衡；4、你必须积累财富；5、适时地控制欲望；6、清晰的人生规划；7、持久的耐力；8、良好的人际关系氛围；9、培养自己的业余爱好；10、不断挑战自己。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 陈道明说，好男人的基本标准：不一定要浪漫，但一定要负责任。不一定要挣大钱，但一定要养家。不一定要事事听父母，但一定要有孝心。不一定要三从四德，但一定要宠老婆。不一定要飞黄腾达，但一定要有时间陪家人。不一定要管孩子，但一定要爱孩子。不一定要大男子主义，但大事发生一定要拿得了主意。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生就像是一座钟摆，从右摆到左，从痛苦摆到苦闷。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 生活不可能像你想象的那么好，但也不会像你想像得那么糟，我觉得人的脆弱和坚强都超乎自己的想象。有时，我可能脆弱得一句话就泪流满面，有时，我也发现自己咬着牙走了很长的路。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你所经历的一切，都是你自己造就的。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 归根结底，只要想着做一切事到最后的受益者都是自己，我们就不会抱怨太多。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 你想过普通人的生活就会遇上普通的挫折 你想过上最好的生活就一定会遇上最强的伤害。世界很公平，你想要最好的，就一定会给你最痛的。能闯过去，你就是赢家；闯不过去，那就乖乖做个普通人吧。所谓成功，并不是看你有多聪明，也不是要你出卖自己，而是看你能否笑着渡过难关。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人之一生，如负重远行，不可急于求成；以受约束为常事，则不会心生不满；常思贫困，方无贪婪之念；忍耐乃长久无事之基石；愤怒是敌；只知胜而不知败，必害其身；常思己过，莫论人非；不及尚能补，过之无以救。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 但求成长，不求成功，让成功成为成长的必然结果，这就是成功最正确的道路。如果我们只向往作为结果的成功，人生必然拔苗助长，最后枯萎而死。一只蝴蝶飞向天空，展示了她所有的美丽，但在美丽的背后，她曾经有过毛毛虫笨拙的爬行，织丝成茧的辛劳，在黑暗之中的等待和化蛹成蝶的痛苦。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1.一杯清水因滴入一滴污水而变污浊,一杯污水却不会因一滴清水的存在而变清澈。2.最小的善行也会胜过最大的善念。3.世界没有悲剧和喜剧之分,如果你能从悲剧中走出来,那就是喜剧,如果你总沉缅于喜剧之中,那它就是悲剧。4.真正的朋友不是在一起有聊不完的话,而是不说一句话也不觉得尴尬。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个优秀人物的八大特征：1、热爱生命，相信未来；2、对工作专注、喜欢并创造性发挥；3、关心他人感受；4、追求成就感和荣誉感；5、进取心强，不断学习成长；6、对于财富、名声、权力没有过分的贪欲，得失之间天高云淡；7、真诚、坦率、阳光的个性；8、自己当人看，但不把自己太当人看。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 《成熟定律》 1果实的成熟不是颜色美丽,而是味道甘甜;2孩子的成熟不是年龄长大,而是独立克制;3女人的成熟不是能力非凡,而是温良贤淑;4男人的成熟不是圆融处世,而是善于担当;5性格的成熟不是心平气和,而是能屈能伸;6领导成熟的标志,不是发号施令,而是能听不同的声音。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 很多人面对未来，总是左思考右打算，就是不敢迈开大步向前走。其实规划好的人生并不多，义无反顾勇敢向前的人常常得到更多，走得也更远。生命的远行不需要太多的准备，上帝给你两条长腿和坚实的脚掌，就是为了让你前行。向哪里走？让心告诉你。考研、出国、工作都会有前途。不同的路不同的风景。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【人与人之间的差距是这样炼成的】1别人休息的时候，你在加班，或参加各种培训班；2别人嘲笑的时候，你在闷头苦干；3别人想着如何找工作的时候，你在想着如何做得更好；4别人抱怨的时候，你在思考解决之道；5别人在想着归入哪一派时，你在寻求专业突破；6每天坚持写专业心得，参与讨论。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1、每个人都会有不幸的时候，不要怨天尤人，也不要幸灾乐祸。2、每个人都会有幸运的时候，不要忘乎所以，也不要身在福中不知福。3、每个人都有不可理喻的地方，不要苛求别人，也不必埋怨自己。4、每个人都各怀天赋，不要因为鱼不会爬树，就把鱼说成一无所长。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 要“八交九不交”：『一』八交：胜己者；盛德者；趣味者；肯吃亏者；直言者；志趣广大者；惠在当厄者，体人者。『九不交』：志不同者；谀人者；恩怨颠倒者；好占便宜者；全无性情者；不孝不悌者；愚人者；落井下石者；德薄者。——所以，你有什么样的朋友，你就是什么样的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 慢慢的，你会养成另外一种心情对付过去的事：就是能够想到而不再惊心动魄，能够从客观的立场分析前因后果，做将来的借鉴，以免重蹈覆辙。一个人惟有敢于正视现实，正视错误，用理智分析，彻底感悟，才不至于被回忆侵蚀。我相信你逐渐会学会这一套，越来越坚强的。——《傅雷家书》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1.脾气泄露了你的修养，沉默道出了你的品味。2.当感觉天快塌下来时，实际上是自己站歪了！3.不要把自己看得太强，以致无视外因的成就；不要把自己看的太轻，以致成为他人的踏板。4.总有人会迷失方向，否则真理的路上将人满为患。5.有棱有角的害处是，别人啃起你来十分方便。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 1.压力最大的时候，效率可能最高。2.最忙的时候，学的东西可能最多。3.最惬意的时候，往往是失败的开始。4.寒冷到了极致时，太阳就要光临。5.少说多做，句句都会得到别人的重视；多说少做，句句都会受到别人的忽视。6.宽容不是软弱而是融合。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 青春终究是幸福，因为它有未来。 ——果戈理
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【如果你感到很迷茫】①先处理心情，再处理事情；②最困难的时候，就是最接近成功的时候；③不为模糊不清的未来担忧，只为清清楚楚的现在努力；④宽容他人对你的冒犯；⑤不要无缘无故的妒忌；⑥只为成功找方法，不为失败找借口；⑦不要看我失去什么，只看我还拥有什么；⑧用最放松的心态对待一切艰难。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 我一直信奉以下做事的三原则：1）有勇气来改变可以改变的事情；2）有度量接受不可改变的事情；3）有智慧来分辨两者的不同。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 友善地对待你讨厌的人，正是你成熟的表现。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 学会与自己的伤痛和平共处，这就是成长的意义。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 许多事情只是当时身临其境时很痛苦，其实回过头来想想也没什么。那些当时你觉得快要了你命的事情，那些你觉得快要撑不过去的境地，都会慢慢地好起来。就算再慢，只要你愿意等，它也会成为过去。而那些你暂时不能战胜的，不能克服的，不能容忍的，就告诉自己：凡是不能杀死你的，最终都会让你更强。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 十年前你是谁，一年前你是谁，甚至昨天你是谁，都不重要。重要的是，今天你是谁，以及明天你将成为谁。Who you were 10 years ago, a year ago, or even yesterday isn't important. What's important is who you are today, and who you'll be tomorrow.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 这个世界上谁比谁明白的道理少呢。我愈发觉得，所谓“懂事”，不是你手里的人生哲理集有多厚，而是你的情绪和行为控制能力有多强。情绪稳定简直是太牛逼的事儿了，别拼谁更懂，拼谁更能停，谁更能等。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【保龄球效应】保龄球投掷对象是10个瓶子，你如果每次砸倒9个瓶子，最终得分90分；而你如果每次能砸倒10个瓶子，最终得分240分。社会记分规则就是这样：只要你每次比别人稍微优秀一点，能再多坚持一会，就可能赢得更多机会。这种机会叠加就是人生效应的逐级放大，最终造成人与人之间巨大的落差
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 被人信赖是一笔用金钱买不到的财富。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** "在你成为领导者之前，成功就是做使自己成长的事；但在你成为领导者之后，成功就是做使他人成长的事” － 杰克·韦尔奇 （Jack Welch）
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人要做成事情，需要三个要素；第一是意愿，有强烈意愿的人更容易百折不挠做成事情；第二是能力，能力包括知识、眼光、经验、人品、个性等，有能力的人一般判断力都不错；第三是资源，能否调动人脉关系，是否有财力上支持等。但最重要的是意愿和能力，有了意愿和能力，早晚能够逢山开路，遇水搭桥。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 眼光有多远，思想就有多远。思想是无垠的，它取决于你的见识。思想是深邃的，它取决于你的态度。走出去，多邂逅陌生的人，多遇见新鲜的事。让脚步载着目光，穿过繁华、荒凉，穿越时尚、古老，于熟悉中发现陌生，于喧闹中发现世态，于静谧中发现永恒，于平常中发现真理。善于思考的人都是善于发现的人。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 每一个不曾起舞的日子，都是对生命的辜负。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 年轻的时候最大的财富不是你的青春，你的美貌，也不是你的充沛的精力，而是你有犯错误的机会。如果年轻的时候你都不能追随自己心里强烈的愿望，去为自己认为值得干的事冒一次风险，哪怕是犯一次错误的话，那青春多么苍白呀！——杨澜
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 人生如路，须在荒凉中走出繁华的风景来。——七堇年
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 一个人二十岁出头的时候，除了仅剩不多的青春以外什么都没有，但是你手头为数不多的青春却能决定你变成一个什么样的人。这个世界那么多不顺心的事情又能怎么样，对他们说一句fuck you，然后继续努力做好自己应该做的事情。——《要么滚回去，要么拼命》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 总有些事，管你愿不愿意，它都要发生，你只能接受；总有些东西，管你躲不躲避，它都要来临，你只能面对
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 青春是一场无知的奔忙，总会留下颠沛流离的伤，我多么希望明天有太阳，灼烧我那腐烂的梦想。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 摔倒了又怎样，至少我们还年轻。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 二十岁到三十岁这段时间，是人生中最艰苦的一段岁月------ 逐渐退去学生的身份，承担着渐长的责任，或许拿着与工作量不匹配的薪水，艰难的权衡事业和感情，不情愿的建立人脉…但你总得撑下去，上天只会给我们能过得去的坎...
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 越有故事的人越沉静简单，越肤浅单薄的人越浮躁不安
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 正如故乡是用来怀念的，青春就是用来追忆的，当你怀揣着它时，它一文不值，只有将它耗尽后，再回过头看，一切才有了意义——爱过我们的人和伤害过我们的人，都是我们青春存在的意义。——《致我们终将逝去的青春》
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 【人生智慧】1.机遇总是有的，如果把握不住，不要怨天忧人，只因自己不够优秀；2.不要把时间当垃圾处理，唯有珍惜光阴，才能提升生命的质量；3.两点之间未必直线最短，有时迂回曲折能够更快地抵达终点；4.如果错了，那就停止，如果得不到，那就放弃；5.赶路并非越快越好，把握正确的方向最重要。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 如果你想任性，那就先学会承受，能承受后果才可以任性。如果你想独立，那就先学会坚强，能忍住伤痛，才可以独立。如果你想放肆的爱，那就先学会遗忘，忘掉失恋痛楚，才可以大胆爱。你可以去做一切事情，但前提是不会为结果伤悲。一个人真正的强大，并非看他能做什么，而是看他能承担什么。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 趁年轻，走自己想走的路。没理由，不去闯。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 大学里应该去去想去的地方，读读应该读的书，逃一逃想逃的课，追一追想追的人，喝一喝想喝的酒，打一打想打的架，都是些健康快乐、充沛的事情。大学要做些什么，就是要做些在30岁、40岁之后回想起来，依然能够感到热泪盈眶的事情，这就是大学，这就是青春时代应该做的事情。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 听过很多道理,依旧过不好一生
:PROPERTIES:
:SOULSOUP: 1
:END:
*** 1，再难也要坚持。2，再好也要淡泊。3，再差也要自信。4，再多也要节省。5，再冷也要热情。

*** 生命中总有那么一段时光，充满不安，可是除了勇敢面对，我们别无选择。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 旅行最大的好处，不是能见到多少人，见过多美的风景，而是走着走着，在一个际遇下，突然重新认识了自己。
:PROPERTIES:
:SOULSOUP: 1
:END:
*** 青春就是疯狂地奔跑，然后华丽地跌倒。

*** 成功人生四步曲：1、耐住寂寞；2、抵住诱惑；3、懂得放弃；4、学会选择。
:PROPERTIES:
:SOULSOUP: 1
:END:

** Others
*** Don't You Cry, Babe. Tears Are Made For Non-Ugly People.
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 梵高对弟弟说过＂没有什么是不朽的，包括艺术本身。唯一不朽的，是艺术所传递出来的对人和世界的理解。＂----摘自「看见」
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 很多时候人的差别在于业余时间，而一个人的命运决定于晚上8点到10点之间。每晚抽出2个小时的时间用来阅读、进修、思考或参加有意的演讲、讨论，你会发现，你的人生正在发生改变，坚持数年之后，成功就会向你招手。
:PROPERTIES:
:SOULSOUP: 1
:END:

*** 路飞(⊙o⊙)，索隆（=_≠），香吉（º_\\\），乌索普⊙﹄⊙，乔巴⊙ω⊙，弗兰其⊙△⊙，布鲁\^O^/，娜美$3$，罗宾=L=
:PROPERTIES:
:SOULSOUP: 1
:END:

* 文化常识


** 字词

*** 吋                                                            :吋:英寸:

【汉字】吋
【拼音】cùn(也读作yīng-cùn)

英寸（英美制长度单位，1英尺=12英寸）的简写。1吋=0.762寸



** 英寸                                                     :英寸:inch:单位:
:PROPERTIES:
:ARTIST:   陈迹迅
:END:

1 英寸 (吋) = 2.54 厘米
1 英寸 (吋) = 0.0254 米
1 英寸(吋) = 0.762 市寸
1 厘米 =0.39370078740157477 英寸（吋）
1 市寸 = 1.312336英寸(吋)
1 米 = 39.370078740157 英寸 (吋)
