* Windows
** windows emacs

** winodws git hub
http://blog.csdn.net/wh_19910525/article/details/8128916

1. 下载msysgit
   目前windows版本的git有几种实现，但我们选择msysgit发行版，这是目前做
   得兼容性最好的。

   下载地址：http://code.google.com/p/msysgit/downloads/list

   使用默认配置安装Git。这个不用多说，一路Next就可以，如果对各种选项不
   熟悉，建议使用默认配.

2. ssh
   GitHub选择的默认通信方式是SSH，所以要先在Git里面生成SHH Key，打开
   Git Bash在其中输入如下命令：
   *ssh-keygen -t rsa -C "3sdfsf80@xinlang.com"*

   之后会让你选择是否对存放SSH Key的文件夹进行加密，一般都不需要的。一
   路回车，就OK了。

   在c盘，当前用户文件夹下，有个.ssh 文件夹，在里边 找到 id_rsa.pub文
   件，用记事本打开，复制其中的全部内容。

   登陆你的GitHub账户，依次点击Account Settings > SSH Public Keys >
   Add another public key，把id_rsa.pub中的内容拷贝进去 。

** MS: 参考文献自动生成
尾注法方法如下以Word2003为例

1. 光标移到要插入参考文献的地方，菜单中“插入”——“引用”-“脚注和尾
   注”。

2. 对话框中选择“尾注”，编号方式选“自动编号”，所在位置可以选“节的
   结尾”或“文档结尾”。

3. 如“自动编号”后不是阿拉伯数字，选右下角的“选项”，在编号格式中选
   中阿拉伯数字。

4. 确定后在该处就插入了一个上标“1”，而光标自动跳到文章最后，前面就是
   一个上标“1”，这就是输入第一个参考文献的地方。

5. 将文章最后的上标“1”的格式改成正常（记住是改格式，而不是将它删掉重
   新输入，否则参考文献以后就是移动的位置，这个序号也不会变），再在它
   后面输入所插入的参考文献（格式按杂志要求来慢慢输，好像没有什么办法
   简化）。

6. 对着参考文献前面的“1”双击，光标就回到了文章内容中插入参考文献的地
   方，可以继续写文章了。

7. 在下一个要插入参考文献的地方再次按以上方法插入尾注，就会出现一个
   “2”（Word已经自动为你排序了），继续输入所要插入的参考文献。

   标号上的方括号如何加呢？

8. 用的尾注，在菜单中的“编辑”——“替换”中“查找内容”填写 ^e，替换为
   [^&]即可：

9. 用的脚注，在菜单中的“编辑”——“替换”中“查找内容”填写^f，替换为
   [^&]便可以了（这里建议在一篇文章都写完后再将方括号加上会省去很多意
   外的麻烦）

10. 所有文献都引用完后，你会发现在第一篇参考文献前面一条短横线（页面视
    图里才能看到），如果参考文献跨页了，在跨页的地方还有一条长横线，这
    些线无法选中，也无法删除。这是尾注的标志，但一般科技论文格式中都不
    能有这样的线，所以一定要把它们删除。

    还没完，删除横线的方法.

11. 切换到普通视图，菜单中“视图”——“脚注”，这时最下方出现了尾注的编
    辑栏。

12. 在尾注右边的下拉菜单中选择“尾注分隔符”，这时那条短横线出现了，选
    中它，删除.

13. 再在下拉菜单中选择“尾注延续分隔符”，这是那条长横线出现了，选中它，
    删除。

14. 切换回到页面视图，参考文献插入已经完成了。

这时，无论文章如何改动，参考文献都会自动地排好序了。如果删除了，后面的参考文献也会自动消失，绝不出错。参考文献越多，这种方法的优势就越强大。
** 捕获系统音频
- State "DONE"       from "TODO"       [2015-11-13 五 21:01]

FOR: 德语录制

Google *streaming audio recorder*

Wondershare Streaming Audio Recorder，简洁易用

Evernote & BaiduYun（破解）

虚拟机中运行的不能录制真实系统中的音频

** eps
eps文件是封装的PostScript（Encapsulated PostScript）格式。PostScript
语言是Adobe 公司设计用于向任何支持PostScript语言的打印机打印文件的页
面 *描述语言* 。除了它是被优化用于纸张上打印文字和图像之外，它像Basjc 语
言、C语言或任何其它编程语言一样。当你在 PostScript打印机上工作并告诉
文字处理器（或任何其它的应用程序）打印页面时，计算机就会用PostScript
语言编写一个程序描述该页面，并将这个程序传送给打印机。打印机实际上其
中装有一台功能齐全的计算机和PostScript 语言解释器执行这个程序，将图形
画在内存中的虚拟纸张上，然后将其打印到纸上。

*** 小结
EPS是一种 *矢量图片格式*


** 标签云                                                              :标签云:
标签云或文字云是关键词的视觉化描述，用于汇总用户生成的标签或一个网站的
文字内容。标签一般是独立的词汇，常常按字母顺序排列，其重要程度又能通过
改变字体大小或颜色来表现，所以标签云可以灵活地依照字序或热门程度来检索
一个标签。
+ [[https://zh.wikipedia.org/wiki/%e6%a0%87%e7%ad%be%e4%ba%91][wiki]]
+ [[
http://www.zhihu.com/question/21128950][知乎]]
+ http://worditout.com/ 这个网站很好

*** 小结
标签云： *关键词频率的可视化*

** 参考文献标准格式

*** 参考文献类型
+ 专著［M］
+ 论文集［C］
+ 报纸文章［N］
+ 期刊文章［J］
+ 学位论文［D］
+ 报告［R］
+ 标准［S］
+ 专利［P］
+ 论文集中的析出文献［A］
*** 电子文献类型
+ 数据库［DB］
+ 计算机［CP］
+ 电子公告［EB］
*** 电子文献的载体类型
+ 互联网［OL］
+ 光盘［CD］
+ 磁带［MT］
+ 磁盘［DK］
*** 专著、论文集、学位论文、报告
*［序号］主要责任者.文献题名［文献类型标识］.出版地：出版者，出版年.起止页码（可选）*
［1］刘国钧，陈绍业.图书馆目录［M］.北京：高等教育出版社，1957.15-18.

*** 期刊文章
*［序号］主要责任者.文献题名［J］.刊名，年，卷（期）：起止页码*
［1］何龄修.读南明史［J］.中国史研究，1998,(3):167-173.
［2］OU J P，SOONG T T，et al.Recent advance in research on applications of passive energy dissipation systems［J］.Earthquack Eng,1997,38(3):358-361.

*** 论文集中的析出文献
*［序号］析出文献主要责任者.析出文献题名［A］.原文献主要责任者（可选）.原文献题名［C］.出版地：出版者，出版年.起止页码*
［7］钟文发.非线性规划在可燃毒物配置中的应用［A］.赵炜.运筹学的理论与应用——中国运筹学会第五届大会论文集［C］.西安：西安电子科技大学出版社，1996.468.

*** 报纸文章
*［序号］主要责任者.文献题名［N］.报纸名，出版日期（版次）*
［8］谢希德.创造学习的新思路［N］.人民日报，1998-12-25（10）.

*** 电子文献
*[文献类型/载体类型标识]：[J/OL]网上期刊、[EB/OL]网上电子公告、*
*[M/CD]光盘图书、[DB/OL]网上数据库、[DB/MT]磁带数据库*
［序号］主要责任者.电子文献题名［电子文献及载体类型标识］.电子文献的出版或获得地址，发表更新日期/引用日期
［12］王明亮.关于中国学术期刊标准化数据库系统工程的进展［EB/OL］.http://www.cajcd.edu.cn/pub/wml.html，1998-08-16/1998-10-01.
［8］万锦.中国大学学报文摘（1983-1993）.英文版［DB/CD］.北京：中国大百
*科全书出版社，1996.

** 键盘数字键指法
+ 左小: 1
+ 左无: 2
+ 左中: 3
+ 左食: 4,5
+ 右食: 6,7
+ 右中: 8
+ 右无: 9
+ 右小: 0

扩展: 标准指法
1) 左小指: `  1  Q  A  Z
2) 左无名指: 2  W  S  X
3) 左中指: 3  E  D  C
4) 左食指: 4  5  R  T  F  G  V  B
5) 左  右拇指: 空白键
6) 右食指: 6  7  Y  U  H  J  N  M
7) 右中指: 8  I  K  ,
8) 右无名指: 9  O  L  .
9) 右小指: 0  -  =  P  ()  ()  ;  '  /  \

* PDF                                                                   :pdf:
* Chrome                                                             :chrome:
* Others
** Knowledge
*** 光化学污染

光化学烟雾主要是由于汽车尾气和工业废气排放造成的，汽车尾气中的烯烃类碳
氢化合物和二氧化氮（NO_{2}）被排放到大气中后，在强烈的阳光紫外线照射下，
会吸收太阳光所具有的能量。这些物质的分子在吸收了太阳光的能量后，会变得
不稳定起来，原有的化学链遭到破坏，形成新的物质。这种化学反应被称为光化
学反应，其产物就是含剧毒的光化学烟雾。

*** gallon

加仑是一种容（体）积单位，英文全称gallon,简写gal,分英制加仑、美制加仑。

1加仑(美)=3.785 412升
1加仑(英)=4.546 092升

*** 480p  垂直分辨率
480p 是一种 *视频解析度标准* 。字母p表示逐行扫描 （progressive scan），数
字 480 表示其 *垂直分辨率* ，也就是垂直方向有480条水平线的扫描线，即通常所
说的标准电视格式(standard-definition television，SDTV)。横纵比（aspect
ratio）为4:3的视频源，每条水平线分辨率有640个像素，纵横比为3:2的视频源，
每条水平线分辨率有720个像素，纵横比为16:10的视频源，每条水平线分辨率有
800个像素，纵横比为16:9的视频源，而每条水平线分辨率有854个像素。

*** GFW 中国网络防火墙

The Great Fire Wall of China的简写，意指“中国网络防火墙”(字面意为
“中国防火长城”)，这是对“国家公共网络监控系统”的俗称，国内简称“防
火长城”。

GFW是“金盾工程”的一个子功能。“金盾工程”是以公安信息网络为先导，以
各项公安工作信息化为主要内容，建立统一指挥、快速反应、协同作战机制，在
全国范围内开展公安信息化的工程，主要包括建设公安综合业务通信网、公安综
合信息系统、全国公安指挥调度系统以及全国公共网络监控中心等。该项目2003
年开始生效。一般所说的GFW，主要指公共网络监控系统，尤其是指对境外涉及
敏感内容的网站、IP地址、关键词、网址等的过滤。

GFW的效果通常为，国内网络用户无法访问某些国外网站或者网页；或者国外网
络用户无法访问国内的某些网站或者网页。这里的无法访问，有永久性的无法访
问（比如色情网站），也有因为URL中含有敏感关键词或者网页上有敏感内容而
暂时性的无法访问。

国家防火墙并非中国的专利。实际上，美国也有国家网络监控系统，对进出美国
的每一封电子邮件进行内容扫描。不同的是，中国的国家防火墙会直接切断敏感
连接，而美国的国家防火墙（考虑更名）则只是做数据监控记录。伊朗、巴基斯
坦、乌兹别克斯坦、北非共和国、叙利亚、缅甸、马尔代夫、古巴、北韩、南韩、
沙特阿拉伯、阿拉伯联合酋长国、也门使用与金盾类似的国家防火墙。
