#+TITLE: Tiger
#+AUTHOR: Tiger D Wong
#+EMAIL: buaaben@163.com
#+STARTUP: CONTENTS
#+OPTIONS: H:4 num:t
#+LATEX_CLASS: ctexbook


** Evernote
*** 整理技巧
1. Evernote PC客户端(Ubuntu Wine) 生成目录，并寻出为HTML
2. Emacs打开HTML文件(w3m-find-file)
3. ORG拷贝 org-w3m-copy
4. 正则替换

#+BEGIN_EXAMPLE
 1. [[evernote:///view/11551545/s52/3002d5ec-ab74-4c3d-871e-7c07514daf80/3002d5ec-ab74-4c3d-871e-7c07514daf80/][string::npos - C++ Reference]]
https://app.yinxiang.com/shard/s52/nl/11551545/3002d5ec-ab74-4c3d-871e-7c07514daf80?title=string%3A%3Anpos%20-%20C%2B%2B%20Reference
#+END_EXAMPLE

*观察规律，正则替换*
#+BEGIN_EXAMPLE
  ^[0-9, ]*\..+view/\(.*\)/\(.*\)/\(.*\)/.*/\]\[\(.*\)\]\]$
  ,***** [[https://app.yinxiang.com/shard/\2/nl/\1/\3?title=\4][\4]]
#+END_EXAMPLE

** Kindle


** ideas
*** 一个人摆脱幼稚的标志之一，就是不再以自己读的书、看的电影、听的音乐为理由而产生优越感。

你爱看书，值得鼓励，但这并不代表你有理由因此产生任何的优越感，将那些看
消遣娱乐节目的人斥为低俗，然后上知乎寻找与你志同道合的小清新。我虽然没
有工作，但我知道很多养家糊口压力大、工作繁重的人喜欢看爆米花电影，因为
平时的生活已经够残酷了，他们没必要在难得的放松时刻里去寻找”深刻“，相
反很多身无长技的啃老族，每天为赋新词强说愁，最喜欢用大卫林奇的电影证明
自己的人生是深刻的。

说实话，一般喜欢拿自己消费的文化产品标榜自己的人，他们所谓的好书或好节
目，最多也就是罗胖或高晓松级别的，再扯一点”平庸之恶“、”乌合之众
“、”娱乐至死“之类的民科概念，觉得自己虽然活在猪圈里却成了精神贵族。

** knowledge
*** 长镜头(时间较长的单一镜头)
长镜头是一种拍摄手法，它相对于蒙太奇拍摄方法。 这里的“长镜头”，指的
不是实体镜头外观的长短或是焦距，也不是摄影镜头距离拍摄物的远近，而是拍
摄之开机点与关机点的时间距，也就是影片的片段的长短。长镜头并没有绝对的
标准，是相对而言较长的单一镜头。通常用来表达导演的特定构想和审美情趣，
例如文场戏的演员内心描写、武打场面的真功夫等。

长镜头是指用比较长的时间（有的长达10分钟），对一个场景、一场戏进行连续
地拍摄，形成一个比较完整的镜头段落。顾名思义，就是在一段持续时间内连续
摄取的、占用胶片较长的镜头。这样命名主要是相对短镜头来对称的。摄影机从
一次开机到这次关机拍摄的内容为一个镜头，一般一个时间超过10秒的镜头称为
长镜头。长镜头能包容较多所需内容或成为一个蒙太奇句子（而不同于由若干短
镜头切换组接而成的蒙太奇句子）。其长度并无明确的、统一的规定。是相对于
‘短镜头’的讲法。

** Habbits
*** 如何科学熬夜

夜深人静的时候的确注意力很容易长时间集中，学习效率也高一些。想想以后熬
夜通宵可能会成为家常便饭，所以提前尝试一下怎样熬夜才会更值得一些。熬夜
注意方法很重要，但更重要的在于身体是革命的本钱。所以，多吃肉以增加体力，
多跑步以增强恢复力。 from weibo-131025
1. 熬夜时
   + 准备热食
   + 晚饭不要吃太饱(胃肠负担重导致大脑缺氧,容易犯困)
   + 注意保暖,胃部和足部
   + 多喝白开水(熬夜身体缺水),一次喝一整杯
   + 忙完再休息,累了也不要中途上床休息,突然开突然关的,对身体和状态都没益处
   + 困乏时可喝咖啡或茶叶提神
     + 热饮
     + 低浓度,以免伤胃
   + 时时做深呼吸,熬夜大脑需氧量增加
   + 千万不要一坐一整夜,每小时起来走走
   + 事情忙完要收心,即使不睡觉,也要坐在椅子上收心
2. 熬夜后
   + 睡前或醒后利用五到十分钟敷一下脸来补充缺水的肌肤
   + 起床后利用冷,热交替刺激脸部血液循环
   + 涂抹保养品时先按摩脸部五分钟
   + 早上起床后先喝一杯枸杞茶,补气养身
     + 枸杞一把,红枣3~4粒
     + 红枣切开
     + 开水冲泡,或煮
     + 冲完开水后等入味后再喝
   + 做个简单柔软操,活动一下筋骨
   + 早饭要吃饱,不吃凉
3. 关于吃
   + 咖啡和茶,提神但
     + 维持时间短
     + 而且消维生素B
     + 咖啡碱的利尿作用,导致脱水
   + 缺少维生素B群的人容易疲劳,依赖咖啡因会形成恶性循环
   + 补充维生素B
   + 甜食是大忌
   + 吃香蕉等水果
   + 日常饮食合理,补充维生素A(预防视力减弱)和维生素B
     + 维生素A: 胡萝卜,韭菜,鳗鱼等
     + 维生素B: 瘦肉,鱼肉,猪肝等
     + 干果:花生,杏仁,核桃等

** Running
** Reading
** Guita
** web login
*** stackexchange 注册
=163 ^Se_6$=
